-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["海灵护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "魔力再生率提高 (20-30)%",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["珊瑚护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "生命每秒再生 (2-4)",
	implicitModTypes = { { "flat_life_regen", "resource", "life" }, },
	req = { },
}
itemBases["琥珀护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(20-30) 力量",
	implicitModTypes = { { "attribute" }, },
	req = { level = 5, },
}
itemBases["翠玉护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(20-30) 敏捷",
	implicitModTypes = { { "attribute" }, },
	req = { level = 5, },
}
itemBases["海玉护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(20-30) 智慧",
	implicitModTypes = { { "attribute" }, },
	req = { level = 5, },
}
itemBases["帝金护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "物品稀有度提高 (12-20)%",
	implicitModTypes = { {  }, },
	req = { level = 8, },
}
itemBases["黑曜护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(10-16) 全属性",
	implicitModTypes = { { "attribute" }, },
	req = { level = 20, },
}
itemBases["青玉护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(16-24) 敏捷与智慧",
	implicitModTypes = { { "attribute" }, },
	req = { level = 16, },
}
itemBases["玛瑙护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(16-24) 力量和智慧",
	implicitModTypes = { { "attribute" }, },
	req = { level = 16, },
}
itemBases["黄晶护身符"] = {
	type = "Amulet",
	tags = { amulet = true, default = true, },
	implicit = "+(16-24) 力量和敏捷",
	implicitModTypes = { { "attribute" }, },
	req = { level = 16, },
}
itemBases["血色护身符"] = {
	type = "Amulet",
	tags = { not_for_sale = true, default = true, amulet = true, },
	implicit = "+(20-30)% 火焰抗性",
	implicitModTypes = { { "elemental", "fire", "resistance" }, },
	req = { },
}
itemBases["潜能项链"] = {
	type = "Amulet",
	tags = { not_for_sale = true, default = true, amulet = true, },
	implicit = "有 1 个插槽",
	implicitModTypes = { {  }, },
	req = { level = 5, },
}
itemBases["碧珠护身符"] = {
	type = "Amulet",
	tags = { amuletatlas1 = true, not_for_sale = true, atlas_base_type = true, amulet = true, default = true, },
	implicit = "魔力再生率提高 (48-56)%",
	implicitModTypes = { { "resource", "mana" }, },
	req = { level = 77, },
}
itemBases["大理石护身符"] = {
	type = "Amulet",
	tags = { amuletatlas2 = true, not_for_sale = true, atlas_base_type = true, amulet = true, default = true, },
	implicit = "生命每秒再生 (1.2-1.6)",
	implicitModTypes = { { "resource", "life" }, },
	req = { level = 74, },
}
itemBases["海晶护符"] = {
	type = "Amulet",
	tags = { not_for_sale = true, atlas_base_type = true, amuletatlas3 = true, amulet = true, default = true, },
	implicit = "能量护盾充能时间提前 (10-15)%",
	implicitModTypes = { { "energy_shield", "defences" }, },
	req = { level = 74, },
}
itemBases["星盘项链"] = {
	type = "Amulet",
	tags = { not_for_sale = true, default = true, amulet = true, },
	implicit = "基底词缀不能改变\n具有裂界者、塑界者和所有征服者影响效果",
	implicitModTypes = { {  }, {  }, },
	req = { level = 69, },
}
itemBases["朴实项链"] = {
	type = "Amulet",
	tags = { not_for_sale = true, default = true, amulet = true, },
	implicit = "允许的前缀 -1\n允许的后缀 -1\n基底词缀不能改变\n外延词缀幅度提高 25%",
	implicitModTypes = { {  }, {  }, {  }, {  }, },
	req = { level = 24, },
}
itemBases["杰特护身符"] = {
	type = "Amulet",
	hidden = true,
	tags = { demigods = true, not_for_sale = true, default = true, amulet = true, },
	implicit = "+(8-12)% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	req = { level = 12, },
}

itemBases["黑牙魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "有 1 个插槽",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["脊骨魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "魔力上限提高 (20-30)%",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["灰烬魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "火焰伤害提高 (20-30)%",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "fire" }, },
	req = { },
}
itemBases["孤角魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "闪电伤害提高 (20-30)%",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "lightning" }, },
	req = { },
}
itemBases["深渊魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "冰霜伤害提高 (20-30)%",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "cold" }, },
	req = { },
}
itemBases["碎骨魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "全局物理伤害提高 (20-30)%",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	req = { },
}
itemBases["亡手魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "混沌伤害提高 (19-31)%",
	implicitModTypes = { { "chaos_damage", "damage", "chaos" }, },
	req = { },
}
itemBases["不朽魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "+1 【魔卫复苏】数量上限",
	implicitModTypes = { { "minion" }, },
	req = { },
}
itemBases["腐首魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "鱼咬的灵敏度提高 (30-40)%",
	implicitModTypes = { { "green_herring" }, },
	req = { },
}
itemBases["巨颚魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "攻击与施法速度提高 (6-10)%",
	implicitModTypes = { { "attack", "caster", "speed" }, },
	req = { },
}
itemBases["虫蛹魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "法术伤害提高 (20-30)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	req = { },
}
itemBases["狂癫魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "攻击伤害提高 (20-30)%",
	implicitModTypes = { { "damage", "attack" }, },
	req = { },
}
itemBases["幻爪魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "攻击和法术暴击率提高 (40-50)%",
	implicitModTypes = { { "critical" }, },
	req = { },
}
itemBases["皇骨魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "生命每秒再生 2",
	implicitModTypes = { { "resource", "life" }, },
	req = { },
}
itemBases["亡爪魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "+(24-36)% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	req = { },
}
itemBases["断螈魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "(4-6)% 的几率使敌人受到冰冻，感电与点燃",
	implicitModTypes = { { "elemental", "fire", "cold", "lightning", "ailment" }, },
	req = { },
}
itemBases["咒箍魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "全局防御提高 (15-25)%",
	implicitModTypes = { { "defences" }, },
	req = { },
}
itemBases["双子魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中火焰伤害的 50% 转为冰霜伤害",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["双子魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中火焰伤害的 50% 转为闪电伤害",
	implicitModTypes = { { "elemental", "fire", "lightning" }, },
	req = { },
}
itemBases["双子魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中冰霜伤害的 50% 转为火焰伤害",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["双子魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中冰霜伤害的 50% 转为闪电伤害",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["双子魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中闪电伤害的 50% 转为冰霜伤害",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["双子魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中闪电伤害的 50% 转为火焰伤害",
	implicitModTypes = { { "elemental", "fire", "lightning" }, },
	req = { },
}
itemBases["齿鲨魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "生命上限提高 (8-12)%",
	implicitModTypes = { { "resource", "life" }, },
	req = { },
}
itemBases["尖角魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "投射物会穿透 2 个额外目标",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["潜能魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "物品掉落数量提高 (6-10)%",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["三鼠魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "所有属性提高 (12-16)%",
	implicitModTypes = { { "attribute" }, },
	req = { },
}
itemBases["双猴魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "效果区域扩大 (5-8)%",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["长牙魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "(4-6)% 额外物理伤害减伤",
	implicitModTypes = { { "physical" }, },
	req = { },
}
itemBases["死羽魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "伤害提高 (25-35)%",
	implicitModTypes = { { "damage" }, },
	req = { },
}
itemBases["猴掌魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "击败敌人有 10% 的几率获得暴击球",
	implicitModTypes = { { "power_charge" }, },
	req = { },
}
itemBases["猴掌魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "击败敌人有 10% 的几率获得狂怒球",
	implicitModTypes = { { "frenzy_charge" }, },
	req = { },
}
itemBases["猴掌魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "击败敌人有 10% 的几率时获得耐力球",
	implicitModTypes = { { "endurance_charge" }, },
	req = { },
}
itemBases["三手魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "获得等同 (6-12)% 物理伤害的 1 个随机元素伤害",
	implicitModTypes = { { "physical_damage", "elemental_damage", "damage", "physical", "elemental" }, },
	req = { },
}
itemBases["狼王魔符"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { amulet = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["Avian Twins Talisman (Fire-To-Cold)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中火焰伤害的 50% 转为冰霜伤害",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Fire-To-Lightning)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中火焰伤害的 50% 转为闪电伤害",
	implicitModTypes = { { "elemental", "fire", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Cold-To-Lightning)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中冰霜伤害的 50% 转为火焰伤害",
	implicitModTypes = { { "elemental", "fire", "cold" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Cold-To-Fire)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中冰霜伤害的 50% 转为闪电伤害",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["Avian Twins Talisman (Lightning-To-Cold)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "受到击中闪电伤害的 50% 转为冰霜伤害",
	implicitModTypes = { { "elemental", "cold", "lightning" }, },
	req = { },
}
itemBases["Monkey Paw Talisman (Power)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "击败敌人有 10% 的几率获得暴击球",
	implicitModTypes = { { "power_charge" }, },
	req = { },
}
itemBases["Monkey Paw Talisman (Frenzy)"] = {
	type = "Amulet",
	subType = "Talisman",
	tags = { default = true, talisman = true, amulet = true, },
	implicit = "击败敌人有 10% 的几率获得狂怒球",
	implicitModTypes = { { "frenzy_charge" }, },
	req = { },
}
