-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["素布腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "全局物理伤害提高 (12-24)%",
	implicitModTypes = { { "physical_damage", "damage", "physical" }, },
	req = { },
}
itemBases["扣链腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "+(9-20) 最大能量护盾",
	implicitModTypes = { { "energy_shield", "defences" }, },
	req = { },
}
itemBases["皮革腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "+(25-40) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	req = { level = 8, },
}
itemBases["重革腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "+(25-35) 力量",
	implicitModTypes = { { "attribute" }, },
	req = { level = 8, },
}
itemBases["饰布腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "晕眩回复和格挡回复提高 (15-25)%",
	implicitModTypes = { {  }, },
	req = { level = 16, },
}
itemBases["扣钉腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "敌人被晕眩时间延长 (20-30)%",
	implicitModTypes = { {  }, },
	req = { level = 16, },
}
itemBases["低酿腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "你身上的药剂效果提高 20%\n不能使用第五栏的药剂",
	implicitModTypes = { {  }, {  }, },
	req = { level = 24, },
}
itemBases["警戒腰带"] = {
	type = "Belt",
	tags = { belt = true, default = true, },
	implicit = "你使用药剂时触发 20 级召唤嘲讽装置",
	implicitModTypes = { {  }, },
	req = { level = 56, },
}
itemBases["先锋腰带"] = {
	type = "Belt",
	tags = { not_for_sale = true, atlas_base_type = true, beltatlas1 = true, belt = true, default = true, },
	implicit = "+(260-320) 护甲和闪避值",
	implicitModTypes = { { "armour", "evasion", "defences" }, },
	req = { level = 78, },
}
itemBases["水晶腰带"] = {
	type = "Belt",
	tags = { beltatlas2 = true, not_for_sale = true, atlas_base_type = true, belt = true, default = true, },
	implicit = "+(60-80) 最大能量护盾",
	implicitModTypes = { { "energy_shield", "defences" }, },
	req = { level = 79, },
}
itemBases["深渊腰带"] = {
	type = "Belt",
	tags = { not_for_sale = true, default = true, belt = true, },
	implicit = "拥有 1 个深渊插槽",
	implicitModTypes = { {  }, },
	req = { },
}

itemBases["金羽腰带"] = {
	type = "Belt",
	tags = { demigods = true, not_for_sale = true, default = true, belt = true, },
	implicit = "物品稀有度提高 (20-30)%",
	implicitModTypes = { {  }, },
	req = { },
}
