-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["铁锻胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 6, },
	req = { str = 8, },
}
itemBases["冷钢胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 32, },
	req = { level = 9, str = 21, },
}
itemBases["坚铁胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 77, },
	req = { level = 23, str = 44, },
}
itemBases["强化胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 109, },
	req = { level = 33, str = 61, },
}
itemBases["古钢胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 122, },
	req = { level = 37, str = 67, },
}
itemBases["远古胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 151, },
	req = { level = 46, str = 82, },
}
itemBases["巨灵胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 177, },
	req = { level = 54, str = 95, },
}
itemBases["瓦尔胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 220, },
	req = { level = 62, str = 117, },
}
itemBases["巨人胫甲"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, armour = true, str_armour = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 241, },
	req = { level = 68, str = 120, },
}
itemBases["劣金之履"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, str_armour = true, not_for_sale = true, armour = true, default = true, },
	implicit = "+(4-5)% 攻击伤害格挡几率\n被格挡的攻击对你造成 20% 伤害",
	implicitModTypes = { { "block" }, { "block" }, },
	armour = { ArmourBase = 68, },
	req = { level = 20, str = 39, },
}
itemBases["乌钢之履"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, str_armour = true, not_for_sale = true, armour = true, default = true, },
	implicit = "+(4-5)% 攻击伤害格挡几率\n被格挡的攻击对你造成 20% 伤害",
	implicitModTypes = { { "block" }, { "block" }, },
	armour = { ArmourBase = 164, },
	req = { level = 50, str = 89, },
}
itemBases["踏烟之履"] = {
	type = "Boots",
	subType = "Armour",
	socketLimit = 4,
	tags = { boots = true, str_armour = true, not_for_sale = true, armour = true, default = true, },
	implicit = "+(4-5)% 攻击伤害格挡几率\n被格挡的攻击对你造成 20% 伤害",
	implicitModTypes = { { "block" }, { "block" }, },
	armour = { ArmourBase = 236, },
	req = { level = 80, str = 124, },
}

itemBases["生皮短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 13, },
	req = { dex = 11, },
}
itemBases["羊皮短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 42, },
	req = { level = 12, dex = 26, },
}
itemBases["鹿皮短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 74, },
	req = { level = 22, dex = 42, },
}
itemBases["砂影短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 113, },
	req = { level = 34, dex = 62, },
}
itemBases["鳗皮短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 129, },
	req = { level = 39, dex = 70, },
}
itemBases["鲨皮短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 145, },
	req = { level = 44, dex = 79, },
}
itemBases["粗革短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 180, },
	req = { level = 55, dex = 97, },
}
itemBases["匿踪短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 220, },
	req = { level = 62, dex = 117, },
}
itemBases["迷踪短靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 246, },
	req = { level = 69, dex = 120, },
}
itemBases["唤云之靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { boots = true, dex_armour = true, armour = true, not_for_sale = true, default = true, },
	implicit = "每 200 点命中值都附加 1 到 (5-6) 点攻击闪电伤害\n总命中值总降 25%",
	implicitModTypes = { { "attack" }, { "attack" }, },
	armour = { EvasionBase = 68, },
	req = { level = 20, dex = 39, },
}
itemBases["破风之靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { boots = true, dex_armour = true, armour = true, not_for_sale = true, default = true, },
	implicit = "每 200 点命中值都附加 1 到 (5-6) 点攻击闪电伤害\n总命中值总降 25%",
	implicitModTypes = { { "attack" }, { "attack" }, },
	armour = { EvasionBase = 164, },
	req = { level = 50, dex = 89, },
}
itemBases["御风之靴"] = {
	type = "Boots",
	subType = "Evasion",
	socketLimit = 4,
	tags = { boots = true, dex_armour = true, armour = true, not_for_sale = true, default = true, },
	implicit = "每 200 点命中值都附加 1 到 (5-6) 点攻击闪电伤害\n总命中值总降 25%",
	implicitModTypes = { { "attack" }, { "attack" }, },
	armour = { EvasionBase = 236, },
	req = { level = 80, dex = 124, },
}

itemBases["羊毛之鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 4, },
	req = { int = 11, },
}
itemBases["丝绒便鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 8, },
	req = { level = 9, int = 21, },
}
itemBases["丝绸便鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 15, },
	req = { level = 22, int = 42, },
}
itemBases["学者长靴"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 21, },
	req = { level = 32, int = 59, },
}
itemBases["缎布便鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 25, },
	req = { level = 38, int = 69, },
}
itemBases["绣布便鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 29, },
	req = { level = 44, int = 79, },
}
itemBases["咒者长靴"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 34, },
	req = { level = 53, int = 94, },
}
itemBases["秘术便鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 45, },
	req = { level = 61, int = 119, },
}
itemBases["术士长靴"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EnergyShieldBase = 49, },
	req = { level = 67, int = 123, },
}
itemBases["踏暮之鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { boots = true, int_armour = true, armour = true, not_for_sale = true, default = true, },
	implicit = "移动速度降低 10%\n位移技能的的冷却恢复速度提高 (30-40)%",
	implicitModTypes = { { "speed" }, { "speed" }, },
	armour = { EnergyShieldBase = 14, },
	req = { level = 20, int = 39, },
}
itemBases["夜风之鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { boots = true, int_armour = true, armour = true, not_for_sale = true, default = true, },
	implicit = "移动速度降低 10%\n位移技能的的冷却恢复速度提高 (30-40)%",
	implicitModTypes = { { "speed" }, { "speed" }, },
	armour = { EnergyShieldBase = 32, },
	req = { level = 50, int = 89, },
}
itemBases["探梦之鞋"] = {
	type = "Boots",
	subType = "Energy Shield",
	socketLimit = 4,
	tags = { boots = true, int_armour = true, armour = true, not_for_sale = true, default = true, },
	implicit = "移动速度降低 10%\n位移技能的的冷却恢复速度提高 (30-40)%",
	implicitModTypes = { { "speed" }, { "speed" }, },
	armour = { EnergyShieldBase = 47, },
	req = { level = 80, int = 124, },
}

itemBases["粗鳞皮靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 12, EvasionBase = 12, },
	req = { level = 6, str = 9, dex = 9, },
}
itemBases["铁影长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 34, EvasionBase = 34, },
	req = { level = 18, str = 19, dex = 19, },
}
itemBases["铜影长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 55, EvasionBase = 55, },
	req = { level = 30, str = 30, dex = 30, },
}
itemBases["钢影长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 65, EvasionBase = 65, },
	req = { level = 36, str = 35, dex = 35, },
}
itemBases["蛇鳞长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 76, EvasionBase = 76, },
	req = { level = 42, str = 40, dex = 40, },
}
itemBases["地蝮鳞长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 92, EvasionBase = 92, },
	req = { level = 51, str = 48, dex = 48, },
}
itemBases["火蝮鳞长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 106, EvasionBase = 106, },
	req = { level = 59, str = 56, dex = 56, },
}
itemBases["龙鳞长靴"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { str_dex_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 121, EvasionBase = 121, },
	req = { level = 65, str = 62, dex = 62, },
}
itemBases["Two-Toned Boots (Armour/Evasion)"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { boots = true, str_dex_armour = true, not_for_sale = true, atlas_base_type = true, armour = true, bootsatlas2 = true, default = true, },
	implicit = "+(8-12)% 火焰与冰霜抗性",
	implicitModTypes = { { "elemental", "fire", "cold", "resistance" }, },
	armour = { ArmourBase = 126, EvasionBase = 126, },
	req = { level = 70, str = 62, dex = 62, },
}

itemBases["链甲长靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 11, EnergyShieldBase = 3, },
	req = { level = 5, str = 8, int = 8, },
}
itemBases["环甲筒靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 25, EnergyShieldBase = 5, },
	req = { level = 13, str = 15, int = 15, },
}
itemBases["网眼长靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 51, EnergyShieldBase = 10, },
	req = { level = 28, str = 28, int = 28, },
}
itemBases["仪式短靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 65, EnergyShieldBase = 13, },
	req = { level = 36, str = 35, int = 35, },
}
itemBases["狂热者长靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 73, EnergyShieldBase = 14, },
	req = { level = 40, str = 39, int = 39, },
}
itemBases["战士之靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 88, EnergyShieldBase = 17, },
	req = { level = 49, str = 47, int = 47, },
}
itemBases["军团长靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 104, EnergyShieldBase = 20, },
	req = { level = 58, str = 54, int = 54, },
}
itemBases["圣战长靴"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { str_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { ArmourBase = 121, EnergyShieldBase = 24, },
	req = { level = 64, str = 62, int = 62, },
}
itemBases["Two-Toned Boots (Armour/Energy Shield)"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { bootsatlas3 = true, boots = true, not_for_sale = true, atlas_base_type = true, armour = true, str_int_armour = true, default = true, },
	implicit = "+(8-12)% 火焰与闪电抗性",
	implicitModTypes = { { "elemental", "fire", "lightning", "resistance" }, },
	armour = { ArmourBase = 126, EnergyShieldBase = 24, },
	req = { level = 70, str = 62, int = 62, },
}

itemBases["裹趾凉鞋"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 12, EnergyShieldBase = 3, },
	req = { level = 6, dex = 9, int = 9, },
}
itemBases["扣环短靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 30, EnergyShieldBase = 6, },
	req = { level = 16, dex = 18, int = 18, },
}
itemBases["环带长靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 50, EnergyShieldBase = 10, },
	req = { level = 27, dex = 27, int = 27, },
}
itemBases["缚足长靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 62, EnergyShieldBase = 12, },
	req = { level = 34, dex = 34, int = 34, },
}
itemBases["猎人之靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 74, EnergyShieldBase = 15, },
	req = { level = 41, dex = 40, int = 40, },
}
itemBases["伏击之靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 85, EnergyShieldBase = 17, },
	req = { level = 47, dex = 45, int = 45, },
}
itemBases["禁礼之靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 99, EnergyShieldBase = 19, },
	req = { level = 55, dex = 52, int = 52, },
}
itemBases["暗影之靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 121, EnergyShieldBase = 24, },
	req = { level = 63, dex = 62, int = 62, },
}
itemBases["暗影者长靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { dex_int_armour = true, armour = true, boots = true, default = true, },
	implicitModTypes = { },
	armour = { EvasionBase = 185, EnergyShieldBase = 17, },
	req = { level = 69, dex = 82, int = 42, },
}
itemBases["逃亡之靴"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { boots = true, bootsatlasdexint = true, not_for_sale = true, atlas_base_type = true, armour = true, dex_int_armour = true, default = true, },
	implicit = "+(13-17)% 混沌抗性",
	implicitModTypes = { { "chaos", "resistance" }, },
	armour = { EvasionBase = 112, EnergyShieldBase = 31, },
	req = { level = 70, dex = 56, int = 76, },
}
itemBases["Two-Toned Boots (Evasion/Energy Shield)"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { boots = true, dex_int_armour = true, not_for_sale = true, atlas_base_type = true, armour = true, bootsatlas1 = true, default = true, },
	implicit = "+(8-12)% 冰霜与闪电抗性",
	implicitModTypes = { { "elemental", "cold", "lightning", "resistance" }, },
	armour = { EvasionBase = 126, EnergyShieldBase = 24, },
	req = { level = 70, dex = 62, int = 62, },
}


itemBases["异色鞋 (冰闪)"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { default = true, armour = true, boots = true, not_for_sale = true, atlas_base_type = true, bootsatlas1 = true, dex_int_armour = true, },
	implicitModTypes = { { "elemental", "cold", "lightning", "resistance" }, },
	implicit = "+(8-12)% 冰霜与闪电抗性",
	armour = { EvasionBase = 126, EnergyShieldBase = 24, },
	req = { level = 70, dex = 62, int = 62, },
}
itemBases["异色鞋 (火闪)"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { default = true, armour = true, boots = true, not_for_sale = true, atlas_base_type = true, bootsatlas3 = true, str_int_armour = true, },
	implicitModTypes = { { "elemental", "fire", "lightning", "resistance" }, },
	implicit = "+(8-12)% 火焰与闪电抗性",
	armour = { ArmourBase = 126, EnergyShieldBase = 24, },
	req = { level = 70, str = 62, int = 62, },
}
itemBases["异色鞋 (火冰)"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { default = true, armour = true, boots = true, not_for_sale = true, atlas_base_type = true, bootsatlas2 = true, str_dex_armour = true, },
	implicitModTypes = { { "elemental", "fire", "cold", "resistance" }, },
	implicit = "+(8-12)% 火焰与冰霜抗性",
	armour = { ArmourBase = 126, EvasionBase = 126, },
	req = { level = 70, str = 62, dex = 62, },
}


itemBases["异色鞋(冰闪)"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	socketLimit = 4,
	tags = { default = true, armour = true, boots = true, not_for_sale = true, atlas_base_type = true, bootsatlas1 = true, dex_int_armour = true, },
	implicitModTypes = { { "elemental", "cold", "lightning", "resistance" }, },
	implicit = "+(8-12)% 冰霜与闪电抗性",
	armour = { EvasionBase = 126, EnergyShieldBase = 24, },
	req = { level = 70, dex = 62, int = 62, },
}
itemBases["异色鞋(火闪)"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	socketLimit = 4,
	tags = { default = true, armour = true, boots = true, not_for_sale = true, atlas_base_type = true, bootsatlas3 = true, str_int_armour = true, },
	implicitModTypes = { { "elemental", "fire", "lightning", "resistance" }, },
	implicit = "+(8-12)% 火焰与闪电抗性",
	armour = { ArmourBase = 126, EnergyShieldBase = 24, },
	req = { level = 70, str = 62, int = 62, },
}
itemBases["异色鞋(火冰)"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	socketLimit = 4,
	tags = { default = true, armour = true, boots = true, not_for_sale = true, atlas_base_type = true, bootsatlas2 = true, str_dex_armour = true, },
	implicitModTypes = { { "elemental", "fire", "cold", "resistance" }, },
	implicit = "+(8-12)% 火焰与冰霜抗性",
	armour = { ArmourBase = 126, EvasionBase = 126, },
	req = { level = 70, str = 62, dex = 62, },
}

itemBases["符文胫甲"] = {
	type = "Boots",
	subType = "Ward",
	socketLimit = 4,
	tags = { boots = true, not_for_sale = true, armour = true, ward_armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 20, },
	req = { level = 24, str = 20, dex = 20, int = 20, },
}
itemBases["符文护腿"] = {
	type = "Boots",
	subType = "Ward",
	socketLimit = 4,
	tags = { boots = true, not_for_sale = true, armour = true, ward_armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 52, },
	req = { level = 48, str = 37, dex = 37, int = 37, },
}
itemBases["符文战靴"] = {
	type = "Boots",
	subType = "Ward",
	socketLimit = 4,
	tags = { boots = true, not_for_sale = true, armour = true, ward_armour = true, default = true, },
	implicitModTypes = { },
	armour = { WardBase = 85, },
	req = { level = 69, str = 46, dex = 46, int = 46, },
}

itemBases["黄金缠鞋"] = {
	type = "Boots",
	socketLimit = 4,
	tags = { boots = true, not_for_sale = true, armour = true, demigods = true, default = true, },
	implicit = "+(8-16)% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { },
	req = { level = 12, },
}
