-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["玻璃利片"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 6, PhysicalMax = 10, CritChanceBase = 6, AttackRateBase = 1.5, Range = 10, },
	req = { dex = 9, int = 6, },
}
itemBases["剥皮刀"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 4, PhysicalMax = 17, CritChanceBase = 6, AttackRateBase = 1.45, Range = 10, },
	req = { level = 5, dex = 16, int = 11, },
}
itemBases["锐利刺匕"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 7, PhysicalMax = 27, CritChanceBase = 6.1, AttackRateBase = 1.5, Range = 10, },
	req = { level = 15, dex = 30, int = 30, },
}
itemBases["尖耙短匕"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { maraketh = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "4% 攻击伤害格挡率",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 14, PhysicalMax = 54, CritChanceBase = 6.2, AttackRateBase = 1.35, Range = 10, },
	req = { level = 36, dex = 55, int = 77, },
}
itemBases["残体利刃"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 45, CritChanceBase = 6, AttackRateBase = 1.4, Range = 10, },
	req = { level = 30, dex = 64, int = 44, },
}
itemBases["夺命刺"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 52, CritChanceBase = 6.1, AttackRateBase = 1.5, Range = 10, },
	req = { level = 41, dex = 72, int = 72, },
}
itemBases["三叉短匕"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { maraketh = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "4% 攻击伤害格挡率",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 74, CritChanceBase = 6.5, AttackRateBase = 1.35, Range = 10, },
	req = { level = 51, dex = 83, int = 99, },
}
itemBases["重伤短刀"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 76, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 10, },
	req = { level = 56, dex = 113, int = 78, },
}
itemBases["伏击刺刃"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { onehand = true, one_hand_weapon = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 74, CritChanceBase = 6.1, AttackRateBase = 1.5, Range = 10, },
	req = { level = 60, dex = 113, int = 113, },
}
itemBases["战叉"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { maraketh = true, one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "6% 攻击伤害格挡率",
	implicitModTypes = { { "block" }, },
	weapon = { PhysicalMin = 22, PhysicalMax = 88, CritChanceBase = 6.2, AttackRateBase = 1.35, Range = 10, },
	req = { level = 70, dex = 121, int = 121, },
}
itemBases["折叠匕首"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "用该武器击中时，所有伤害都导致中毒",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 46, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 30, dex = 54, int = 54, },
}
itemBases["冲压匕首"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "用该武器击中时，所有伤害都导致中毒",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 71, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 50, dex = 86, int = 86, },
}
itemBases["气动匕首"] = {
	type = "Dagger",
	socketLimit = 3,
	tags = { one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicit = "用该武器击中时，所有伤害都导致中毒",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 79, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 70, dex = 121, int = 121, },
}
itemBases["虚空飞刃"] = {
	type = "Dagger",
	hidden = true,
	socketLimit = 3,
	tags = { one_hand_weapon = true, onehand = true, not_for_sale = true, dagger = true, weapon = true, attack_dagger = true, default = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 4, PhysicalMax = 8, CritChanceBase = 6, AttackRateBase = 1.5, Range = 10, },
	req = { dex = 9, int = 6, },
}

itemBases["刻骨刀"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 3, PhysicalMax = 26, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 10, dex = 18, int = 26, },
}
itemBases["窃者短刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 8, PhysicalMax = 34, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 20, dex = 31, int = 45, },
}
itemBases["铜锻波刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 50%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 41, CritChanceBase = 6.5, AttackRateBase = 1.3, Range = 10, },
	req = { level = 24, dex = 28, int = 60, },
}
itemBases["双刃匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 43, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 28, dex = 42, int = 60, },
}
itemBases["魔性之刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 40%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 59, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 32, dex = 36, int = 78, },
}
itemBases["屠兽利刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 7, PhysicalMax = 62, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 38, dex = 55, int = 79, },
}
itemBases["窃者短匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 59, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 44, dex = 63, int = 90, },
}
itemBases["金光波刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 50%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 75, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 47, dex = 51, int = 110, },
}
itemBases["皇家短匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 64, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 50, dex = 71, int = 102, },
}
itemBases["兽血短匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 40%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 22, PhysicalMax = 87, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 53, dex = 58, int = 123, },
}
itemBases["猎者之刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 10, PhysicalMax = 86, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 58, dex = 81, int = 117, },
}
itemBases["艾兹麦之匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 79, CritChanceBase = 6.3, AttackRateBase = 1.4, Range = 10, },
	req = { level = 62, dex = 95, int = 131, },
}
itemBases["白金波刃"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 50%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 95, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 64, dex = 76, int = 149, },
}
itemBases["帝国短匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 30%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 73, CritChanceBase = 6.3, AttackRateBase = 1.5, Range = 10, },
	req = { level = 66, dex = 95, int = 131, },
}
itemBases["魔灵短匕"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, rune_dagger = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "攻击和法术暴击率提高 40%",
	implicitModTypes = { { "critical" }, },
	weapon = { PhysicalMin = 24, PhysicalMax = 97, CritChanceBase = 6.5, AttackRateBase = 1.2, Range = 10, },
	req = { level = 68, dex = 76, int = 149, },
}
itemBases["火焰刀"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { rune_dagger = true, onehand = true, not_for_sale = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "你使用插入的技能时触发 10 级烈焰冲刺",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 47, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 30, dex = 54, int = 54, },
}
itemBases["闪火刀"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { rune_dagger = true, onehand = true, not_for_sale = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "你使用插入的技能时触发 20 级烈焰冲刺",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 73, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 50, dex = 86, int = 86, },
}
itemBases["炼狱刀"] = {
	type = "Dagger",
	subType = "Rune",
	socketLimit = 3,
	tags = { rune_dagger = true, onehand = true, not_for_sale = true, one_hand_weapon = true, weapon = true, dagger = true, default = true, },
	implicit = "你使用插入的技能时触发 30 级烈焰冲刺",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 85, CritChanceBase = 6.3, AttackRateBase = 1.45, Range = 10, },
	req = { level = 70, dex = 121, int = 121, },
}
