-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["赤红珠宝"] = {
	type = "Jewel",
	tags = { strjewel = true, not_dex = true, not_for_sale = true, not_int = true, jewel = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["翠绿珠宝"] = {
	type = "Jewel",
	tags = { dexjewel = true, not_for_sale = true, jewel = true, not_int = true, not_str = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["钴蓝珠宝"] = {
	type = "Jewel",
	tags = { not_dex = true, not_for_sale = true, intjewel = true, not_str = true, jewel = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["三相珠宝"] = {
	type = "Jewel",
	tags = { dexjewel = true, not_for_sale = true, strjewel = true, jewel = true, default = true, intjewel = true, },
	implicitModTypes = { },
	req = { },
}

itemBases["苍白之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { abyss_jewel = true, default = true, abyss_jewel_summoner = true, not_for_sale = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["安睡之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { abyss_jewel = true, abyss_jewel_caster = true, default = true, not_for_sale = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["凶残之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { abyss_jewel = true, abyss_jewel_melee = true, default = true, not_for_sale = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["锐利之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { abyss_jewel = true, abyss_jewel_ranged = true, default = true, not_for_sale = true, },
	implicitModTypes = { },
	req = { },
}

itemBases["大型星团珠宝"] = {
	type = "Jewel",
	subType = "Cluster",
	tags = { not_for_sale = true, jewel = true, expansion_jewel_large = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["中型星团珠宝"] = {
	type = "Jewel",
	subType = "Cluster",
	tags = { expansion_jewel_medium = true, jewel = true, not_for_sale = true, default = true, },
	implicitModTypes = { },
	req = { },
}
itemBases["小型星团珠宝"] = {
	type = "Jewel",
	subType = "Cluster",
	tags = { not_for_sale = true, jewel = true, expansion_jewel_small = true, default = true, },
	implicitModTypes = { },
	req = { },
}

itemBases["永恒珠宝"] = {
	type = "Jewel",
	subType = "Timeless",
	tags = { dexjewel = true, not_for_sale = true, strjewel = true, jewel = true, default = true, intjewel = true, },
	implicitModTypes = { },
	req = { },
}
