-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["锻铁戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "攻击附加 1 - 4 基础物理伤害",
	implicitModTypes = { { "physical_damage", "damage", "physical", "attack" }, },
	req = { },
}
itemBases["珊瑚戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	req = { },
}
itemBases["海灵戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(20-30) 最大魔力",
	implicitModTypes = { { "resource", "mana" }, },
	req = { },
}
itemBases["金光戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "物品稀有度提高 (6-15)%",
	implicitModTypes = { {  }, },
	req = { level = 20, },
}
itemBases["黄玉戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(20-30)% 闪电抗性",
	implicitModTypes = { { "elemental", "lightning", "resistance" }, },
	req = { level = 12, },
}
itemBases["蓝玉戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(20-30)% 冰霜抗性",
	implicitModTypes = { { "elemental", "cold", "resistance" }, },
	req = { level = 8, },
}
itemBases["红玉戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(20-30)% 火焰抗性",
	implicitModTypes = { { "elemental", "fire", "resistance" }, },
	req = { level = 16, },
}
itemBases["三相戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(8-10)% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	req = { level = 30, },
}
itemBases["月光石戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(15-25) 最大能量护盾",
	implicitModTypes = { { "energy_shield", "defences" }, },
	req = { level = 20, },
}
itemBases["紫晶戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "+(17-23)% 混沌抗性",
	implicitModTypes = { { "chaos", "resistance" }, },
	req = { level = 30, },
}
itemBases["宝钻戒指"] = {
	type = "Ring",
	tags = { ring = true, default = true, },
	implicit = "攻击和法术暴击率提高 (20-30)%",
	implicitModTypes = { { "critical" }, },
	req = { level = 20, },
}
itemBases["双玉戒指"] = {
	type = "Ring",
	tags = { ring = true, twostonering = true, default = true, },
	implicit = "+(12-16)% 火焰与闪电抗性",
	implicitModTypes = { { "elemental", "fire", "lightning", "resistance" }, },
	req = { level = 20, },
}
itemBases["潜能之戒"] = {
	type = "Ring",
	tags = { ring = true, unset_ring = true, default = true, },
	implicit = "有 1 个插槽",
	implicitModTypes = { {  }, },
	req = { level = 5, },
}
itemBases["骨环"] = {
	type = "Ring",
	tags = { ring = true, ring_can_roll_minion_modifiers = true, default = true, },
	implicit = "召唤生物获得 +(10-15)% 元素抗性",
	implicitModTypes = { { "elemental", "resistance", "minion" }, },
	req = { level = 25, },
}
itemBases["合金戒指"] = {
	type = "Ring",
	tags = { not_for_sale = true, ring = true, ringatlas1 = true, atlas_base_type = true, default = true, },
	implicit = "攻击附加 (3-4) - (10-14) 基础物理伤害",
	implicitModTypes = { { "physical_damage", "damage", "physical", "attack" }, },
	req = { level = 80, },
}
itemBases["蛋白石戒指"] = {
	type = "Ring",
	tags = { not_for_sale = true, ring = true, ringatlas2 = true, atlas_base_type = true, default = true, },
	implicit = "元素伤害提高 (15-25)%",
	implicitModTypes = { { "elemental_damage", "damage", "elemental" }, },
	req = { level = 80, },
}
itemBases["朱砂之戒"] = {
	type = "Ring",
	tags = { ringatlas3 = true, not_for_sale = true, ring = true, atlas_base_type = true, default = true, },
	implicit = "生命上限提高 (5-7)%",
	implicitModTypes = { { "resource", "life" }, },
	req = { level = 80, },
}
itemBases["天蓝之戒"] = {
	type = "Ring",
	tags = { not_for_sale = true, ring = true, atlas_base_type = true, ringatlas4 = true, default = true, },
	implicit = "魔力上限提高 (8-10)%",
	implicitModTypes = { { "resource", "mana" }, },
	req = { level = 80, },
}
itemBases["青石戒指"] = {
	type = "Ring",
	tags = { not_for_sale = true, ring = true, ringatlas5 = true, atlas_base_type = true, default = true, },
	implicit = "混沌伤害提高 (17-23)%",
	implicitModTypes = { { "chaos_damage", "damage", "chaos" }, },
	req = { level = 80, },
}
itemBases["双玉戒指(火闪)"] = {
	type = "Ring",
	tags = { ring = true, twostonering = true, default = true, },
	implicit = "+(12-16)% 火焰与闪电抗性",
	implicitModTypes = { { "elemental", "fire", "lightning", "resistance" }, },
	req = { level = 20, },
}
itemBases["双玉戒指(冰闪)"] = {
	type = "Ring",
	tags = { ring = true, twostonering = true, default = true, },
	implicit = "+(12-16)% 冰霜与闪电抗性",
	implicitModTypes = { { "elemental", "cold", "lightning", "resistance" }, },
	req = { level = 20, },
}
itemBases["双玉戒指(火冰)"] = {
	type = "Ring",
	tags = { ring = true, twostonering = true, default = true, },
	implicit = "+(12-16)% 火焰与冰霜抗性",
	implicitModTypes = { { "elemental", "fire", "cold", "resistance" }, },
	req = { level = 20, },
}
itemBases["齿轮戒指"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "允许的前缀 -1\n允许的后缀 +1\n基底词缀不能改变",
	implicitModTypes = { {  }, {  }, {  }, },
	req = { level = 24, },
}
itemBases["地线戒指"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "允许的前缀 +1\n允许的后缀 -1\n基底词缀不能改变",
	implicitModTypes = { {  }, {  }, {  }, },
	req = { level = 24, },
}
itemBases["Dusk Ring"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：技能效果的持续时间减少15%\n右边的戒指栏位：技能效果持续时间增加15%",
	implicitModTypes = { {  }, {  }, },
	req = { level = 24, },
}
itemBases["Penumbra Ring"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：你受到的诅咒效果减弱30%\n右边的戒指栏位：你受到的诅咒效果增强30%",
	implicitModTypes = { { "curse" }, { "curse" }, },
	req = { level = 24, },
}
itemBases["Gloam Ring"] = {
	type = "Ring",
	tags = { ring = true, ring_can_roll_minion_modifiers = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：召唤生物受到的伤害降低15%\n右边的戒指栏位：召唤生物受到的伤害提高15%",
	implicitModTypes = { { "minion" }, { "minion" }, },
	req = { level = 24, },
}
itemBases["Tenebrous Ring"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：你处于异常状态的时间减少30%\n右边的戒指栏位：你处于异常状态的时间增加30%",
	implicitModTypes = { { "ailment" }, { "ailment" }, },
	req = { level = 24, },
}
itemBases["Shadowed Ring"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：受到的冰霜伤害的25%转化为火焰伤害\n右边的戒指栏位：受到的火焰伤害的25%转化为冰霜伤害",
	implicitModTypes = { { "elemental", "fire", "cold" }, { "elemental", "fire", "cold" }, },
	req = { level = 24, },
}
itemBases["Shadowed Ring"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：受到的火焰伤害的25%转化为闪电伤害\n右边的戒指栏位：受到的闪电伤害的25%转化为火焰伤害",
	implicitModTypes = { { "elemental", "fire", "lightning" }, { "elemental", "fire", "lightning" }, },
	req = { level = 24, },
}
itemBases["Shadowed Ring"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "左边的戒指栏位：受到的闪电伤害的25%转化为冰霜伤害\n右边的戒指栏位：受到的冰霜伤害的25%转化为闪电伤害",
	implicitModTypes = { { "elemental", "cold", "lightning" }, { "elemental", "cold", "lightning" }, },
	req = { level = 24, },
}
itemBases["戒指"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicitModTypes = { },
	req = { },
}

itemBases["裂隙戒指"] = {
	type = "Ring",
	tags = { ring = true, not_for_sale = true, default = true, },
	implicit = "属性在裂隙内得到加倍",
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["金环"] = {
	type = "Ring",
	tags = { ring = true, demigods = true, not_for_sale = true, default = true, },
	implicit = "+(8-12) 全属性",
	implicitModTypes = { { "attribute" }, },
	req = { level = 12, },
}
itemBases["杰特戒指"] = {
	type = "Ring",
	hidden = true,
	tags = { ring = true, demigods = true, not_for_sale = true, default = true, },
	implicit = "全局防御提高 (5-10)%",
	implicitModTypes = { { "defences" }, },
	req = { },
}
