-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["朽木塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 24, ArmourBaseMin = 9, ArmourBaseMax = 12, MovementPenalty = 3, },
	req = { str = 11, },
}
itemBases["斑驳塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 23, ArmourBaseMin = 36, ArmourBaseMax = 47, MovementPenalty = 3, },
	req = { level = 5, str = 20, },
}
itemBases["生皮塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 26, ArmourBaseMin = 53, ArmourBaseMax = 66, MovementPenalty = 3, },
	req = { level = 11, str = 33, },
}
itemBases["松木塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 94, ArmourBaseMax = 113, MovementPenalty = 3, },
	req = { level = 17, str = 47, },
}
itemBases["铜锻塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(30-40) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 151, ArmourBaseMax = 173, MovementPenalty = 3, },
	req = { level = 24, str = 62, },
}
itemBases["强化塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 23, ArmourBaseMin = 237, ArmourBaseMax = 260, MovementPenalty = 3, },
	req = { level = 30, str = 76, },
}
itemBases["彩绘塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 188, ArmourBaseMax = 216, MovementPenalty = 3, },
	req = { level = 35, str = 87, },
}
itemBases["鹿皮塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 26, ArmourBaseMin = 177, ArmourBaseMax = 209, MovementPenalty = 3, },
	req = { level = 39, str = 96, },
}
itemBases["桃木塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 230, ArmourBaseMax = 265, MovementPenalty = 3, },
	req = { level = 43, str = 105, },
}
itemBases["青铜塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(30-40) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 290, ArmourBaseMax = 324, MovementPenalty = 3, },
	req = { level = 47, str = 114, },
}
itemBases["征战塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 23, ArmourBaseMin = 397, ArmourBaseMax = 437, MovementPenalty = 3, },
	req = { level = 51, str = 123, },
}
itemBases["荣冠塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 293, ArmourBaseMax = 337, MovementPenalty = 3, },
	req = { level = 55, str = 132, },
}
itemBases["粗革塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 26, ArmourBaseMin = 261, ArmourBaseMax = 308, MovementPenalty = 3, },
	req = { level = 58, str = 139, },
}
itemBases["乌木塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 357, ArmourBaseMax = 411, MovementPenalty = 3, },
	req = { level = 61, str = 159, },
}
itemBases["艾兹麦塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(30-40) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 412, ArmourBaseMax = 474, MovementPenalty = 3, },
	req = { level = 64, str = 159, },
}
itemBases["巨型塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(10-20) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 23, ArmourBaseMin = 522, ArmourBaseMax = 601, MovementPenalty = 3, },
	req = { level = 67, str = 159, },
}
itemBases["坚毅塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "+(20-30) 最大生命",
	implicitModTypes = { { "resource", "life" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 467, ArmourBaseMax = 537, MovementPenalty = 3, },
	req = { level = 70, str = 159, },
}
itemBases["排热型塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, not_for_sale = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时灼烧敌人",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 23, ArmourBaseMin = 125, ArmourBaseMax = 143, MovementPenalty = 3, },
	req = { level = 30, str = 76, },
}
itemBases["熔岩塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, not_for_sale = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时灼烧敌人",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 23, ArmourBaseMin = 205, ArmourBaseMax = 236, MovementPenalty = 3, },
	req = { level = 50, str = 121, },
}
itemBases["适热型塔盾"] = {
	type = "Shield",
	subType = "Armour",
	socketLimit = 3,
	tags = { str_armour = true, not_for_sale = true, str_shield = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时灼烧敌人",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 23, ArmourBaseMin = 330, ArmourBaseMax = 379, MovementPenalty = 3, },
	req = { level = 70, str = 159, },
}

itemBases["羊皮轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 25, EvasionBaseMin = 14, EvasionBaseMax = 20, MovementPenalty = 3, },
	req = { dex = 13, },
}
itemBases["松木轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 26, EvasionBaseMin = 51, EvasionBaseMax = 66, MovementPenalty = 3, },
	req = { level = 8, dex = 26, },
}
itemBases["彩绘轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 6%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 24, EvasionBaseMin = 123, EvasionBaseMax = 154, MovementPenalty = 3, },
	req = { level = 16, dex = 44, },
}
itemBases["铆钉轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 27, EvasionBaseMin = 116, EvasionBaseMax = 139, MovementPenalty = 3, },
	req = { level = 23, dex = 60, },
}
itemBases["战争轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 9%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 26, EvasionBaseMin = 169, EvasionBaseMax = 194, MovementPenalty = 3, },
	req = { level = 29, dex = 74, },
}
itemBases["金面轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 6%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 25, EvasionBaseMin = 225, EvasionBaseMax = 259, MovementPenalty = 3, },
	req = { level = 34, dex = 85, },
}
itemBases["橡木轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 26, EvasionBaseMin = 220, EvasionBaseMax = 259, MovementPenalty = 3, },
	req = { level = 38, dex = 94, },
}
itemBases["釉彩轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 6%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 24, EvasionBaseMin = 311, EvasionBaseMax = 349, MovementPenalty = 3, },
	req = { level = 42, dex = 103, },
}
itemBases["波纹轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 27, EvasionBaseMin = 227, EvasionBaseMax = 272, MovementPenalty = 3, },
	req = { level = 46, dex = 112, },
}
itemBases["斗者轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 9%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 26, EvasionBaseMin = 287, EvasionBaseMax = 330, MovementPenalty = 3, },
	req = { level = 50, dex = 121, },
}
itemBases["金阳轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 6%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 25, EvasionBaseMin = 354, EvasionBaseMax = 407, MovementPenalty = 3, },
	req = { level = 54, dex = 130, },
}
itemBases["钢木轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 26, EvasionBaseMin = 327, EvasionBaseMax = 385, MovementPenalty = 3, },
	req = { level = 57, dex = 137, },
}
itemBases["漆彩轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 6%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 24, EvasionBaseMin = 477, EvasionBaseMax = 549, MovementPenalty = 3, },
	req = { level = 60, dex = 154, },
}
itemBases["瓦尔轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 3%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 27, EvasionBaseMin = 330, EvasionBaseMax = 379, MovementPenalty = 3, },
	req = { level = 63, dex = 159, },
}
itemBases["圣战轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 9%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 26, EvasionBaseMin = 385, EvasionBaseMax = 442, MovementPenalty = 3, },
	req = { level = 66, dex = 159, },
}
itemBases["帝国轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, armour = true, default = true, shield = true, },
	implicit = "移动速度提高 6%",
	implicitModTypes = { { "speed" }, },
	armour = { BlockChance = 25, EvasionBaseMin = 440, EvasionBaseMax = 506, MovementPenalty = 3, },
	req = { level = 69, dex = 159, },
}
itemBases["吸热型轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, not_for_sale = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时，给它们施加脆弱",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 22, EvasionBaseMin = 112, EvasionBaseMax = 129, MovementPenalty = 3, },
	req = { level = 30, dex = 76, },
}
itemBases["极地轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, not_for_sale = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时，给它们施加脆弱",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 22, EvasionBaseMin = 185, EvasionBaseMax = 212, MovementPenalty = 3, },
	req = { level = 50, dex = 121, },
}
itemBases["适寒型轻盾"] = {
	type = "Shield",
	subType = "Evasion",
	socketLimit = 3,
	tags = { dex_shield = true, dex_armour = true, not_for_sale = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时，给它们施加脆弱",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 22, EvasionBaseMin = 302, EvasionBaseMax = 348, MovementPenalty = 3, },
	req = { level = 70, dex = 159, },
}

itemBases["残枝魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (10-15)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 22, EnergyShieldBaseMin = 6, EnergyShieldBaseMax = 8, MovementPenalty = 3, },
	req = { int = 15, },
}
itemBases["紫衫魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (5-10)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 24, EnergyShieldBaseMin = 11, EnergyShieldBaseMax = 14, MovementPenalty = 3, },
	req = { level = 9, int = 29, },
}
itemBases["骨制魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (15-20)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 22, EnergyShieldBaseMin = 15, EnergyShieldBaseMax = 19, MovementPenalty = 3, },
	req = { level = 15, int = 42, },
}
itemBases["环形魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (5-10)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 24, EnergyShieldBaseMin = 21, EnergyShieldBaseMax = 25, MovementPenalty = 3, },
	req = { level = 23, int = 60, },
}
itemBases["灵相魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (10-15)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 23, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 29, MovementPenalty = 3, },
	req = { level = 28, int = 71, },
}
itemBases["铜锻魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 25, EnergyShieldBaseMin = 35, EnergyShieldBaseMax = 40, MovementPenalty = 3, },
	req = { level = 33, int = 83, },
}
itemBases["桃木魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (5-10)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 24, EnergyShieldBaseMin = 32, EnergyShieldBaseMax = 38, MovementPenalty = 3, },
	req = { level = 37, int = 92, },
}
itemBases["象牙魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (15-20)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 22, EnergyShieldBaseMin = 35, EnergyShieldBaseMax = 40, MovementPenalty = 3, },
	req = { level = 41, int = 101, },
}
itemBases["远古魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (5-10)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 24, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 45, MovementPenalty = 3, },
	req = { level = 45, int = 110, },
}
itemBases["魂相魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (10-15)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 23, EnergyShieldBaseMin = 42, EnergyShieldBaseMax = 48, MovementPenalty = 3, },
	req = { level = 49, int = 119, },
}
itemBases["暗金魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 25, EnergyShieldBaseMin = 54, EnergyShieldBaseMax = 62, MovementPenalty = 3, },
	req = { level = 53, int = 128, },
}
itemBases["软橡魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (5-10)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 24, EnergyShieldBaseMin = 47, EnergyShieldBaseMax = 55, MovementPenalty = 3, },
	req = { level = 56, int = 134, },
}
itemBases["石化魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (15-20)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 22, EnergyShieldBaseMin = 49, EnergyShieldBaseMax = 55, MovementPenalty = 3, },
	req = { level = 59, int = 141, },
}
itemBases["瓦尔魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (5-10)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 24, EnergyShieldBaseMin = 56, EnergyShieldBaseMax = 64, MovementPenalty = 3, },
	req = { level = 62, int = 159, },
}
itemBases["和谐魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicit = "法术伤害提高 (10-15)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	armour = { BlockChance = 23, EnergyShieldBaseMin = 58, EnergyShieldBaseMax = 66, MovementPenalty = 3, },
	req = { level = 65, int = 159, },
}
itemBases["巨人魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 25, EnergyShieldBaseMin = 67, EnergyShieldBaseMax = 77, MovementPenalty = 3, },
	req = { level = 68, int = 159, },
}
itemBases["力竭魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, not_for_sale = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时使它们精疲力尽",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 20, EnergyShieldBaseMin = 24, EnergyShieldBaseMax = 28, MovementPenalty = 3, },
	req = { level = 30, int = 76, },
}
itemBases["归纳魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, not_for_sale = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时使它们精疲力尽",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 20, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 44, MovementPenalty = 3, },
	req = { level = 50, int = 121, },
}
itemBases["适应型魔盾"] = {
	type = "Shield",
	subType = "Energy Shield",
	socketLimit = 3,
	tags = { focus = true, int_armour = true, not_for_sale = true, armour = true, default = true, shield = true, },
	implicit = "你格挡敌人的伤害时使它们精疲力尽",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 20, EnergyShieldBaseMin = 56, EnergyShieldBaseMax = 64, MovementPenalty = 3, },
	req = { level = 70, int = 159, },
}

itemBases["朽木圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 60%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 13, ArmourBaseMax = 18, EvasionBaseMin = 13, EvasionBaseMax = 18, MovementPenalty = 3, },
	req = { level = 5, str = 11, dex = 11, },
}
itemBases["杉木圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 180%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 29, ArmourBaseMax = 37, EvasionBaseMin = 29, EvasionBaseMax = 37, MovementPenalty = 3, },
	req = { level = 12, str = 19, dex = 19, },
}
itemBases["铆钉圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 60%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 27, ArmourBaseMin = 46, ArmourBaseMax = 58, EvasionBaseMin = 46, EvasionBaseMax = 58, MovementPenalty = 3, },
	req = { level = 20, str = 29, dex = 29, },
}
itemBases["炽红圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 26, ArmourBaseMin = 87, ArmourBaseMax = 100, EvasionBaseMin = 87, EvasionBaseMax = 100, MovementPenalty = 3, },
	req = { level = 27, str = 37, dex = 37, },
}
itemBases["光辉圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 120%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 75, ArmourBaseMax = 86, EvasionBaseMin = 75, EvasionBaseMax = 86, MovementPenalty = 3, },
	req = { level = 33, str = 44, dex = 44, },
}
itemBases["枫木圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 180%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 88, ArmourBaseMax = 99, EvasionBaseMin = 88, EvasionBaseMax = 99, MovementPenalty = 3, },
	req = { level = 39, str = 52, dex = 52, },
}
itemBases["尖刺圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 60%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 27, ArmourBaseMin = 102, ArmourBaseMax = 120, EvasionBaseMin = 102, EvasionBaseMax = 120, MovementPenalty = 3, },
	req = { level = 45, str = 59, dex = 59, },
}
itemBases["绯红圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 26, ArmourBaseMin = 155, ArmourBaseMax = 178, EvasionBaseMin = 155, EvasionBaseMax = 178, MovementPenalty = 3, },
	req = { level = 49, str = 64, dex = 64, },
}
itemBases["古代圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 120%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 122, ArmourBaseMax = 140, EvasionBaseMin = 122, EvasionBaseMax = 140, MovementPenalty = 3, },
	req = { level = 54, str = 70, dex = 70, },
}
itemBases["柚木圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 180%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 131, ArmourBaseMax = 146, EvasionBaseMin = 131, EvasionBaseMax = 146, MovementPenalty = 3, },
	req = { level = 58, str = 74, dex = 74, },
}
itemBases["棘刺圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 60%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 27, ArmourBaseMin = 154, ArmourBaseMax = 177, EvasionBaseMin = 154, EvasionBaseMax = 177, MovementPenalty = 3, },
	req = { level = 62, str = 85, dex = 85, },
}
itemBases["祭者圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 26, ArmourBaseMin = 209, ArmourBaseMax = 240, EvasionBaseMin = 209, EvasionBaseMax = 240, MovementPenalty = 3, },
	req = { level = 66, str = 85, dex = 85, },
}
itemBases["权贵圆盾"] = {
	type = "Shield",
	subType = "Armour/Evasion",
	socketLimit = 3,
	tags = { str_dex_armour = true, str_dex_shield = true, armour = true, default = true, shield = true, },
	implicit = "格挡回复提高 120%",
	implicitModTypes = { { "block" }, },
	armour = { BlockChance = 25, ArmourBaseMin = 148, ArmourBaseMax = 170, EvasionBaseMin = 148, EvasionBaseMax = 170, MovementPenalty = 3, },
	req = { level = 70, str = 85, dex = 85, },
}

itemBases["朽木鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+4% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 22, ArmourBaseMin = 18, ArmourBaseMax = 25, EnergyShieldBaseMin = 5, EnergyShieldBaseMax = 7, MovementPenalty = 3, },
	req = { level = 7, str = 13, int = 13, },
}
itemBases["椴木鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+4% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 43, ArmourBaseMax = 56, EnergyShieldBaseMin = 11, EnergyShieldBaseMax = 14, MovementPenalty = 3, },
	req = { level = 13, str = 20, int = 20, },
}
itemBases["强化鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 26, ArmourBaseMin = 65, ArmourBaseMax = 81, EnergyShieldBaseMin = 15, EnergyShieldBaseMax = 18, MovementPenalty = 3, },
	req = { level = 20, str = 29, int = 29, },
}
itemBases["层板鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+8% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 62, ArmourBaseMax = 73, EnergyShieldBaseMin = 13, EnergyShieldBaseMax = 16, MovementPenalty = 3, },
	req = { level = 27, str = 37, int = 37, },
}
itemBases["祭仪鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+12% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 22, ArmourBaseMin = 77, ArmourBaseMax = 89, EnergyShieldBaseMin = 16, EnergyShieldBaseMax = 19, MovementPenalty = 3, },
	req = { level = 34, str = 46, int = 46, },
}
itemBases["刻文鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+4% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 127, ArmourBaseMax = 142, EnergyShieldBaseMin = 27, EnergyShieldBaseMax = 30, MovementPenalty = 3, },
	req = { level = 40, str = 53, int = 53, },
}
itemBases["冷钢鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 26, ArmourBaseMin = 146, ArmourBaseMax = 167, EnergyShieldBaseMin = 30, EnergyShieldBaseMax = 35, MovementPenalty = 3, },
	req = { level = 46, str = 60, int = 60, },
}
itemBases["合板鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+8% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 113, ArmourBaseMax = 133, EnergyShieldBaseMin = 23, EnergyShieldBaseMax = 27, MovementPenalty = 3, },
	req = { level = 50, str = 65, int = 65, },
}
itemBases["天使鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+12% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 22, ArmourBaseMin = 124, ArmourBaseMax = 142, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 29, MovementPenalty = 3, },
	req = { level = 55, str = 71, int = 71, },
}
itemBases["圣记鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+4% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 186, ArmourBaseMax = 208, EnergyShieldBaseMin = 38, EnergyShieldBaseMax = 43, MovementPenalty = 3, },
	req = { level = 59, str = 76, int = 76, },
}
itemBases["斗士鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicitModTypes = { },
	armour = { BlockChance = 26, ArmourBaseMin = 215, ArmourBaseMax = 247, EnergyShieldBaseMin = 44, EnergyShieldBaseMax = 50, MovementPenalty = 3, },
	req = { level = 62, str = 85, int = 85, },
}
itemBases["厚装鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+8% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 24, ArmourBaseMin = 147, ArmourBaseMax = 169, EnergyShieldBaseMin = 30, EnergyShieldBaseMax = 34, MovementPenalty = 3, },
	req = { level = 65, str = 85, int = 85, },
}
itemBases["威能鸢盾"] = {
	type = "Shield",
	subType = "Armour/Energy Shield",
	socketLimit = 3,
	tags = { str_int_armour = true, str_int_shield = true, armour = true, default = true, shield = true, },
	implicit = "+12% 所有元素抗性",
	implicitModTypes = { { "elemental", "resistance" }, },
	armour = { BlockChance = 22, ArmourBaseMin = 156, ArmourBaseMax = 179, EnergyShieldBaseMin = 32, EnergyShieldBaseMax = 37, MovementPenalty = 3, },
	req = { level = 68, str = 85, int = 85, },
}

itemBases["尖木刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 13, EvasionBaseMax = 18, EnergyShieldBaseMin = 4, EnergyShieldBaseMax = 6, MovementPenalty = 3, },
	req = { level = 5, dex = 11, int = 11, },
}
itemBases["朽木刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 46, EvasionBaseMax = 60, EnergyShieldBaseMin = 11, EnergyShieldBaseMax = 15, MovementPenalty = 3, },
	req = { level = 12, dex = 19, int = 19, },
}
itemBases["合金刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 25, EvasionBaseMin = 56, EvasionBaseMax = 70, EnergyShieldBaseMin = 13, EnergyShieldBaseMax = 16, MovementPenalty = 3, },
	req = { level = 20, dex = 29, int = 29, },
}
itemBases["冷芒刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +5%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 26, EvasionBaseMin = 62, EvasionBaseMax = 73, EnergyShieldBaseMin = 13, EnergyShieldBaseMax = 16, MovementPenalty = 3, },
	req = { level = 27, dex = 37, int = 37, },
}
itemBases["华丽刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +5%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 120, EvasionBaseMax = 135, EnergyShieldBaseMin = 26, EnergyShieldBaseMax = 29, MovementPenalty = 3, },
	req = { level = 33, dex = 44, int = 44, },
}
itemBases["红木刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 142, EvasionBaseMax = 163, EnergyShieldBaseMin = 30, EnergyShieldBaseMax = 34, MovementPenalty = 3, },
	req = { level = 39, dex = 52, int = 52, },
}
itemBases["复合刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 25, EvasionBaseMin = 122, EvasionBaseMax = 144, EnergyShieldBaseMin = 25, EnergyShieldBaseMax = 30, MovementPenalty = 3, },
	req = { level = 45, dex = 59, int = 59, },
}
itemBases["光辉刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +5%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 26, EvasionBaseMin = 111, EvasionBaseMax = 131, EnergyShieldBaseMin = 23, EnergyShieldBaseMax = 27, MovementPenalty = 3, },
	req = { level = 49, dex = 64, int = 64, },
}
itemBases["王权刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +5%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 195, EvasionBaseMax = 218, EnergyShieldBaseMin = 40, EnergyShieldBaseMax = 45, MovementPenalty = 3, },
	req = { level = 54, dex = 70, int = 70, },
}
itemBases["桤木刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 209, EvasionBaseMax = 240, EnergyShieldBaseMin = 43, EnergyShieldBaseMax = 49, MovementPenalty = 3, },
	req = { level = 58, dex = 74, int = 74, },
}
itemBases["艾兹麦刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +3%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 25, EvasionBaseMin = 181, EvasionBaseMax = 209, EnergyShieldBaseMin = 37, EnergyShieldBaseMax = 43, MovementPenalty = 3, },
	req = { level = 62, dex = 85, int = 85, },
}
itemBases["钢镜刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +5%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 26, EvasionBaseMin = 151, EvasionBaseMax = 174, EnergyShieldBaseMin = 31, EnergyShieldBaseMax = 35, MovementPenalty = 3, },
	req = { level = 66, dex = 85, int = 85, },
}
itemBases["霸者刺盾"] = {
	type = "Shield",
	subType = "Evasion/Energy Shield",
	socketLimit = 3,
	tags = { dex_int_shield = true, default = true, armour = true, shield = true, dex_int_armour = true, },
	implicit = "法术伤害压制率 +5%",
	implicitModTypes = { {  }, },
	armour = { BlockChance = 24, EvasionBaseMin = 242, EvasionBaseMax = 278, EnergyShieldBaseMin = 49, EnergyShieldBaseMax = 57, MovementPenalty = 3, },
	req = { level = 70, dex = 85, int = 85, },
}

itemBases["黄金圣炎"] = {
	type = "Shield",
	socketLimit = 3,
	tags = { not_for_sale = true, demigods = true, armour = true, default = true, shield = true, },
	implicit = "+(11-19)% 混沌抗性",
	implicitModTypes = { { "chaos", "resistance" }, },
	armour = { BlockChance = 20, MovementPenalty = 3, },
	req = { level = 15, },
}
