-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["锈剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 4, PhysicalMax = 9, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { str = 8, dex = 8, },
}
itemBases["青铜短剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+45 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 6, PhysicalMax = 14, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 5, str = 14, dex = 14, },
}
itemBases["旧军刀"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 5, PhysicalMax = 22, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 10, str = 18, dex = 26, },
}
itemBases["阔剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 15, PhysicalMax = 21, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { level = 15, str = 30, dex = 30, },
}
itemBases["征战之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 30, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 20, str = 41, dex = 35, },
}
itemBases["远古之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+165 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 33, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { level = 24, str = 44, dex = 44, },
}
itemBases["贵族之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+190 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 33, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 28, str = 46, dex = 55, },
}
itemBases["暮色之刃"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 54, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 32, str = 57, dex = 57, },
}
itemBases["钩爪剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { maraketh = true, onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "击中时有 15% 的几率造成瘫痪",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 28, PhysicalMax = 60, CritChanceBase = 5, AttackRateBase = 1.15, Range = 11, },
	req = { level = 34, str = 64, dex = 64, },
}
itemBases["碧铜短剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+240 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 35, str = 62, dex = 62, },
}
itemBases["军用长刃"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 38, str = 55, dex = 79, },
}
itemBases["冷光长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 37, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 41, str = 72, dex = 72, },
}
itemBases["士兵长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 70, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 44, str = 83, dex = 70, },
}
itemBases["智者长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+330 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 36, PhysicalMax = 66, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 47, str = 81, dex = 81, },
}
itemBases["权贵之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+350 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 34, PhysicalMax = 55, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 50, str = 78, dex = 94, },
}
itemBases["暮光长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 30, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 53, str = 91, dex = 91, },
}
itemBases["捕捉者"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { maraketh = true, onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "击中时有 15% 的几率造成瘫痪",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 44, PhysicalMax = 94, CritChanceBase = 5, AttackRateBase = 1.15, Range = 11, },
	req = { level = 55, str = 99, dex = 99, },
}
itemBases["宝石之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+400 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 39, PhysicalMax = 83, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 56, str = 96, dex = 96, },
}
itemBases["海贼长刀"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.55, Range = 11, },
	req = { level = 58, str = 81, dex = 117, },
}
itemBases["斗士长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 54, PhysicalMax = 78, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 60, str = 113, dex = 113, },
}
itemBases["军团长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 53, PhysicalMax = 98, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11, },
	req = { level = 62, str = 122, dex = 104, },
}
itemBases["瓦尔军刃"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+460 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 46, PhysicalMax = 86, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 64, str = 113, dex = 113, },
}
itemBases["永恒之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+475 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 41, PhysicalMax = 68, CritChanceBase = 5, AttackRateBase = 1.5, Range = 11, },
	req = { level = 66, str = 104, dex = 122, },
}
itemBases["夜语长剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 99, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11, },
	req = { level = 68, str = 113, dex = 113, },
}
itemBases["虎钩"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { maraketh = true, onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "击中时有 20% 的几率造成瘫痪",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 37, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.4, Range = 11, },
	req = { level = 70, str = 119, dex = 119, },
}
itemBases["无常魂刃"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "该武器击中后造成的 100% 物理伤害转换为一种随机元素伤害",
	implicitModTypes = { { "physical_damage", "elemental_damage", "damage", "physical", "elemental", "attack" }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 33, CritChanceBase = 6, AttackRateBase = 1.6, Range = 11, },
	req = { level = 30, str = 54, dex = 54, },
}
itemBases["莫测魂刃"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "该武器击中后造成的 100% 物理伤害转换为一种随机元素伤害",
	implicitModTypes = { { "physical_damage", "elemental_damage", "damage", "physical", "elemental", "attack" }, },
	weapon = { PhysicalMin = 27, PhysicalMax = 51, CritChanceBase = 6, AttackRateBase = 1.6, Range = 11, },
	req = { level = 50, str = 94, dex = 94, },
}
itemBases["无序魂刃"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "该武器击中后造成的 100% 物理伤害转换为一种随机元素伤害",
	implicitModTypes = { { "physical_damage", "elemental_damage", "damage", "physical", "elemental", "attack" }, },
	weapon = { PhysicalMin = 34, PhysicalMax = 63, CritChanceBase = 6, AttackRateBase = 1.6, Range = 11, },
	req = { level = 70, str = 121, dex = 121, },
}

itemBases["查兰之剑"] = {
	type = "One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 5, PhysicalMax = 11, CritChanceBase = 5, AttackRateBase = 1.45, Range = 11, },
	req = { str = 9, dex = 9, },
}

itemBases["锈刺剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 5, PhysicalMax = 11, CritChanceBase = 5.5, AttackRateBase = 1.55, Range = 14, },
	req = { dex = 20, },
}
itemBases["鲸骨细刃"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 4, PhysicalMax = 17, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 7, dex = 32, },
}
itemBases["钝刃细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 20, CritChanceBase = 6, AttackRateBase = 1.5, Range = 14, },
	req = { level = 12, dex = 47, },
}
itemBases["练武者细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 25, CritChanceBase = 5.5, AttackRateBase = 1.55, Range = 14, },
	req = { level = 17, dex = 62, },
}
itemBases["锯状薄刃"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 29, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 22, dex = 77, },
}
itemBases["古代细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 46, CritChanceBase = 6.5, AttackRateBase = 1.3, Range = 14, },
	req = { level = 26, dex = 89, },
}
itemBases["贵族细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 33, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 30, dex = 101, },
}
itemBases["棘刺细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+35% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 44, CritChanceBase = 5.7, AttackRateBase = 1.4, Range = 14, },
	req = { level = 34, dex = 113, },
}
itemBases["小剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { maraketh = true, rapier = true, onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "击中时 15% 的几率造成流血",
	implicitModTypes = { { "bleed", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 40, CritChanceBase = 6, AttackRateBase = 1.55, Range = 14, },
	req = { level = 36, dex = 124, },
}
itemBases["龙骨细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 51, CritChanceBase = 5.5, AttackRateBase = 1.5, Range = 14, },
	req = { level = 37, dex = 122, },
}
itemBases["冷芒刺剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 46, CritChanceBase = 6, AttackRateBase = 1.4, Range = 14, },
	req = { level = 40, dex = 131, },
}
itemBases["穿甲刺剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 50, CritChanceBase = 5.5, AttackRateBase = 1.5, Range = 14, },
	req = { level = 43, dex = 140, },
}
itemBases["锯齿细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 49, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 46, dex = 149, },
}
itemBases["古典刺剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 18, PhysicalMax = 73, CritChanceBase = 6.5, AttackRateBase = 1.3, Range = 14, },
	req = { level = 49, dex = 158, },
}
itemBases["华丽细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 28, PhysicalMax = 51, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 52, dex = 167, },
}
itemBases["锐锋细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+35% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 67, CritChanceBase = 5.7, AttackRateBase = 1.4, Range = 14, },
	req = { level = 55, dex = 176, },
}
itemBases["花魁之剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { maraketh = true, rapier = true, onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "击中时 15% 的几率造成流血",
	implicitModTypes = { { "bleed", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 60, CritChanceBase = 6, AttackRateBase = 1.55, Range = 14, },
	req = { level = 57, dex = 190, },
}
itemBases["龙骨细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 19, PhysicalMax = 75, CritChanceBase = 5.5, AttackRateBase = 1.5, Range = 14, },
	req = { level = 58, dex = 185, },
}
itemBases["强化细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 65, CritChanceBase = 6, AttackRateBase = 1.4, Range = 14, },
	req = { level = 60, dex = 212, },
}
itemBases["寒光刺剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 69, CritChanceBase = 5.5, AttackRateBase = 1.5, Range = 14, },
	req = { level = 62, dex = 212, },
}
itemBases["螺纹细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 27, PhysicalMax = 64, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 64, dex = 212, },
}
itemBases["瓦尔细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 22, PhysicalMax = 87, CritChanceBase = 6.5, AttackRateBase = 1.3, Range = 14, },
	req = { level = 66, dex = 212, },
}
itemBases["宝饰细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 60, CritChanceBase = 5.5, AttackRateBase = 1.6, Range = 14, },
	req = { level = 68, dex = 212, },
}
itemBases["魔喙细剑"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { onehand = true, rapier = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "+35% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 72, CritChanceBase = 5.7, AttackRateBase = 1.4, Range = 14, },
	req = { level = 70, dex = 212, },
}
itemBases["骑兵军刀"] = {
	type = "Thrusting One Handed Sword",
	socketLimit = 3,
	tags = { maraketh = true, rapier = true, onehand = true, not_for_sale = true, weapon = true, sword = true, one_hand_weapon = true, default = true, },
	implicit = "击中时 20% 的几率造成流血",
	implicitModTypes = { { "bleed", "physical", "attack", "ailment" }, },
	weapon = { PhysicalMin = 32, PhysicalMax = 66, CritChanceBase = 6, AttackRateBase = 1.5, Range = 14, },
	req = { level = 72, dex = 220, },
}

itemBases["宝钥之刃"] = {
	type = "Two Handed Sword",
	hidden = true,
	socketLimit = 6,
	tags = { two_hand_weapon = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicitModTypes = { },
	weapon = { PhysicalMin = 1, PhysicalMax = 1, CritChanceBase = 5, AttackRateBase = 1.2, Range = 13, },
	req = { str = 8, dex = 8, },
}
itemBases["锈斑巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 40%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 8, PhysicalMax = 16, CritChanceBase = 5, AttackRateBase = 1.45, Range = 13, },
	req = { str = 11, dex = 11, },
}
itemBases["大剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+60 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 11, PhysicalMax = 26, CritChanceBase = 5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 8, str = 20, dex = 17, },
}
itemBases["重剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 60%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 17, PhysicalMax = 29, CritChanceBase = 5, AttackRateBase = 1.45, Range = 13, },
	req = { level = 12, str = 21, dex = 30, },
}
itemBases["双手剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+120 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 20, PhysicalMax = 38, CritChanceBase = 5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 17, str = 33, dex = 33, },
}
itemBases["术雕巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 60%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 23, PhysicalMax = 48, CritChanceBase = 5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 22, str = 45, dex = 38, },
}
itemBases["名贵巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+185 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 30, PhysicalMax = 50, CritChanceBase = 5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 27, str = 45, dex = 54, },
}
itemBases["幽魂巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 45%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 65, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 32, str = 57, dex = 57, },
}
itemBases["弯刃"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+40% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 41, PhysicalMax = 68, CritChanceBase = 6, AttackRateBase = 1.35, Range = 13, },
	req = { level = 35, str = 62, dex = 73, },
}
itemBases["冷血巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+250 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 34, PhysicalMax = 79, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 36, str = 69, dex = 58, },
}
itemBases["士兵巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 60%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 39, PhysicalMax = 65, CritChanceBase = 5, AttackRateBase = 1.45, Range = 13, },
	req = { level = 40, str = 57, dex = 83, },
}
itemBases["高山重刃"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+305 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 45, PhysicalMax = 84, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 44, str = 77, dex = 77, },
}
itemBases["符文巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 60%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 49, PhysicalMax = 102, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 48, str = 91, dex = 76, },
}
itemBases["虎牙巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+360 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 54, PhysicalMax = 89, CritChanceBase = 5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 51, str = 80, dex = 96, },
}
itemBases["凶灵巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 45%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 52, PhysicalMax = 109, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 54, str = 93, dex = 93, },
}
itemBases["细刃"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+40% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 63, PhysicalMax = 104, CritChanceBase = 6, AttackRateBase = 1.35, Range = 13, },
	req = { level = 56, str = 96, dex = 113, },
}
itemBases["行刑巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+400 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 55, PhysicalMax = 128, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 57, str = 106, dex = 89, },
}
itemBases["残暴巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "命中值提高 60%",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 62, PhysicalMax = 104, CritChanceBase = 5, AttackRateBase = 1.5, Range = 13, },
	req = { level = 59, str = 82, dex = 119, },
}
itemBases["艾兹麦巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+25% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 62, PhysicalMax = 115, CritChanceBase = 6.5, AttackRateBase = 1.4, Range = 13, },
	req = { level = 61, str = 113, dex = 113, },
}
itemBases["瓦尔巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+470 命中值",
	implicitModTypes = { { "attack" }, },
	weapon = { PhysicalMin = 68, PhysicalMax = 142, CritChanceBase = 5, AttackRateBase = 1.3, Range = 13, },
	req = { level = 63, str = 122, dex = 104, },
}
itemBases["狮爪巨剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+50 力量和敏捷",
	implicitModTypes = { { "attribute" }, },
	weapon = { PhysicalMin = 69, PhysicalMax = 115, CritChanceBase = 5, AttackRateBase = 1.45, Range = 13, },
	req = { level = 65, str = 104, dex = 122, },
}
itemBases["狱炎重剑"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "攻击技能的元素伤害提高 30%",
	implicitModTypes = { { "elemental_damage", "damage", "elemental", "attack" }, },
	weapon = { PhysicalMin = 62, PhysicalMax = 129, CritChanceBase = 5, AttackRateBase = 1.35, Range = 13, },
	req = { level = 67, str = 113, dex = 113, },
}
itemBases["精致之刃"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, maraketh = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "+50% 攻击和法术暴击伤害加成",
	implicitModTypes = { { "damage", "critical" }, },
	weapon = { PhysicalMin = 67, PhysicalMax = 112, CritChanceBase = 5.7, AttackRateBase = 1.35, Range = 13, },
	req = { level = 70, str = 119, dex = 131, },
}
itemBases["责难刀"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "暴击攻击无视敌人的元素抗性",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 34, PhysicalMax = 63, CritChanceBase = 6, AttackRateBase = 1.3, Range = 13, },
	req = { level = 30, str = 54, dex = 54, },
}
itemBases["爆破刀"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "暴击攻击无视敌人的元素抗性",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 52, PhysicalMax = 97, CritChanceBase = 6, AttackRateBase = 1.3, Range = 13, },
	req = { level = 50, str = 86, dex = 86, },
}
itemBases["放逐刀"] = {
	type = "Two Handed Sword",
	socketLimit = 6,
	tags = { two_hand_weapon = true, not_for_sale = true, weapon = true, sword = true, twohand = true, default = true, },
	implicit = "暴击攻击无视敌人的元素抗性",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 61, PhysicalMax = 114, CritChanceBase = 6, AttackRateBase = 1.3, Range = 13, },
	req = { level = 70, str = 130, dex = 130, },
}
