-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["朽木法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (8-12)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 5, PhysicalMax = 9, CritChanceBase = 7, AttackRateBase = 1.4, Range = 120, },
	req = { int = 14, },
}
itemBases["羊角法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (10-14)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 9, PhysicalMax = 16, CritChanceBase = 7, AttackRateBase = 1.2, Range = 120, },
	req = { level = 6, int = 29, },
}
itemBases["粗纹法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (11-15)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 9, PhysicalMax = 17, CritChanceBase = 7, AttackRateBase = 1.5, Range = 120, },
	req = { level = 12, int = 47, },
}
itemBases["石英法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (18-22)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 14, PhysicalMax = 27, CritChanceBase = 7, AttackRateBase = 1.3, Range = 120, },
	req = { level = 18, int = 65, },
}
itemBases["螺纹法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (15-19)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 12, PhysicalMax = 37, CritChanceBase = 7, AttackRateBase = 1.3, Range = 120, },
	req = { level = 24, int = 83, },
}
itemBases["贤者法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (17-21)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 23, PhysicalMax = 42, CritChanceBase = 8, AttackRateBase = 1.2, Range = 120, },
	req = { level = 30, int = 119, },
}
itemBases["异教法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { maraketh = true, not_for_sale = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "施法速度提高 10%",
	implicitModTypes = { { "caster", "speed" }, },
	weapon = { PhysicalMin = 22, PhysicalMax = 40, CritChanceBase = 7, AttackRateBase = 1.35, Range = 120, },
	req = { level = 34, int = 118, },
}
itemBases["兽角法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (20-24)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 26, PhysicalMax = 48, CritChanceBase = 7, AttackRateBase = 1.2, Range = 120, },
	req = { level = 35, int = 116, },
}
itemBases["符文法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (22-26)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 38, CritChanceBase = 7, AttackRateBase = 1.5, Range = 120, },
	req = { level = 40, int = 131, },
}
itemBases["水晶法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (29-33)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 28, PhysicalMax = 52, CritChanceBase = 7, AttackRateBase = 1.3, Range = 120, },
	req = { level = 45, int = 146, },
}
itemBases["蛇眼法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (26-30)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 21, PhysicalMax = 64, CritChanceBase = 7, AttackRateBase = 1.3, Range = 120, },
	req = { level = 49, int = 158, },
}
itemBases["灵兆法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (27-31)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 33, PhysicalMax = 61, CritChanceBase = 8, AttackRateBase = 1.2, Range = 120, },
	req = { level = 53, int = 200, },
}
itemBases["异徒法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { maraketh = true, not_for_sale = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "施法速度提高 10%",
	implicitModTypes = { { "caster", "speed" }, },
	weapon = { PhysicalMin = 31, PhysicalMax = 57, CritChanceBase = 7, AttackRateBase = 1.35, Range = 120, },
	req = { level = 55, int = 184, },
}
itemBases["魔角法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (31-35)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 38, PhysicalMax = 71, CritChanceBase = 7, AttackRateBase = 1.2, Range = 120, },
	req = { level = 56, int = 179, },
}
itemBases["魔性法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (33-37)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 53, CritChanceBase = 7, AttackRateBase = 1.5, Range = 120, },
	req = { level = 59, int = 188, },
}
itemBases["灵石法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (38-42)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 65, CritChanceBase = 7, AttackRateBase = 1.3, Range = 120, },
	req = { level = 62, int = 212, },
}
itemBases["狂风法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (35-39)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 75, CritChanceBase = 7, AttackRateBase = 1.3, Range = 120, },
	req = { level = 65, int = 212, },
}
itemBases["箴言法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { top_tier_base_item_type = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "法术伤害提高 (36-40)%",
	implicitModTypes = { { "caster_damage", "damage", "caster" }, },
	weapon = { PhysicalMin = 35, PhysicalMax = 64, CritChanceBase = 8, AttackRateBase = 1.2, Range = 120, },
	req = { level = 68, int = 245, },
}
itemBases["亵渎法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { maraketh = true, not_for_sale = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "施法速度提高 14%",
	implicitModTypes = { { "caster", "speed" }, },
	weapon = { PhysicalMin = 33, PhysicalMax = 61, CritChanceBase = 7, AttackRateBase = 1.35, Range = 120, },
	req = { level = 70, int = 237, },
}
itemBases["装配法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { not_for_sale = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "每 6 秒获得一个耐力球、狂怒球或暴击球",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 16, PhysicalMax = 30, CritChanceBase = 7.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 30, int = 101, },
}
itemBases["集合法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { not_for_sale = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "每 6 秒获得一个耐力球、狂怒球或暴击球",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 25, PhysicalMax = 46, CritChanceBase = 7.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 50, int = 168, },
}
itemBases["蓄能法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { not_for_sale = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "每 6 秒获得一个耐力球、狂怒球或暴击球",
	implicitModTypes = { {  }, },
	weapon = { PhysicalMin = 29, PhysicalMax = 54, CritChanceBase = 7.5, AttackRateBase = 1.4, Range = 120, },
	req = { level = 70, int = 237, },
}

itemBases["召集法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { onehand = true, ranged = true, wandatlas1 = true, weapon_can_roll_minion_modifiers = true, top_tier_base_item_type = true, wand = true, atlas_base_type = true, default = true, one_hand_weapon = true, weapon = true, },
	implicit = "召唤生物的伤害提高 (26-30)%",
	implicitModTypes = { { "damage", "minion" }, },
	weapon = { PhysicalMin = 30, PhysicalMax = 55, CritChanceBase = 7, AttackRateBase = 1.4, Range = 120, },
	req = { level = 72, int = 242, },
}

itemBases["召唤法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { weapon_can_roll_minion_modifiers = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "召唤生物的伤害提高 (12-16)%",
	implicitModTypes = { { "damage", "minion" }, },
	weapon = { PhysicalMin = 13, PhysicalMax = 25, CritChanceBase = 7, AttackRateBase = 1.4, Range = 120, },
	req = { level = 20, int = 81, },
}

itemBases["召集法杖"] = {
	type = "Wand",
	socketLimit = 3,
	tags = { weapon_can_roll_minion_modifiers = true, onehand = true, wand = true, weapon = true, ranged = true, one_hand_weapon = true, default = true, },
	implicit = "召唤生物的伤害提高 (20-24)%",
	implicitModTypes = { { "damage", "minion" }, },
	weapon = { PhysicalMin = 27, PhysicalMax = 50, CritChanceBase = 7, AttackRateBase = 1.4, Range = 120, },
	req = { level = 50, int = 183, },
}
