-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		lang={
			["Simplified Chinese"]={
				[1]={
					[1]={
						k="milliseconds_to_seconds_2dp",
						v=1
					},
					limit={
						[1]={
							[1]=1,
							[2]="#"
						}
					},
					text="减益效果持续持续 {0} 秒"
				}
			}
		},
		name="secondary_buff_duration",
		stats={
			[1]="secondary_buff_effect_duration"
		}
	},
	parent="buff_skill_stat_descriptions",
	["secondary_buff_effect_duration"]=1
}