-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Minion active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["ChaosElementalCascadeSummoned"] = {
	name = "Cascade",
	hidden = true,
	color = 3,
	baseEffectiveness = 1.3650000095367,
	incrementalEffectiveness = 0.040600001811981,
	description = "从地面上不断的冒出冰结之刺, 宛如川流一般向前攻击并对敌人造成伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.Cold] = true, [SkillType.Physical] = true, [SkillType.CanRapidFire] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		spell = true,
		area = true,
	},
	constantStats = {
		{ "upheaval_number_of_spikes", 6 },
		{ "skill_physical_damage_%_to_convert_to_chaos", 100 },
		{ "monster_penalty_against_minions_damage_+%_final_vs_player_minions", -25 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, cooldown = 3, levelRequirement = 4, statInterpolation = { 3, 3, }, },
	},
}
skills["SandstormChaosElementalSummoned"] = {
	name = "Chaos Aura",
	hidden = true,
	color = 4,
	baseEffectiveness = 6.1421999931335,
	incrementalEffectiveness = 0.052099999040365,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		duration = true,
		area = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 5000 },
		{ "active_skill_area_of_effect_radius_+%_final", 20 },
	},
	stats = {
		"base_chaos_damage_to_deal_per_minute",
		"is_area_damage",
		"spell_damage_modifiers_apply_to_skill_dot",
	},
	levels = {
		[1] = { 16.666667039196, cooldown = 8, levelRequirement = 3, statInterpolation = { 3, }, },
	},
}
skills["FireElementalFlameRedSummoned"] = {
	name = "Immolate",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.2546999454498,
	incrementalEffectiveness = 0.044599998742342,
	description = "召唤一个图腾，它会持续的对附近的敌人喷射火焰.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Trappable] = true, [SkillType.Mineable] = true, [SkillType.SummonsTotem] = true, [SkillType.Fire] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	skillTotemId = 8,
	castTime = 0.25,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	constantStats = {
		{ "active_skill_cast_speed_+%_final", -89 },
		{ "spell_maximum_action_distance_+%", -77 },
		{ "monster_penalty_against_minions_damage_+%_final_vs_player_minions", -25 },
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_is_projectile",
		"always_pierce",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 0.8, critChance = 5, levelRequirement = 3, statInterpolation = { 3, 3, }, },
	},
}
skills["FireElementalMortarSummoned"] = {
	name = "Magma Ball",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.8238000869751,
	incrementalEffectiveness = 0.034600000828505,
	description = "通用的怪物炮击技能. 与怪物投射物相似, 但带有冲击效果.",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	constantStats = {
		{ "projectile_spread_radius", 15 },
		{ "spell_maximum_action_distance_+%", -33 },
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"is_area_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 2, cooldown = 6, critChance = 5, levelRequirement = 34, statInterpolation = { 3, 3, }, },
	},
}
skills["FireElementalConeSummoned"] = {
	name = "Flame Wave",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.8845000267029,
	incrementalEffectiveness = 0.03999999910593,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, [SkillType.Fire] = true, [SkillType.AreaSpell] = true, [SkillType.Cooldown] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.935,
	baseFlags = {
		spell = true,
		area = true,
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 34, statInterpolation = { 3, 3, }, },
		[2] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 36, statInterpolation = { 3, 3, }, },
		[3] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 38, statInterpolation = { 3, 3, }, },
		[4] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 40, statInterpolation = { 3, 3, }, },
		[5] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 42, statInterpolation = { 3, 3, }, },
		[6] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 44, statInterpolation = { 3, 3, }, },
		[7] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 46, statInterpolation = { 3, 3, }, },
		[8] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 48, statInterpolation = { 3, 3, }, },
		[9] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 50, statInterpolation = { 3, 3, }, },
		[10] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 52, statInterpolation = { 3, 3, }, },
		[11] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 54, statInterpolation = { 3, 3, }, },
		[12] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 56, statInterpolation = { 3, 3, }, },
		[13] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 58, statInterpolation = { 3, 3, }, },
		[14] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 60, statInterpolation = { 3, 3, }, },
		[15] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 62, statInterpolation = { 3, 3, }, },
		[16] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 64, statInterpolation = { 3, 3, }, },
		[17] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 66, statInterpolation = { 3, 3, }, },
		[18] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 68, statInterpolation = { 3, 3, }, },
		[19] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 69, statInterpolation = { 3, 3, }, },
		[20] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 70, statInterpolation = { 3, 3, }, },
		[21] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 72, statInterpolation = { 3, 3, }, },
		[22] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 74, statInterpolation = { 3, 3, }, },
		[23] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 76, statInterpolation = { 3, 3, }, },
		[24] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 78, statInterpolation = { 3, 3, }, },
		[25] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 80, statInterpolation = { 3, 3, }, },
		[26] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 82, statInterpolation = { 3, 3, }, },
		[27] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 84, statInterpolation = { 3, 3, }, },
		[28] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 86, statInterpolation = { 3, 3, }, },
		[29] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 88, statInterpolation = { 3, 3, }, },
		[30] = { 0.80000001192093, 1.25, damageEffectiveness = 2, cooldown = 2, critChance = 5, levelRequirement = 90, statInterpolation = { 3, 3, }, },
	},
}
skills["IceElementalIceCyclone"] = {
	name = "Cyclone",
	hidden = true,
	color = 2,
	baseEffectiveness = 0.85000002384186,
	description = "对周围敌人造成伤害, 接而进行一连串的旋转攻击, 边向目标地点前进边攻击路径上的敌人, 无法被多重打击和无情辅助.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
		movement = true,
	},
	baseMods = {
		skill("dpsMultiplier", 2),
	},
	constantStats = {
		{ "cyclone_movement_speed_+%_final", 75 },
		{ "cyclone_extra_distance", 40 },
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"is_area_damage",
		"cyclone_places_ground_ice",
	},
	levels = {
		[1] = { cooldown = 6, levelRequirement = 1, },
	},
}
skills["IceElementalSpearSummoned"] = {
	name = "Ice Spear",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.2813000679016,
	incrementalEffectiveness = 0.034600000828505,
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Spell] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_reverse_point_blank_damage_-%_at_minimum_range", 25 },
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.5, cooldown = 4, levelRequirement = 3, statInterpolation = { 3, 3, }, },
	},
}
skills["LightningGolemArcSummoned"] = {
	name = "Storm Orb",
	hidden = true,
	color = 3,
	baseEffectiveness = 0.78420001268387,
	incrementalEffectiveness = 0.028500000014901,
	skillTypes = { [SkillType.Duration] = true, [SkillType.Lightning] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.ProjectileSpeed] = true, [SkillType.Spell] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		spell = true,
		projectile = true,
		duration = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 8000 },
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
	},
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, damageEffectiveness = 0.6, cooldown = 8, critChance = 6, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["MonsterProjectileSpellLightningGolemSummoned"] = {
	name = "Lightning Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 3.2934999465942,
	incrementalEffectiveness = 0.036100000143051,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 11 },
		{ "active_skill_cast_speed_+%_final", -15 },
		{ "spell_maximum_action_distance_+%", -40 },
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, damageEffectiveness = 2.5, critChance = 6, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["LightningGolemWrath"] = {
	name = "Wrath",
	hidden = true,
	color = 3,
	baseEffectiveness = 0.16249999403954,
	incrementalEffectiveness = 0.019999999552965,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Buff] = true, [SkillType.Aura] = true, [SkillType.Lightning] = true, [SkillType.Duration] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	statMap = {
		["attack_minimum_added_lightning_damage"] = {
			mod("LightningMin", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["attack_maximum_added_lightning_damage"] = {
			mod("LightningMax", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_minimum_added_lightning_damage"] = {
			mod("LightningMin", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_maximum_added_lightning_damage"] = {
			mod("LightningMax", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
	},
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		duration = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"attack_minimum_added_lightning_damage",
		"attack_maximum_added_lightning_damage",
		"spell_minimum_added_lightning_damage",
		"spell_maximum_added_lightning_damage",
		"base_deal_no_damage",
	},
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, 0.11999999731779, 1.0800000429153, cooldown = 12, levelRequirement = 1, statInterpolation = { 3, 3, 3, 3, }, },
	},
}
skills["SpectralSkullShieldCharge"] = {
	name = "Charge",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "向一个目标冲锋, 使用盾牌对其猛击的同时也用近战武器顺手补刀. 此攻击将会击退目标并将其击晕, 在路径上的敌人将会被推向两旁. 伤害与击晕几率将视冲锋距离而定. ",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	constantStats = {
		{ "shield_charge_stun_duration_+%_maximum", 200 },
		{ "base_movement_velocity_+%", 500 },
		{ "shield_charge_damage_+%_maximum", 300 },
		{ "active_skill_damage_+%_final", -50 },
	},
	stats = {
		"ignores_proximity_shield",
	},
	levels = {
		[1] = { cooldown = 5, levelRequirement = 1, },
	},
}
skills["RagingSpiritMeleeAttack"] = {
	name = "普通攻击",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "对你的敌人无情痛击.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	stats = {
		"active_skill_damage_+%_final",
	},
	levels = {
		[1] = { 76, levelRequirement = 4, statInterpolation = { 1, }, },
		[2] = { 71, levelRequirement = 6, statInterpolation = { 1, }, },
		[3] = { 66, levelRequirement = 9, statInterpolation = { 1, }, },
		[4] = { 61, levelRequirement = 12, statInterpolation = { 1, }, },
		[5] = { 56, levelRequirement = 15, statInterpolation = { 1, }, },
		[6] = { 52, levelRequirement = 19, statInterpolation = { 1, }, },
		[7] = { 47, levelRequirement = 23, statInterpolation = { 1, }, },
		[8] = { 42, levelRequirement = 28, statInterpolation = { 1, }, },
		[9] = { 37, levelRequirement = 33, statInterpolation = { 1, }, },
		[10] = { 32, levelRequirement = 39, statInterpolation = { 1, }, },
		[11] = { 28, levelRequirement = 43, statInterpolation = { 1, }, },
		[12] = { 23, levelRequirement = 46, statInterpolation = { 1, }, },
		[13] = { 18, levelRequirement = 49, statInterpolation = { 1, }, },
		[14] = { 12, levelRequirement = 52, statInterpolation = { 1, }, },
		[15] = { 10, levelRequirement = 55, statInterpolation = { 1, }, },
		[16] = { 7, levelRequirement = 58, statInterpolation = { 1, }, },
		[17] = { 5, levelRequirement = 61, statInterpolation = { 1, }, },
		[18] = { 2, levelRequirement = 64, statInterpolation = { 1, }, },
		[19] = { 0, levelRequirement = 66, statInterpolation = { 1, }, },
		[20] = { -2, levelRequirement = 68, statInterpolation = { 1, }, },
		[21] = { -4, levelRequirement = 70, statInterpolation = { 1, }, },
		[22] = { -7, levelRequirement = 72, statInterpolation = { 1, }, },
		[23] = { -10, levelRequirement = 74, statInterpolation = { 1, }, },
	},
}
skills["SkeletonMinionProjectileCold"] = {
	name = "Cold Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.1579999923706,
	incrementalEffectiveness = 0.040899999439716,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.2,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["SkeletonMinionProjectileFire"] = {
	name = "Fire Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.1579999923706,
	incrementalEffectiveness = 0.040899999439716,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.2,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, critChance = 5, levelRequirement = 12, statInterpolation = { 3, 3, }, },
	},
}
skills["SkeletonMinionProjectileLightning"] = {
	name = "Lightning Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.1579999923706,
	incrementalEffectiveness = 0.040899999439716,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Multicastable] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.2,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_is_projectile",
	},
	levels = {
		[1] = { 0.5, 1.5, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["RockGolemSlam"] = {
	name = "Slam",
	hidden = true,
	color = 1,
	baseEffectiveness = 0,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_attack_speed_+%_final", -20 },
		{ "chance_to_taunt_on_hit_%", 33 },
		{ "active_skill_area_of_effect_radius_+%_final", 200 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { damageEffectiveness = 2, cooldown = 4, baseMultiplier = 2, levelRequirement = 1, },
	},
}
skills["RockGolemMinionWhirlingBlades"] = {
	name = "Roll",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "迅速穿越敌人并同时造成武器伤害. 限定匕首, 爪以及单手剑. ",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.43,
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	constantStats = {
		{ "skill_sound_variation", 1 },
		{ "active_skill_attack_speed_+%_final", -25 },
		{ "monster_flurry", 1 },
	},
	stats = {
		"cast_time_overrides_attack_duration",
		"ignores_proximity_shield",
	},
	levels = {
		[1] = { cooldown = 6, levelRequirement = 1, },
	},
}
skills["ZombieSlam"] = {
	name = "Slam",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("radius", 18),
	},
	constantStats = {
		{ "active_skill_area_of_effect_radius_+%_final", 25 },
	},
	stats = {
		"active_skill_attack_speed_+%_final",
		"active_skill_damage_+%_final",
		"is_area_damage",
		"global_always_hit",
	},
	levels = {
		[1] = { -30, -20, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, 1, }, },
		[2] = { -28, -10, cooldown = 6, levelRequirement = 12, statInterpolation = { 1, 1, }, },
		[3] = { -26, 0, cooldown = 6, levelRequirement = 20, statInterpolation = { 1, 1, }, },
		[4] = { -24, 10, cooldown = 6, levelRequirement = 33, statInterpolation = { 1, 1, }, },
		[5] = { -22, 15, cooldown = 6, levelRequirement = 45, statInterpolation = { 1, 1, }, },
	},
}
skills["SummonedSpiderViperStrike"] = {
	name = "毒蛇打击",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.64999997615814,
	incrementalEffectiveness = 0.025499999523163,
	description = "击中敌人，将部分部分物理伤害转化为混沌伤害，并使敌人中毒。该技能受技能持续时间词缀影响。双持武器时会用两把武器同时攻击。限定爪类、匕首与剑类。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Duration] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.DamageOverTime] = true, [SkillType.Chaos] = true, },
	weaponTypes = {
		["Claw"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "debuff_skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	constantStats = {
		{ "base_chance_to_poison_on_hit_%", 100 },
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"poison_duration_is_skill_duration",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["DancingDervishCycloneChannelled"] = {
	name = "旋风斩",
	hidden = true,
	color = 4,
	description = "持续吟唱该技能，向指定地点旋转移动，持续攻击你周围的敌人，并积累阶段。持续吟唱该技能时，你无法被击退。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, [SkillType.Channel] = true, [SkillType.Physical] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	baseMods = {
		skill("radiusIsWeaponRange", true),
	},
	constantStats = {
		{ "cyclone_gain_stage_every_x_ms_while_channelling", 170 },
		{ "cyclone_melee_weapon_range_+_per_stage", 1 },
		{ "cyclone_stage_decay_time_ms", 330 },
		{ "cyclone_max_number_of_stages", 6 },
		{ "cyclone_area_of_effect_+%_per_additional_melee_range", 8 },
	},
	stats = {
		"is_area_damage",
		"skill_can_add_multiple_charges_per_action",
	},
	levels = {
		[1] = { damageEffectiveness = 0.65, attackSpeedMultiplier = 200, baseMultiplier = 0.65, levelRequirement = 0, },
	},
}
skills["SummonPhantasmFadingProjectile"] = {
	name = "Physical Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0221999883652,
	incrementalEffectiveness = 0.048500001430511,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.Damage] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.17,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"base_is_projectile",
		"always_pierce",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.5, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, }, },
	},
}
skills["HeraldOfAgonyMinionMortar"] = {
	name = "Mortar",
	hidden = true,
	color = 4,
	description = "通用的怪物炮击技能. 与怪物投射物相似, 但带有冲击效果.",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Attack] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Trappable] = true, [SkillType.Totemable] = true, [SkillType.Mineable] = true, [SkillType.Multicastable] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2,
	baseFlags = {
		attack = true,
		projectile = true,
		area = true,
	},
	constantStats = {
		{ "projectile_spread_radius", 20 },
		{ "projectile_minimum_range", 10 },
		{ "number_of_additional_projectiles", 5 },
		{ "active_skill_attack_speed_+%_final", -35 },
		{ "main_hand_base_maximum_attack_distance", 50 },
		{ "active_skill_area_of_effect_radius_+%_final", 20 },
	},
	stats = {
		"is_area_damage",
		"base_is_projectile",
		"distribute_additional_projectiles_over_contact_points",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { damageEffectiveness = 0.4, cooldown = 7.5, baseMultiplier = 0.4, levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionTailSpike"] = {
	name = "Tail Spike",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.3,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 39 },
		{ "number_of_additional_projectiles", 4 },
	},
	stats = {
		"base_is_projectile",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionCleave"] = {
	name = "Cleave",
	hidden = true,
	color = 1,
	description = "在身体前方以弧状挥动武器（双持时则挥动两把武器）, 对前方区域的怪物造成伤害。限定斧类与剑类。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ThresholdJewelArea] = true, [SkillType.Physical] = true, },
	weaponTypes = {
		["Two Handed Axe"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Two Handed Sword"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_area_of_effect_radius_+%_final", 30 },
	},
	stats = {
		"is_area_damage",
		"visual_hit_effect_chaos_is_green",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["HeraldOfLightMinionSlam"] = {
	name = "Slam",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_attack_speed_+%_final", -33 },
		{ "active_skill_area_of_effect_radius_+%_final", 100 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["SentinelHolySlam"] = {
	name = "Crusade Slam",
	hidden = true,
	color = 1,
	baseEffectiveness = 0,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "active_skill_attack_speed_+%_final", -33 },
		{ "active_skill_area_of_effect_radius_+%_final", 100 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { damageEffectiveness = 2, cooldown = 5, baseMultiplier = 2, levelRequirement = 0, },
	},
}
skills["RelicTriggeredNova"] = {
	name = "Nova",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.1052000522614,
	incrementalEffectiveness = 0.057900000363588,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.InbuiltTrigger] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	constantStats = {
		{ "holy_relic_trigger_on_parent_attack_%", 100 },
		{ "base_skill_effect_duration", 4000 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"active_skill_area_of_effect_radius_+%_final",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, -24, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 4, statInterpolation = { 3, 3, 1, }, },
		[2] = { 0.80000001192093, 1.2000000476837, -23, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 6, statInterpolation = { 3, 3, 1, }, },
		[3] = { 0.80000001192093, 1.2000000476837, -22, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 9, statInterpolation = { 3, 3, 1, }, },
		[4] = { 0.80000001192093, 1.2000000476837, -20, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 12, statInterpolation = { 3, 3, 1, }, },
		[5] = { 0.80000001192093, 1.2000000476837, -19, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 16, statInterpolation = { 3, 3, 1, }, },
		[6] = { 0.80000001192093, 1.2000000476837, -18, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 20, statInterpolation = { 3, 3, 1, }, },
		[7] = { 0.80000001192093, 1.2000000476837, -17, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 24, statInterpolation = { 3, 3, 1, }, },
		[8] = { 0.80000001192093, 1.2000000476837, -15, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 28, statInterpolation = { 3, 3, 1, }, },
		[9] = { 0.80000001192093, 1.2000000476837, -14, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 32, statInterpolation = { 3, 3, 1, }, },
		[10] = { 0.80000001192093, 1.2000000476837, -13, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 36, statInterpolation = { 3, 3, 1, }, },
		[11] = { 0.80000001192093, 1.2000000476837, -12, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 40, statInterpolation = { 3, 3, 1, }, },
		[12] = { 0.80000001192093, 1.2000000476837, -10, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 44, statInterpolation = { 3, 3, 1, }, },
		[13] = { 0.80000001192093, 1.2000000476837, -9, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 48, statInterpolation = { 3, 3, 1, }, },
		[14] = { 0.80000001192093, 1.2000000476837, -8, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 52, statInterpolation = { 3, 3, 1, }, },
		[15] = { 0.80000001192093, 1.2000000476837, -7, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 55, statInterpolation = { 3, 3, 1, }, },
		[16] = { 0.80000001192093, 1.2000000476837, -5, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 58, statInterpolation = { 3, 3, 1, }, },
		[17] = { 0.80000001192093, 1.2000000476837, -4, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 61, statInterpolation = { 3, 3, 1, }, },
		[18] = { 0.80000001192093, 1.2000000476837, -3, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 64, statInterpolation = { 3, 3, 1, }, },
		[19] = { 0.80000001192093, 1.2000000476837, -2, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 67, statInterpolation = { 3, 3, 1, }, },
		[20] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 70, statInterpolation = { 3, 3, }, },
		[21] = { 0.80000001192093, 1.2000000476837, 1, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 72, statInterpolation = { 3, 3, 1, }, },
		[22] = { 0.80000001192093, 1.2000000476837, 3, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 74, statInterpolation = { 3, 3, 1, }, },
		[23] = { 0.80000001192093, 1.2000000476837, 4, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 76, statInterpolation = { 3, 3, 1, }, },
		[24] = { 0.80000001192093, 1.2000000476837, 6, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 78, statInterpolation = { 3, 3, 1, }, },
		[25] = { 0.80000001192093, 1.2000000476837, 7, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 80, statInterpolation = { 3, 3, 1, }, },
		[26] = { 0.80000001192093, 1.2000000476837, 9, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 82, statInterpolation = { 3, 3, 1, }, },
		[27] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 84, statInterpolation = { 3, 3, 1, }, },
		[28] = { 0.80000001192093, 1.2000000476837, 12, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 86, statInterpolation = { 3, 3, 1, }, },
		[29] = { 0.80000001192093, 1.2000000476837, 13, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 88, statInterpolation = { 3, 3, 1, }, },
		[30] = { 0.80000001192093, 1.2000000476837, 15, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 90, statInterpolation = { 3, 3, 1, }, },
		[31] = { 0.80000001192093, 1.2000000476837, 16, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 91, statInterpolation = { 3, 3, 1, }, },
		[32] = { 0.80000001192093, 1.2000000476837, 18, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 92, statInterpolation = { 3, 3, 1, }, },
		[33] = { 0.80000001192093, 1.2000000476837, 19, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 93, statInterpolation = { 3, 3, 1, }, },
		[34] = { 0.80000001192093, 1.2000000476837, 21, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 94, statInterpolation = { 3, 3, 1, }, },
		[35] = { 0.80000001192093, 1.2000000476837, 22, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 95, statInterpolation = { 3, 3, 1, }, },
		[36] = { 0.80000001192093, 1.2000000476837, 24, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 96, statInterpolation = { 3, 3, 1, }, },
		[37] = { 0.80000001192093, 1.2000000476837, 25, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 97, statInterpolation = { 3, 3, 1, }, },
		[38] = { 0.80000001192093, 1.2000000476837, 27, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 98, statInterpolation = { 3, 3, 1, }, },
		[39] = { 0.80000001192093, 1.2000000476837, 28, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 99, statInterpolation = { 3, 3, 1, }, },
		[40] = { 0.80000001192093, 1.2000000476837, 30, damageEffectiveness = 2.5, cooldown = 0.3, critChance = 5, levelRequirement = 100, statInterpolation = { 3, 3, 1, }, },
	},
}
skills["DominatingBlowMinionCharge"] = {
	name = "重盾冲锋",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "向目标区域或敌人冲锋，在路径上的敌人将会被推向两旁，并反复对你前方小范围区域内造成伤害。 抵达目标处时造成大范围伤害。伤害与击晕几率将视冲锋距离而定。无法被多重打击辅助。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RequiresShield] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	constantStats = {
		{ "shield_charge_scaling_stun_threshold_reduction_+%_at_maximum_range", 25 },
		{ "base_movement_velocity_+%", 400 },
		{ "shield_charge_damage_+%_maximum", 30 },
		{ "active_skill_area_of_effect_radius_+%_final", -40 },
	},
	stats = {
		"ignores_proximity_shield",
		"global_cannot_crit",
	},
	levels = {
		[1] = { cooldown = 4, levelRequirement = 1, },
	},
}
skills["AbsolutionMinion"] = {
	name = "赦罪",
	hidden = true,
	color = 1,
	baseEffectiveness = 1.9819999933243,
	incrementalEffectiveness = 0.045299999415874,
	description = "伤害一片区域内的敌人，在短时间内施加一个减益效果。若受该减益效果影响的非传奇敌人被消灭，则消耗它的灵枢来召唤一名持续时间较长的赦罪哨卫。如果你召唤的赦罪哨卫达到数量上限，则刷新其中一个的持续时间和生命值。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Duration] = true, [SkillType.MinionsCanExplode] = true, [SkillType.CreatesMinion] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Multicastable] = true, [SkillType.Cascadable] = true, [SkillType.Physical] = true, [SkillType.Lightning] = true, [SkillType.Triggerable] = true, [SkillType.Totemable] = true, [SkillType.Trappable] = true, [SkillType.Mineable] = true, [SkillType.CanRapidFire] = true, },
	statDescriptionScope = "minion_spell_damage_skill_stat_descriptions",
	castTime = 0.75,
	baseFlags = {
		area = true,
		spell = true,
		duration = true,
	},
	constantStats = {
		{ "spell_maximum_action_distance_+%", -50 },
		{ "active_skill_area_of_effect_radius_+%_final", -25 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.8, critChance = 6, levelRequirement = 12, statInterpolation = { 3, 3, }, },
	},
}
skills["AbsolutionMinionEmpowered"] = {
	name = "赦罪",
	hidden = true,
	color = 1,
	baseEffectiveness = 1.4865000247955,
	incrementalEffectiveness = 0.045299999415874,
	description = "伤害一片区域内的敌人，在短时间内施加一个减益效果。若受该减益效果影响的非传奇敌人被消灭，则消耗它的灵枢来召唤一名持续时间较长的赦罪哨卫。如果你召唤的赦罪哨卫达到数量上限，则刷新其中一个的持续时间和生命值。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Duration] = true, [SkillType.MinionsCanExplode] = true, [SkillType.CreatesMinion] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.Multicastable] = true, [SkillType.Cascadable] = true, [SkillType.Physical] = true, [SkillType.Lightning] = true, [SkillType.Triggerable] = true, [SkillType.Totemable] = true, [SkillType.Trappable] = true, [SkillType.Mineable] = true, [SkillType.CanRapidFire] = true, },
	statDescriptionScope = "minion_spell_damage_skill_stat_descriptions",
	castTime = 0.75,
	baseFlags = {
		area = true,
		spell = true,
		duration = true,
	},
	constantStats = {
		{ "spell_maximum_action_distance_+%", -50 },
		{ "absolution_blast_shockwave_every_x_beams", 1 },
		{ "active_skill_area_of_effect_radius_+%_final", -25 },
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"is_area_damage",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.3, cooldown = 6, critChance = 6, levelRequirement = 0, statInterpolation = { 3, 3, }, },
	},
}
skills["SummonedRhoaShieldCharge"] = {
	name = "重盾冲锋",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "向目标区域或敌人冲锋，在路径上的敌人将会被推向两旁，并反复对你前方小范围区域内造成伤害。 抵达目标处时造成大范围伤害。伤害与击晕几率将视冲锋距离而定。无法被多重打击辅助。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RequiresShield] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	constantStats = {
		{ "shield_charge_scaling_stun_threshold_reduction_+%_at_maximum_range", 50 },
		{ "base_movement_velocity_+%", 100 },
		{ "shield_charge_damage_+%_maximum", 10 },
		{ "attack_speed_+%", 20 },
		{ "physical_damage_%_to_add_as_lightning", 15 },
	},
	stats = {
		"ignores_proximity_shield",
	},
	levels = {
		[1] = { cooldown = 3, levelRequirement = 1, },
	},
}
skills["SummonedSnakeProjectile"] = {
	name = "Chaos Projectile",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.8700000047684,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 1 },
	},
	stats = {
		"base_is_projectile",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["DropBearSummonedGroundSlam"] = {
	name = "裂地之击",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "以长杖、锤类、短杖重击地面，制造出一道向前释放的冲击波，被此冲击波击中的敌人将会受到伤害并有较高几率被击晕。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.Slam] = true, [SkillType.Totemable] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Two Handed Mace"] = true,
		["Staff"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { cooldown = 3, levelRequirement = 1, },
	},
}
skills["DropBearSummonedRallyingCry"] = {
	name = "激励战吼",
	hidden = true,
	color = 1,
	description = "施展战吼, 使自身和盟友伤害和魔力恢复增加. 伤害增加量随着周围敌人数量提升. 嘲讽周围所有敌人, 使他们攻击施放者. 与其他战吼技能共享技能冷却.",
	skillTypes = { [SkillType.Buff] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.Warcry] = true, [SkillType.Cooldown] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.25,
	statMap = {
		["damage_+%"] = {
			mod("Damage", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		},
	},
	baseFlags = {
		warcry = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("buffAllies", true),
	},
	constantStats = {
		{ "damage_+%", 25 },
		{ "base_skill_effect_duration", 4000 },
		{ "base_mana_regeneration_rate_per_minute", 888 },
		{ "active_skill_area_of_effect_radius_+%_final", -25 },
	},
	stats = {
		"base_deal_no_damage",
	},
	levels = {
		[1] = { cooldown = 5, levelRequirement = 1, },
	},
}
skills["BoneGolemMultiAttack"] = {
	name = "Combo Attack",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	statMap = {
		["bone_golem_attack_speed_+%_final_after_third_combo_index"] = {
			mod("Speed", "MORE", nil, 0, KeywordFlag.Attack),
			div = 1.5,
		},
		["bone_golem_damage_+%_final_after_third_combo_index"] = {
			mod("Damage", "MORE", nil),
			div = 1.5,
		},
	},
	baseFlags = {
		attack = true,
		melee = true,
	},
	constantStats = {
		{ "bone_golem_attack_speed_+%_final_after_third_combo_index", 200 },
		{ "bone_golem_damage_+%_final_after_third_combo_index", 20 },
	},
	stats = {
	},
	levels = {
		[1] = { damageEffectiveness = 1.35, baseMultiplier = 1.35, levelRequirement = 1, },
	},
}
skills["BoneGolemCascade"] = {
	name = "Cascade",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	constantStats = {
		{ "upheaval_number_of_spikes", 4 },
		{ "active_skill_base_radius_+", 1 },
	},
	stats = {
		"is_area_damage",
	},
	levels = {
		[1] = { attackSpeedMultiplier = -10, cooldown = 6, damageEffectiveness = 0.65, baseMultiplier = 0.65, levelRequirement = 1, },
	},
}
skills["BoneGolemLeapSlam"] = {
	name = "跃击",
	hidden = true,
	color = 4,
	description = "一跃而起，落地时用武器对敌人造成伤害，并击退敌人。被踩到的敌人会被推出去。限定斧头、锤类、短杖、剑类或长杖。无法被被多重打击辅助。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.Movement] = true, [SkillType.Travel] = true, [SkillType.Slam] = true, [SkillType.Totemable] = true, },
	weaponTypes = {
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	constantStats = {
		{ "active_skill_area_of_effect_radius_+%_final", 30 },
	},
	stats = {
		"is_area_damage",
		"disable_attack_repeats",
	},
	levels = {
		[1] = { attackSpeedMultiplier = -44, cooldown = 4, damageEffectiveness = 1.8, baseMultiplier = 1.8, levelRequirement = 1, },
	},
}
skills["SkitterbotWait"] = {
	name = "Skitterbot Wait",
	hidden = true,
	color = 4,
	skillTypes = { },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		duration = true,
	},
	constantStats = {
		{ "base_skill_effect_duration", 200 },
	},
	stats = {
	},
	levels = {
		[1] = { levelRequirement = 0, },
	},
}
skills["MinionInstability"] = {
	name = "Minion Instability",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		fire = true,
	},
	skillTypes = { [10] = true, },
	baseMods = {
		skill("FireMin", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("FireMax", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("showAverage", true),
		skill("radius", 22),
	},
	stats = {
	},
	levelMods = {
	},
	levels = {
		[1] = { cost = { } },
	},
}
skills["SiegebreakerCausticGround"] = {
	name = "Caustic Ground",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	skillTypes = { },
	baseMods = {
		skill("ChaosDot", 1, { type = "PerStat", stat = "Life", div = 5 }),
		skill("dotIsArea", true),
		flag("dotIsCausticGround"),
	},
	qualityStats = {
	},
	stats = {
	},
	levels = {
		[1] = { cost = { } },
	},
}
skills["ReplicaSiegebreakerBurningGround"] = {
	name = "Burning Ground",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		fire = true,
	},
	skillTypes = { },
	baseMods = {
		skill("FireDot", 1, { type = "PerStat", stat = "Life", div = 5 }),
		skill("dotIsArea", true),
		flag("dotIsBurningGround"),
	},
	qualityStats = {
	},
	stats = {
	},
	levels = {
		[1] = { cost = { } },
	},
}
skills["InfernalLegion"] = {
	name = "Infernal Legion",
	hidden = true,
	color = 4,
	baseFlags = {
		spell = true,
		area = true,
	},
	skillTypes = { },
	baseMods = {
		skill("FireDot", 1, { type = "Multiplier", var = "InfernalLegionBaseDamage" }),
		skill("dotIsArea", true),
	},
	qualityStats = {
	},
	stats = {
	},
	levels = {
		[1] = { cost = { } },
	},
}

skills["MeleeAtAnimationSpeedUnique"] = {
	name = "Default Attack",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "对你的敌人无情痛击.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	stats = {
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"action_attack_or_cast_time_uses_animation_length",
		"projectile_uses_contact_position",
		"use_scaled_contact_offset",
	},
	levels = {
		[1] = { attackSpeedMultiplier = -25, levelRequirement = 1, },
	},
}
skills["SummonedReaperMelee"] = {
	name = "Default Attack",
	hidden = true,
	color = 4,
	baseEffectiveness = 0,
	description = "对你的敌人无情痛击.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Multistrikeable] = true, [SkillType.Melee] = true, [SkillType.ProjectilesFromUser] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"action_attack_or_cast_time_uses_animation_length",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["SummonedReaperUltimate"] = {
	name = "Ultimate",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.Damage] = true, [SkillType.Area] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Movement] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 1.5, baseMultiplier = 1.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 1.65, baseMultiplier = 1.65, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["GASummonReaperUltimateLeftSlash"] = {
	name = "Ultimate Slash",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 1.5, baseMultiplier = 1.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 1.5, baseMultiplier = 1.5, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["GASummonReaperComboWhirl"] = {
	name = "Whirl",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, damageEffectiveness = 0.5, baseMultiplier = 0.5, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["GASummonReaperComboLeftSlash"] = {
	name = "Combo Slash",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.Attack] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
	},
	stats = {
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, levelRequirement = 28, statInterpolation = { 2, }, },
		[2] = { 60, levelRequirement = 80, statInterpolation = { 2, }, },
	},
}
skills["MPWExpeditionSummonedArbalestProjectile"] = {
	name = "Projectile Attack",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.RangedAttack] = true, [SkillType.MirageArcherCanUse] = true, [SkillType.Projectile] = true, [SkillType.ProjectilesFromUser] = true, [SkillType.Damage] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.5,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	constantStats = {
		{ "monster_projectile_variation", 145 },
	},
	stats = {
		"base_is_projectile",
		"projectile_uses_contact_position",
		"use_scaled_contact_offset",
	},
	levels = {
		[1] = { levelRequirement = 1, },
	},
}