-- This file is automatically generated, do not edit!
-- Skill costs data (c) Grinding Gear Games

return {
	[1] = {
		Resource = "Mana",
		Stat = "base_mana_cost",
		ResourceString = "{0} 点魔力",
	},
	[2] = {
		Resource = "Life",
		Stat = "base_life_cost",
		ResourceString = "{0} 点生命",
	},
	[3] = {
		Resource = "ES",
		Stat = "base_es_cost",
		ResourceString = "{0} 点能量护盾",
	},
	[4] = {
		Resource = "Rage",
		Stat = "base_rage_cost",
		ResourceString = "{0} 点怒火",
	},
	[5] = {
		Resource = "ManaPercent",
		Stat = "base_mana_cost_%",
		ResourceString = "{0}% 魔力",
	},
	[6] = {
		Resource = "LifePercent",
		Stat = "base_life_cost_%",
		ResourceString = "{0}% 生命",
	},
	[7] = {
		Resource = "UnreservedManaPercent",
		Stat = "base_unreserved_mana_cost_%",
		ResourceString = "[DNT] {0}% Unreserved Mana ",
	},
	[8] = {
		Resource = "ManaPerMinute",
		Stat = "base_mana_cost_per_minute",
		ResourceString = "魔力每秒 {0} 点",
	},
	[9] = {
		Resource = "LifePerMinute",
		Stat = "base_life_cost_per_minute",
		ResourceString = "生命每秒 {0} 点",
	},
	[10] = {
		Resource = "ManaPercentPerMinute",
		Stat = "base_mana_cost_%_per_minute",
		ResourceString = "魔力每秒 {0}%",
	},
	[11] = {
		Resource = "LifePercentPerMinute",
		Stat = "base_life_cost_%_per_minute",
		ResourceString = "生命每秒 {0}%",
	},
	[12] = {
		Resource = "ESPerMinute",
		Stat = "base_es_cost_per_minute",
		ResourceString = "能量护盾每秒 {0} 点",
	},
	[13] = {
		Resource = "ESPercentPerMinute",
		Stat = "base_es_cost_%_per_minute",
		ResourceString = "能量护盾每秒 {0}%",
	},
}
