-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Weapon"] = {
		{ type = "", affix = "","品质不提高物理伤害","每 2% 品质使元素伤害提高 1%",  level = 1},
		{ type = "", affix = "","品质不提高物理伤害","每 4% 品质使范围效果扩大 1%",  level = 1},
		{ type = "", affix = "","品质不提高物理伤害","每 2% 品质使命中值提高提高 1%",  level = 1},
		{ type = "", affix = "","品质不提高物理伤害","每 8% 品质使攻击速度加快 1%",  level = 1},
		{ type = "", affix = "","品质不提高物理伤害","每 4% 品质使暴击率提高 1%",  level = 1},
		{ type = "", affix = "","品质不提高物理伤害","每 10% 品质 +1 武器范围",  level = 1},		
	},
	["Body Armour"] = {
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1 力量",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1 智慧",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1 敏捷",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1 最大生命",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1 最大魔力",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1% 火焰抗性",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1% 冰霜抗性",  level = 1},
		{ type = "", affix = "","品质不提高防御属性","每 2% 品质 +1% 闪电抗性",  level = 1},
		 
	},
	
}