-- This file is automatically generated, do not edit!
-- The Pantheon data (c) Grinding Gear Games

return {
	["TheBrineKing"] = {
		isMajorGod = true,
		souls = {
			[1] = { name = "惊海之王 索亚格斯之魂",
				mods = {
					-- cannot_be_stunned_if_have_been_stunned_or_blocked_stunning_hit_in_past_2_seconds
					[1] = { line = "若过去的 2 秒内你被晕眩或是格挡晕眩，你将无法再被晕眩", value = { 1 }, },
				},
			},
			[2] = { name = "被诅咒的克莱奔船长",
				mods = {
					-- base_stun_recovery_+%
					[1] = { line = "晕眩回复和格挡回复提高 30%", value = { 30 }, },
				},
			},
			[3] = { name = "光明姐妹娥拉",
				mods = {
					-- base_avoid_freeze_%
					[1] = { line = "100% 几率避免被冰冻", value = { 100 }, },
				},
			},
			[4] = { name = "复生者莫薇儿",
				mods = {
					-- chill_effectiveness_on_self_+%
					[1] = { line = "你受到的冰缓效果降低 50%", value = { -50 }, },
				},
			},
		},
	},
	["Arakaali"] = {
		isMajorGod = true,
		souls = {
			[1] = { name = "暗影女皇 阿拉卡力之魂",
				mods = {
					-- degen_effect_+%
					[1] = { line = "受到的持续性伤害降低 10%", value = { -10 }, },
				},
			},
			[2] = { name = "巨猿原祖",
				mods = {
					-- life_and_energy_shield_recovery_rate_+%_if_stopped_taking_damage_over_time_recently
					[1] = { line = "近期内若你停止受到持续伤害，则生命和能量护盾回复速度提高 20%", value = { 20 }, },
				},
			},
			[3] = { name = "丛林皇蛛",
				mods = {
					-- debuff_time_passed_+%
					[1] = { line = "你身上的减益效果消失速度提高 20%", value = { 20 }, },
				},
			},
			[4] = { name = "虚空之异",
				mods = {
					-- additional_chaos_resistance_against_damage_over_time_%
					[1] = { line = "对持续伤害有 +40% 混沌抗性", value = { 40 }, },
				},
			},
		},
	},
	["Solaris"] = {
		isMajorGod = true,
		souls = {
			[1] = { name = "日耀女神之魂",
				mods = {
					-- physical_damage_reduction_%_if_only_one_enemy_nearby
					[1] = { line = "若附近只有 1 个敌人，则受到的物理伤害降低 6%", value = { 6 }, },
					-- take_half_area_damage_from_hit_%_chance
					[2] = { line = "有 20% 的几率使受到的范围总伤害额外降低 50%", value = { 20 }, },
				},
			},
			[2] = { name = "炎灵密卡拉",
				mods = {
					-- elemental_damage_taken_+%_if_not_hit_recently
					[1] = { line = "若你近期内没有被击中，则受到的元素伤害降低 8%", value = { -8 }, },
				},
			},
			[3] = { name = "炽怒之灵",
				mods = {
					-- self_take_no_extra_damage_from_critical_strikes_if_have_been_crit_recently
					[1] = { line = "近期你若受到过暴击伤害，则不再受到暴击的额外伤害", value = { 1 }, },
				},
			},
			[4] = { name = "毁灭者奇塔弗",
				mods = {
					-- avoid_ailments_%_from_crit
					[1] = { line = "50% 几率避免暴击造成的异常状态", value = { 50 }, },
				},
			},
		},
	},
	["Lunaris"] = {
		isMajorGod = true,
		souls = {
			[1] = { name = "月影女神之魂",
				mods = {
					-- physical_damage_reduction_%_per_nearby_enemy
					[1] = { line = "身边每存在 1 个敌人，受到的物理伤害便降低 1%，最多 8%", value = { 1 }, },
					-- movement_speed_+%_per_nearby_enemy
					[2] = { line = "身边每有 1 个敌人，自己的移动速度提高 1%，最多 8%", value = { 1 }, },
				},
			},
			[2] = { name = "新月之纪瑟伯特",
				mods = {
					-- base_avoid_projectiles_%_chance
					[1] = { line = "10% 的几率免疫投射物", value = { 10 }, },
				},
			},
			[3] = { name = "骨法师伯托克",
				mods = {
					-- elemental_damage_taken_+%_if_been_hit_recently
					[1] = { line = "承受的元素伤害在你近期内被击中的情况下降低 6%", value = { -6 }, },
				},
			},
			[4] = { name = "丛林巨石",
				mods = {
					-- avoid_chained_projectile_%_chance
					[1] = { line = "避免被连锁弹射的投射物击中", value = { 100 }, },
				},
			},
		},
	},
	["Minor God 1"] = {
		isMajorGod = false,
		souls = {
		},
	},
	["Minor God 2"] = {
		isMajorGod = false,
		souls = {
		},
	},
	["Abberath"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "割裂者 艾贝拉斯之魂",
				mods = {
					-- pantheon_abberath_ignite_duration_on_self_+%_final
					[1] = { line = "你身上的点燃持续时间总降 60%", value = { -60 }, },
				},
			},
			[2] = { name = "撼地者米福德",
				mods = {
					-- unaffected_by_burning_ground
					[1] = { line = "不受燃烧地面影响", value = { 1 }, },
					-- movement_speed_+%_while_on_burning_ground
					[2] = { line = "在燃烧地面上时，移动速度提高 10%", value = { 10 }, },
				},
			},
		},
	},
	["Minor God 4"] = {
		isMajorGod = false,
		souls = {
		},
	},
	["Gruthkul"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "绝望之母 格鲁丝克之魂",
				mods = {
					-- physical_damage_reduction_%_per_hit_you_have_taken_recently
					[1] = { line = "近期每受到 1 次伤害，下次承受的物理伤害減少 1%，最多 5%", value = { 1 }, },
				},
			},
			[2] = { name = "光明克星阿尔碧斯",
				mods = {
					-- enemies_that_hit_you_with_attack_recently_attack_speed_+%
					[1] = { line = "若近期敌人用攻击击中过你，则它们的攻击速度降低 8%", value = { -8 }, },
				},
			},
		},
	},
	["Yugul"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "恐惧之源 尤格尔之魂",
				mods = {
					-- reflect_damage_taken_and_minion_reflect_damage_taken_+%
					[1] = { line = "你和你的召唤生物受到的反射伤害降低 50%", value = { -50 }, },
					-- reflect_hexes_chance_%
					[2] = { line = "有 50% 的几率反射魔蛊", value = { 50 }, },
				},
			},
			[2] = { name = "苦痛主教",
				mods = {
					-- curse_effect_on_self_+%
					[1] = { line = "你受到的诅咒效果降低 30%", value = { -30 }, },
				},
			},
		},
	},
	["Shakari"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "沙之女神 沙卡丽之魂",
				mods = {
					-- pantheon_shakari_self_poison_duration_+%_final
					[1] = { line = "你身上的总中毒持续时间额外缩短 50%", value = { -50 }, },
					-- cannot_be_poisoned_if_x_poisons_on_you
					[2] = { line = "你身上至少有 3 层中毒状态时，你无法中毒", value = { 3 }, },
				},
			},
			[2] = { name = "不息之影",
				mods = {
					-- chaos_damage_taken_+%
					[1] = { line = "受到的混沌伤害降低 5%", value = { -5 }, },
					-- chaos_damage_taken_over_time_+%_while_in_caustic_cloud
					[2] = { line = "当在腐蚀地面上时，受到的混沌持续伤害降低 25%", value = { -25 }, },
				},
			},
		},
	},
	["Tukohama"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "战争之父 图克哈玛之魂",
				mods = {
					-- while_stationary_gain_additional_physical_damage_reduction_%
					[1] = { line = "物理伤害减免在静止时每秒额外获得 3%，最多可额外获得 9%", value = { 3 }, },
				},
			},
			[2] = { name = "诅咒之王",
				mods = {
					-- life_regeneration_rate_per_minute_%_while_stationary
					[1] = { line = "静止时每秒回复 2% 生命", value = { 120 }, },
				},
			},
		},
	},
	["Minor God 9"] = {
		isMajorGod = false,
		souls = {
		},
	},
	["Ralakesh"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "万面之主 拉克斯之魂",
				mods = {
					-- physical_damage_over_time_taken_+%_while_moving
					[1] = { line = "持续物理伤害在移动时降低 25%", value = { -25 }, },
					-- no_extra_bleed_damage_while_moving
					[2] = { line = "流血状态下移动不再承受额外的伤害", value = { 1 }, },
				},
			},
			[2] = { name = "玫红女妖",
				mods = {
					-- cannot_gain_corrupted_blood_while_you_have_at_least_5_stacks
					[1] = { line = "若你身上至少有 5 层腐化之血，则腐化之血不能再施加给你", value = { 1 }, },
				},
			},
		},
	},
	["Garukhan"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "风暴女神 格鲁坎之魂",
				mods = {
					-- shocked_effect_on_self_+%
					[1] = { line = "你受到的感电效果降低 60%", value = { -60 }, },
				},
			},
			[2] = { name = "瓦瑟瑞斯",
				mods = {
					-- cannot_be_blinded
					[1] = { line = "免疫致盲", value = { 1 }, },
					-- avoid_maim_%_chance
					[2] = { line = "你无法被瘫痪", value = { 100 }, },
				},
			},
		},
	},
	["Ryslatha"] = {
		isMajorGod = false,
		souls = {
			[1] = { name = "傀儡女王 瑞斯拉萨之魂",
				mods = {
					-- life_flasks_gain_X_charges_every_3_seconds_if_you_have_not_used_a_life_flask_recently
					[1] = { line = "若你近期内没使用生命药剂，则生命药剂每 3 秒获得 3 充能", value = { 3 }, },
				},
			},
			[2] = { name = "利希斯啸夜",
				mods = {
					-- life_recovery_+%_from_flasks_while_on_low_life
					[1] = { line = "低血时，使用药剂会提高 60% 生命回复量", value = { 60 }, },
				},
			},
		},
	},
}