-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Spectre Data
-- Monster data (c) Grinding Gear Games
--
local minions, mod = ...

-- Blackguard
minions["Metadata/Monsters/Axis/AxisCaster"] = {
	name = "乌旗守卫法师",
	life = 0.9,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Wand",
	weaponType2 = "Shield",
	skillList = {
		"MeleeUseContactPoint",
		"SkeletonSpark",
		"MonsterLightningThorns",
		"AxisClaimSoldierMinions",
	},
	modList = {
		-- MonsterCastsSparkText [monster_casts_spark_text = 1]
		-- MonsterCastsLightningThornsText [monster_casts_lightning_thorns_text = 1]
		-- MonsterSpellBlock25Bypass30___ [base_spell_block_% = 20] [base_block_%_damage_taken = 10]
	},
	modListSP = {
		"施放电球", 
		"施放闪电反伤盾", 
		"20% 几率格挡法术，被格挡的击中对你造成 10% 伤害", 
	},
}
minions["Metadata/Monsters/Axis/AxisCasterArc"] = {
	name = "乌旗守卫雷使",
	life = 0.9,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Wand",
	weaponType2 = "Shield",
	skillList = {
		"MeleeUseContactPoint",
		"MonsterLightningThorns",
		"AxisCasterArc",
		"AxisClaimSoldierMinions",
	},
	modList = {
		-- MonsterCastsArcText [monster_casts_arc_text = 1]
		-- MonsterCastsLightningThornsText [monster_casts_lightning_thorns_text = 1]
		-- MonsterSpellBlock25Bypass30___ [base_spell_block_% = 20] [base_block_%_damage_taken = 10]
	},
	modListSP = {
		"施放电弧", 
		"施放闪电反伤盾", 
		"20% 几率格挡法术，被格挡的击中对你造成 10% 伤害", 
	},
}
minions["Metadata/Monsters/Axis/AxisEliteSoldier3Champion"] = {
	name = "日耀斗士",
	life = 1.5,
	armour = 0.4,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.12,
	damageSpread = 0.2,
	attackTime = 1.245,
	attackRange = 11,
	accuracy = 1,
	weaponType1 = "Two Handed Sword",
	skillList = {
		"Melee",
		"BreachCleave",
		"AxisDoubleStrikeTrigger",
		"SummonFlamingAnimatedWeapons",
		"SolarisChampionFlameVortex",
	},
	modList = {
		mod("PhysicalDamageGainAsFire", "BASE", 100), -- MonsterPhysicalAddedAsFireSkeletonMaps [physical_damage_%_to_add_as_fire = 100]
	},
	modListSP = {
		"额外火焰伤害", 
	},
}
minions["Metadata/Monsters/Axis/AxisExperimenter"] = {
	name = "生灵实验者",
	life = 0.96,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 75,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Wand",
	skillList = {
		"MeleeUseContactPoint",
		"SkeletonTemporalChains",
		"MonsterDetonateDeadExperimenter",
		"ExperimenterEnrageDemon",
	},
	modList = {
		-- MonsterCastsTemporalChainsText [monster_casts_temporal_chains_text = 1]
		-- MonsterDetonatesCorpsesText [monster_detonates_corpses_text = 1]
	},
	modListSP = {
		"施放时空锁链", 
		"引爆灵柩", 
	},
}
minions["Metadata/Monsters/Axis/AxisExperimenter2"] = {
	name = "躯体雕塑者",
	life = 0.96,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 75,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Wand",
	skillList = {
		"Melee",
		"MonsterEnfeeble",
		"MonsterProjectileWeakness",
		"MonsterDetonateDeadExperimenter",
	},
	modList = {
		-- MonsterDetonatesCorpsesText [monster_detonates_corpses_text = 1]
		-- MonsterCastsEnfeebleCurseText [monster_casts_enfeeble_curse_text = 1]
		-- MonsterCastsProjectileWeaknessCurseText [monster_casts_projectile_vulnerability_curse_text = 1]
	},
	modListSP = {
		"引爆灵柩", 
		"施放衰弱", 
		"施放投射物要害", 
	},
}
minions["Metadata/Monsters/Axis/AxisExperimenterRaiseZombie"] = {
	name = "复生师",
	life = 0.96,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 75,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Wand",
	skillList = {
		"MeleeUseContactPoint",
		"MonsterEnfeeble",
		"NecromancerRaiseZombie",
		"ExperimenterEnrageDemon",
	},
	modList = {
		-- MonsterCastsEnfeebleCurseText [monster_casts_enfeeble_curse_text = 1]
		-- MonsterRaisesZombiesText [monster_raises_zombies_text = 1]
	},
	modListSP = {
		"施放衰弱", 
		"施放魔卫复苏", 
	},
}
-- Bandit
minions["Metadata/Monsters/Bandits/BanditBowExplosiveArrow"] = {
	name = "克雷顿的狙击手",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"BanditExplosiveArrow",
	},
	modList = {
		-- MonsterFiresExplosiveArrowText [monster_fires_explosive_arrows_text = 1]
	},
	modListSP = {
		"爆炸箭矢", 
	},
}
minions["Metadata/Monsters/Bandits/BanditBowPoisonArrow"] = {
	name = "阿莉亚的穿心之弓",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterCausticArrow",
	},
	modList = {
		-- MonsterFiresCausticArrowsText [monster_fires_caustic_arrows_text = 1]
	},
	modListSP = {
		"使用腐蚀箭矢", 
	},
}
minions["Metadata/Monsters/Bandits/BanditMeleeWarlordsMarkMaul"] = {
	name = "欧克的信徒",
	life = 1,
	armour = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.35,
	attackRange = 7,
	accuracy = 1,
	weaponType1 = "Two Handed Mace",
	skillList = {
		"Melee",
		"MonsterWarlordsMark",
	},
	modList = {
		-- MonsterCastsWarlordsMarkCurseText [monster_casts_warlords_mark_curse_text = 1]
	},
	modListSP = {
		"施放督军印记", 
	},
}
-- Beast
minions["Metadata/Monsters/Beasts/BeastCaveDegenAura"] = {
	name = "毒息巨兽",
	life = 2.1,
	armour = 0.6,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.605,
	attackRange = 14,
	accuracy = 1,
	damageFixup = 0.33,
	skillList = {
		"Melee",
		"ChaosDegenAura",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupComplete [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 33]
	},
	modListSP = {
		"怪物速度和伤害调整（完全）", 
	},
}
minions["Metadata/Monsters/Beasts/BeastCleaveEnduringCry"] = {
	name = "长毛碎骨兽",
	life = 2.1,
	armour = 0.6,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.605,
	attackRange = 14,
	accuracy = 1,
	damageFixup = 0.33,
	skillList = {
		"Melee",
		"BeastEnduringCry",
		"BeastCleave",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupComplete [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 33]
		-- MonsterUsesEnduringCryText [monster_uses_enduring_cry_text = 1]
		-- MonsterCleavesText [monster_cleaves_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（完全）", 
		"使用坚决战吼", 
		"使用劈砍", 
	},
}
-- Blood apes
minions["Metadata/Monsters/BloodChieftain/MonkeyChiefBloodEnrage"] = {
	name = "冷血酋长",
	life = 1.5,
	armour = 0.2,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.905,
	attackRange = 7,
	accuracy = 1,
	damageFixup = 0.22,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
		"BloodChieftainSummonMonkeys",
		"MassFrenzy",
		"MonkeyThrow",
		"TriggeredMonkeyBomb",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupLarge [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 22]
		-- MonsterSummonsMonkeysText [monster_summons_monkeys_from_nearby_trees_text = 1]
		-- MonsterCastsMassFrenzyText [monster_casts_mass_frenzy_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（大）", 
		"呼唤树上猿猴", 
		"友军狂暴", 
	},
}
minions["Metadata/Monsters/BloodChieftain/MonkeyChiefBloodParasite"] = {
	name = "宿主酋长",
	life = 1.5,
	armour = 0.2,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.905,
	attackRange = 7,
	accuracy = 1,
	damageFixup = 0.22,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
		"BloodChieftainSummonParasiteMonkeys",
		"MassPower",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupLarge [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 22]
		-- MonsterSummonsMonkeysText [monster_summons_monkeys_from_nearby_trees_text = 1]
		-- MonsterUsesMassPowerText [monster_uses_mass_power_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（大）", 
		"呼唤树上猿猴", 
		"强化周围友军", 
	},
}
-- Bone Stalker
minions["Metadata/Monsters/BoneStalker/BoneStalker"] = {
	name = "骨之史杜克",
	life = 2.1,
	armour = 0.75,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1.12,
	damageSpread = 0.2,
	attackTime = 1.8,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "One Handed Axe",
	skillList = {
		"Melee",
		"BoneStalkerEarthquake",
		"WalkingDoubleSlash",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Bull
minions["Metadata/Monsters/Bull/Bull"] = {
	name = "战斗公牛",
	life = 2.38,
	armour = 1,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.28,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
		"BullCharge",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Cage Spider
minions["Metadata/Monster/CageSpider/CageSpider2"] = {
	name = "恶魔奴隶",
	life = 4.4,
	armour = 0.6,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.28,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 12,
	accuracy = 1,
	skillList = {
		"Melee",
		"CageSpiderCycloneTriggerSandstorms",
		"CageSpiderSandSpark",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Cannibals
minions["Metadata/Monsters/Cannibal/CannibalMaleChampion"] = {
	name = "食人族拥护者",
	life = 1.44,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 10,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
		"MonsterFlameRedCannibal",
	},
	modList = {
		-- StanceScavengerRun [stance_movement_speed_+%_final = 100]
	},
	modListSP = {
	},
}
-- Goatmen
minions["Metadata/Monsters/Goatman/GoatmanLeapSlam"] = {
	name = "羊人",
	life = 1,
	armour = 0.15,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.455,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"GoatmanLeapSlam",
		"Melee",
		"GoatmanWait",
		"GoatmanWait2",
	},
	modList = {
		-- MonsterLeapsOntoEnemiesText [monster_leaps_onto_enemies_text = 1]
	},
	modListSP = {
		"跃击", 
	},
}
minions["Metadata/Monsters/Goatman/GoatmanLightningLeapSlamMaps"] = {
	name = "长须羊人",
	life = 1,
	armour = 0.15,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.8,
	damageSpread = 0.2,
	attackTime = 1.455,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"MonsterLeapSlam",
		"Melee",
		"GoatmanWait",
		"GoatmanWait2",
	},
	modList = {
		mod("PhysicalDamageGainAsLightning", "BASE", 100), -- MonsterPhysicalAddedAsLightningSkeletonMaps [physical_damage_%_to_add_as_lightning = 100]
		-- MonsterLeapsOntoEnemiesText [monster_leaps_onto_enemies_text = 1]
	},
	modListSP = {
		"额外闪电伤害", 
		"跃击", 
	},
}
minions["Metadata/Monsters/Goatman/GoatmanShamanFireball"] = {
	name = "羊人术师",
	life = 1,
	energyShield = 0.2,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	weaponType1 = "Staff",
	skillList = {
		"MonsterFireball",
		"GoatmanMoltenShell",
		"Melee",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		mod("Speed", "INC", -50, ModFlag.Cast), -- MonsterGoatmanShamanCastSpeed [base_cast_speed_+% = -50]
		-- MonsterCastsFireballText [monster_casts_fireball_text = 1]
		-- MonsterCastsMoltenShellText [monster_casts_molten_shell_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"羊人怪物施法速度调整", 
		"施放火球", 
		"施放熔岩护盾", 
	},
}
minions["Metadata/Monsters/Goatman/GoatmanShamanFireChampion"] = {
	name = "羊人炎咒师",
	life = 1.4,
	energyShield = 0.2,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	weaponType1 = "Staff",
	skillList = {
		"MonsterFireball",
		"GoatmanMoltenShell",
		"GoatmanFireMagmaOrb",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		mod("Speed", "INC", -50, ModFlag.Cast), -- MonsterGoatmanShamanCastSpeed [base_cast_speed_+% = -50]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"羊人怪物施法速度调整", 
	},
}
minions["Metadata/Monsters/Goatman/GoatmanShamanLightning"] = {
	name = "长须术师",
	life = 1,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	weaponType1 = "Staff",
	skillList = {
		"Melee",
		"MonsterShockNova",
		"MonsterSpark",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		mod("Speed", "INC", -50, ModFlag.Cast), -- MonsterGoatmanShamanCastSpeed [base_cast_speed_+% = -50]
		-- MonsterCastsShockNovaText [monster_casts_shock_nova_text = 1]
		-- MonsterCastsSparkText [monster_casts_spark_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"羊人怪物施法速度调整", 
		"施放闪电新星", 
		"施放电球", 
	},
}
minions["Metadata/Monsters/Goatman/MountainGoatmanChampion"] = {
	name = "巨大羊魔",
	life = 2.1,
	armour = 0.15,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.28,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	damageFixup = 0.11,
	weaponType1 = "Two Handed Mace",
	skillList = {
		"Melee",
		"GoatmanEarthquake",
		"GoatmanMonsterSlam",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
	},
}
minions["Metadata/Monsters/Goatman/MountainGoatmanShamanIceSpear"] = {
	name = "羊人萨满",
	life = 1,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	weaponType1 = "Staff",
	skillList = {
		"MountainGoatmanIceSpear",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		mod("Speed", "INC", -50, ModFlag.Cast), -- MonsterGoatmanShamanCastSpeed [base_cast_speed_+% = -50]
		-- MonsterCastsIceSpearText [monster_casts_ice_spear_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"羊人怪物施法速度调整", 
		"施放冰矛", 
	},
}
-- Miscreation
minions["Metadata/Monsters/DemonFemale/DemonFemale"] = {
	name = "古灵实验者: 长鞭",
	life = 0.99,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.88,
	damageSpread = 0.2,
	attackTime = 2.445,
	attackRange = 18,
	accuracy = 1,
	skillList = {
		"Melee",
		"MeleeDemonFemale",
	},
	modList = {
		-- MonsterChanceToVulnerabilityOnHit2 [curse_on_hit_%_vulnerability = 50]
	},
	modListSP = {
		"击中时有一定概率造成脆弱", 
	},
}
minions["Metadata/Monsters/DemonModular/DemonFemaleRanged"] = {
	name = "古灵实验者: 扫荡者",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.84,
	damageSpread = 0.2,
	attackTime = 3,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"DemonFemaleRangedGeometryProjectileLeft",
		"DemonFemaleRangedGeometryProjectileRight",
		"EmptyActionFemaleDemonProjectiles",
		"DemonFemaleRangedGeometryProjectileLeftAhead",
		"DemonFemaleRangedGeometryProjectileRightAhead",
		"EmptyActionFemaleDemonProjectilesAhead",
	},
	modList = {
		mod("PhysicalDamageConvertToFire", "BASE", 50), -- MonsterConvertToFireDamage2 [base_physical_damage_%_to_convert_to_fire = 50]
		-- MonsterRangeVarianceMedium [main_hand_base_maximum_attack_distance = 0]
	},
	modListSP = {
		"造成火焰伤害", 
		"主手攻击距离调整（中）", 
	},
}
minions["Metadata/Monsters/DemonModular/DemonModularBladeVortex"] = {
	name = "派蒂的古灵实验者",
	life = 1.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"Melee",
		"DemonModularBladeVortex",
		"DemonModularBladeVortexSpectre",
	},
	modList = {
	},
	modListSP = {
	},
}
minions["Metadata/Monsters/DemonModular/DemonModularFire"] = {
	name = "古灵实验者: 烈火",
	life = 1,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterRighteousFire",
		"MonsterRighteousFireWhileSpectred",
		"ModularDemonFireSuicideExplosion",
	},
	modList = {
		-- MonsterCastsUnholyFireText [monster_casts_unholy_fire_text = 1]
	},
	modListSP = {
		"施放邪恶之火", 
	},
}
-- Maw
minions["Metadata/Monsters/Frog/Frog"] = {
	name = "恶臭裂齿兽",
	life = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.455,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"MonsterLeapSlam",
		"Melee",
	},
	modList = {
		-- MonsterLeapsOntoEnemiesText [monster_leaps_onto_enemies_text = 1]
	},
	modListSP = {
		"跃击", 
	},
}
minions["Metadata/Monsters/Frog/Frog2"] = {
	name = "阴暗之兽",
	life = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.455,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"MonsterLeapSlam",
		"Melee",
	},
	modList = {
		-- MonsterLeapsOntoEnemiesText [monster_leaps_onto_enemies_text = 1]
	},
	modListSP = {
		"跃击", 
	},
}
-- Chimeral
minions["Metadata/Monsters/GemMonster/Iguana"] = {
	name = "彩羽龙蜥",
	life = 1.25,
	energyShield = 0.2,
	fireResist = 52,
	coldResist = 52,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.12,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"IguanaProjectile",
		"Melee",
	},
	modList = {
		-- MonsterSuppressingFire [chance_to_apply_suppression_on_hit_% = 20]
		-- DisplayMonsterSuppressingFire [display_monster_uses_suppressing_fire_text = 1]
	},
	modListSP = {
		"击中几率释放火力压制", 
		"火力压制", 
	},
}
-- Ghost pirate
minions["Metadata/Monsters/GhostPirates/GhostPirateBlackBowMaps"] = {
	name = "怨灵弓手",
	life = 0.96,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.48,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterPuncture",
	},
	modList = {
		mod("PhysicalDamageGainAsLightning", "BASE", 100), -- MonsterPhysicalAddedAsLightningSkeletonMaps [physical_damage_%_to_add_as_lightning = 100]
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"额外闪电伤害", 
		"施放放血", 
	},
}
minions["Metadata/Monsters/GhostPirates/GhostPirateBlackFlickerStrikeMaps"] = {
	name = "水手咒灵",
	life = 1,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.8,
	damageSpread = 0.2,
	attackTime = 1.65,
	attackRange = 8,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	weaponType2 = "Shield",
	skillList = {
		"Melee",
		"MonsterFlickerStrikeExtraRange",
	},
	modList = {
		mod("PhysicalDamageGainAsLightning", "BASE", 100), -- MonsterPhysicalAddedAsLightningSkeletonMaps [physical_damage_%_to_add_as_lightning = 100]
		-- MonsterUsesFlickerStrikeText [monster_uses_flicker_strike_text = 1]
		-- MonsterAttackSpellBlock20Bypass40 [monster_base_block_% = 20] [base_spell_block_% = 20] [base_block_%_damage_taken = 40]
	},
	modListSP = {
		"额外闪电伤害", 
		"使用闪现打击", 
		"格挡攻击和法术", 
	},
}
minions["Metadata/Monsters/GhostPirates/GhostPirateGreenBladeVortex"] = {
	name = "恶棍怨灵",
	life = 1.5,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.65,
	attackRange = 8,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	weaponType2 = "Shield",
	skillList = {
		"Melee",
		"GhostPirateBladeVortex",
		"GhostPirateBladeVortexSpectre",
	},
	modList = {
		mod("PhysicalDamageConvertToLightning", "BASE", 50), -- MonsterElementalSkeletonLightning [base_physical_damage_%_to_convert_to_lightning = 50]
		-- MonsterAttackSpellBlock20Bypass40 [monster_base_block_% = 20] [base_spell_block_% = 20] [base_block_%_damage_taken = 40]
	},
	modListSP = {
		"造成闪电伤害", 
		"格挡攻击和法术", 
	},
}
-- Undying grappler
minions["Metadata/Monsters/Grappler/Grappler"] = {
	name = "不朽格斗者",
	life = 1,
	armour = 0.3,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.245,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterFlickerStrike",
		"MonsterDischarge",
	},
	modList = {
		-- MonsterGainsPowerChargeOnKinDeath [monster_gain_power_charge_on_kin_death = 1]
		-- MonsterUsesFlickerStrikeText [monster_uses_flicker_strike_text = 1]
		-- MonsterCastsDischargeText [monster_casts_discharge_text = 1]
	},
	modListSP = {
		"同伴被杀时强化", 
		"使用闪现打击", 
		"施放解放", 
	},
}
minions["Metadata/Monsters/Grappler/GrapplerLabyrinth"] = {
	name = "阴影潜伏者",
	life = 1,
	armour = 0.3,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.245,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterFlickerStrike",
		"MonsterDischarge",
	},
	modList = {
		-- MonsterGainsPowerChargeOnKinDeath [monster_gain_power_charge_on_kin_death = 1]
		-- MonsterUsesFlickerStrikeText [monster_uses_flicker_strike_text = 1]
		-- MonsterCastsDischargeText [monster_casts_discharge_text = 1]
	},
	modListSP = {
		"同伴被杀时强化", 
		"使用闪现打击", 
		"施放解放", 
	},
}
-- Ribbon
minions["Metadata/Monsters/Guardians/GuardianFire"] = {
	name = "火炎哨带",
	life = 1.8,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"MonsterMultiFireball",
		"MonsterSplitFireball",
		"MonsterLesserMultiFireball",
		"MonsterMultiFireballSpectre",
		"MonsterSplitFireballSpectre",
		"MonsterLesserMultiFireballSpectre",
	},
	modList = {
		-- MonsterCastsAugmentedFireballsText [monster_casts_augmented_fireballs_text = 1]
	},
	modListSP = {
		"施放强化火球", 
	},
}
minions["Metadata/Monsters/Guardians/GuardianFire_BlueMaps"] = {
	name = "寒霜哨带",
	life = 1.8,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"MonsterMultiIceSpear",
		"MonsterSplitIceSpear",
		"MonsterLesserMultiIceSpear",
	},
	modList = {
	},
	modListSP = {
	},
}
minions["Metadata/Monsters/Guardians/GuardianLightning"] = {
	name = "雷电之带",
	life = 1.8,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 85,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"GuardianArc",
	},
	modList = {
		-- MonsterChannelsLightningText [monster_channels_lightning_text = 1]
	},
	modListSP = {
		"闪电通道", 
	},
}
-- Gut flayer
minions["Metadata/Monsters/HalfSkeleton/HalfSkeleton"] = {
	name = "裂脏剥皮刃",
	life = 1.32,
	armour = 0.5,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.1,
	damageSpread = 0.3,
	attackTime = 1.5,
	attackRange = 10,
	accuracy = 1,
	weaponType1 = "Dagger",
	skillList = {
		"Melee",
		"HalfSkeletonPuncture",
	},
	modList = {
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"施放放血", 
	},
}
-- Solar Guard
minions["Metadata/Monsters/HolyFireElemental/HolyFireElementalSolarisBeam"] = {
	name = "太阳军卫",
	life = 1.98,
	energyShield = 0.1,
	armour = 0.25,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.12,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"SpecialBeamCannon",
		"HolyFireElementalFireball",
	},
	modList = {
		mod("PhysicalDamageGainAsFire", "BASE", 60), -- MonsterPhysicalAddedAsFireHolyFireElemental [physical_damage_%_to_add_as_fire = 60]
	},
	modListSP = {
		"额外火焰伤害", 
	},
}
-- Construct
minions["Metadata/Monsters/incaminion/Fragment"] = {
	name = "远古创造物",
	life = 0.7,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 40,
	damage = 0.84,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 25,
	accuracy = 1,
	skillList = {
		"IncaMinionProjectile",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Carrion queen
minions["Metadata/Monsters/InsectSpawner/InsectSpawner"] = {
	name = "食腐虫后",
	life = 2.45,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.56,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"InsectSpawnerSpit",
		"InsectSpawnerSpawn",
	},
	modList = {
		mod("PhysicalDamageConvertToFire", "BASE", 50), -- MonsterConvertToFireDamage2 [base_physical_damage_%_to_convert_to_fire = 50]
	},
	modListSP = {
		"造成火焰伤害", 
	},
}
-- Kaom's Warriors
minions["Metadata/Monsters/KaomWarrior/KaomWarrior2"] = {
	name = "卡鲁族勇士",
	life = 1.43,
	armour = 0.5,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.16,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"KaomWarriorMoltenStrike",
	},
	modList = {
	},
	modListSP = {
	},
}
minions["Metadata/Monsters/KaomWarrior/KaomWarrior3"] = {
	name = "卡鲁族勇士",
	life = 1.43,
	armour = 0.5,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.16,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"Melee",
		"KaomWarriorGroundSlam",
	},
	modList = {
	},
	modListSP = {
	},
}
minions["Metadata/Monsters/KaomWarrior/KaomWarrior7"] = {
	name = "拉维安加的侍祭（图腾）",
	life = 1.43,
	armour = 0.5,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.16,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"Melee",
		"KaomFireBeamTotem",
		"KaomFireBeamTotemSpectre",
	},
	modList = {
		-- KaomWarriorSlowFireBeam [fire_beam_max_rotation_speed_+% = -75] [fire_beam_start_angle_offset_variance = 60] [base_totem_range = 80] [fire_beam_length_+% = -25]
		mod("TotemLife", "INC", 250), -- KaomWarriorSlowFireBeam2 [totem_life_+% = 250]
		-- MonsterKillTrapsMinesTotemsOnDeath [kill_traps_mines_and_totems_on_death = 1]
	},
	modListSP = {
		"慢速火焰光线", 
		"图腾生命提升", 
		"死亡时取消施放的图腾陷阱和地雷", 
	},
}
-- Kitava's Cultist
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearBloodDelve"] = {
	name = "复活的瓦尔虔信者",
	life = 2.88,
	armour = 0.2,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"VaalincursionMortar",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearBloodChampionDelve"] = {
	name = "复活的瓦尔拥护者",
	life = 4.05,
	armour = 0.2,
	fireResist = 35,
	coldResist = 35,
	lightningResist = 35,
	chaosResist = 20,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"VaalincursionMortar",
		"VaalIncursionSpecialBeamCannonBlood",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearChaosDelve"] = {
	name = "复活的瓦尔虔信者",
	life = 2.88,
	armour = 0.2,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"FireballIncursionChaos",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearChaosChampionDelve"] = {
	name = "复活的瓦尔拥护者",
	life = 4.05,
	armour = 0.2,
	fireResist = 35,
	coldResist = 35,
	lightningResist = 35,
	chaosResist = 20,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"FireballIncursionChaos",
		"IncursionSummonPhantasms",
		"IncursionMeteorUpheaval",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearFireDelve"] = {
	name = "复活的瓦尔虔信者",
	life = 2.88,
	armour = 0.2,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"FireballIncusionFire",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearFireChampionDelve_"] = {
	name = "复活的瓦尔拥护者",
	life = 4.05,
	armour = 0.2,
	fireResist = 35,
	coldResist = 35,
	lightningResist = 35,
	chaosResist = 20,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"FireballIncusionFire",
		"VaalIncursionFirestorm",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearLightningDelve"] = {
	name = "复活的瓦尔虔信者",
	life = 2.88,
	armour = 0.2,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"FireballIncusionLightning",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
minions["Metadata/Monsters/KitavaCultist/VaalCultistSpearLightningChampionDelve_"] = {
	name = "复活的瓦尔拥护者",
	life = 4.05,
	armour = 0.2,
	fireResist = 35,
	coldResist = 35,
	lightningResist = 35,
	chaosResist = 20,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"FireballIncusionLightning",
		"DelayedLightningSpark",
		"SummonedSparkDaemonLightning",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
-- Kitava's Herald
minions["Metadata/Monster/KitavaDemon/KitavaDemon"] = {
	name = "奇塔弗的信使",
	life = 3.6,
	armour = 0.6,
	fireResist = 37,
	coldResist = 37,
	lightningResist = 37,
	chaosResist = 0,
	damage = 1.4,
	damageSpread = 0.2,
	attackTime = 1.455,
	attackRange = 10,
	accuracy = 1,
	damageFixup = 0.33,
	weaponType1 = "One Handed Sword",
	skillList = {
		"KitavaDemonLeapSlam",
		"KitavaDemonCleave",
		"KitavaDemonWhirlingBlades",
		"KitavaDemonXMortar",
		"Melee",
	},
	modList = {
		-- MonsterInflictsBleedingText [display_monster_may_inflict_bleeding = 1]
		-- MonsterSpeedAndDamageFixupComplete [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 33]
	},
	modListSP = {
		"一定几率造成流血", 
		"怪物速度和伤害调整（完全）", 
	},
}
-- Birdman
minions["Metadata/Monsters/Kiweth/Kiweth"] = {
	name = "丛林反刍鸟",
	life = 1.54,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.68,
	damageSpread = 0.2,
	attackTime = 1.11,
	attackRange = 11,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"Melee",
		"BirdmanConsumeCorpse",
		"BirdmanBloodProjectile",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		-- MonsterLesserFarShot [monster_reverse_point_blank_damage_-%_at_minimum_range = 60] [projectile_damage_+% = 20] [display_monster_uses_far_shot_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"远射", 
	},
}
minions["Metadata/Monsters/Kiweth/KiwethSeagull"] = {
	name = "狂食反刍鸟",
	life = 1.3,
	energyShield = 0.12,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.56,
	damageSpread = 0.2,
	attackTime = 1.11,
	attackRange = 11,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"Melee",
		"BirdmanConsumeCorpse",
		"BirdmanBloodProjectile",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		-- MonsterLesserFarShot [monster_reverse_point_blank_damage_-%_at_minimum_range = 60] [projectile_damage_+% = 20] [display_monster_uses_far_shot_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"远射", 
	},
}
-- Delve League
minions["Metadata/Monsters/LeagueDelve/ProtoVaalWarriorElite"] = {
	name = "石肤剥皮者",
	life = 8,
	armour = 1,
	fireResist = 35,
	coldResist = 35,
	lightningResist = 35,
	chaosResist = 20,
	damage = 1.34,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 12,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	weaponType2 = "One Handed Sword",
	skillList = {
		"Melee",
		"DelveProtovaalWhirlingCharge",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
	},
}
-- Hellion
minions["Metadata/Monsters/Lion/LionDesertSkinPuncture"] = {
	name = "沙丘地狱犬",
	life = 1,
	armour = 0.1,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 10,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterPuncture",
	},
	modList = {
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"施放放血", 
	},
}
-- Knitted horror
minions["Metadata/Monsters/MassSkeleton/MassSkeleton"] = {
	name = "恐惧创造物",
	life = 2.25,
	armour = 0.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.98,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 11,
	accuracy = 1,
	skillList = {
		"Melee",
		"SkeletonMassBowProjectile",
	},
	modList = {
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"施放放血", 
	},
}
-- Miners
minions["Metadata/Monsters/Miner/MinerLantern"] = {
	name = "疮痕持灯者",
	life = 1.21,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.21,
	damageSpread = 0.2,
	attackTime = 1.395,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"MinerThrowFire",
		"MinerThrowFireSpectre",
	},
	modList = {
		-- IgniteArtVariation [ignite_art_variation = 1]
	},
	modListSP = {
		"特殊特效版本点燃", 
	},
}
minions["Metadata/Monsters/Miner/MinerLanternCrystalVeins"] = {
	name = "疮痕照明者",
	life = 1.21,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.21,
	damageSpread = 0.2,
	attackTime = 1.395,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"MinerThrowFire",
		"MinerThrowFireSpectre",
	},
	modList = {
		-- IgniteArtVariation [ignite_art_variation = 1]
	},
	modListSP = {
		"特殊特效版本点燃", 
	},
}
-- Voidbearer
minions["Metadata/Monsters/Monkeys/FlameBearer"] = {
	name = "虚影炎兽",
	life = 1.1,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"Melee",
		"FlamebearerFlameBlue",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Stone golem
minions["Metadata/Monsters/MossMonster/FireMonster"] = {
	name = "炽炎魔像",
	life = 2.7,
	armour = 0.5,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.695,
	attackRange = 7,
	accuracy = 1,
	damageFixup = 0.33,
	skillList = {
		"Melee",
		"FireMonsterWhirlingBlades",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupComplete [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 33]
		-- MonsterRollsOverEnemiesText [display_monster_uses_whirling_blades_text = 1]
		-- ImmuneToLavaDamage [immune_to_lava_damage = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（完全）", 
		"使用回旋之刃", 
		"免疫熔岩伤害", 
	},
}
-- Mother of Flames
minions["Metadata/Monsters/MotherOfFlames/MotherOfFlamesZombie"] = {
	name = "不死火焰",
	life = 0.9,
	energyShield = 0.28,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.25,
	damageSpread = 0.2,
	attackTime = 1.8,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"MotherOfFlamesMagmaOrb3",
		"Melee",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Necromancer
minions["Metadata/Monsters/Necromancer/NecromancerConductivity"] = {
	name = "恶咒之主",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerConductivity",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
		-- MonsterCastsConductivityText [monster_casts_conductivity_text = 1]
	},
	modListSP = {
		"复活不死生物", 
		"怪物诅咒施法速度惩罚", 
		"施放导电", 
	},
}
minions["Metadata/Monsters/Necromancer/NecromancerEnfeebleCurse"] = {
	name = "恶魔咒师",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerEnfeeble",
		"AddBuffToTargetNecromancer",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		-- MonsterCastsEnfeebleCurseText [monster_casts_enfeeble_curse_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
	},
	modListSP = {
		"复活不死生物", 
		"施放衰弱", 
		"怪物诅咒施法速度惩罚", 
	},
}
minions["Metadata/Monsters/Necromancer/NecromancerFlamability"] = {
	name = "烈火咒师",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerFlammability",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		-- MonsterCastsFlammabilityText [monster_casts_flammability_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
		-- ImmuneToLavaDamage [immune_to_lava_damage = 1]
	},
	modListSP = {
		"复活不死生物", 
		"施放易燃", 
		"怪物诅咒施法速度惩罚", 
		"免疫熔岩伤害", 
	},
}
minions["Metadata/Monsters/Necromancer/NecromancerFrostbite"] = {
	name = "死亡咒师",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerFrostbite",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
		-- MonsterCastsFrostbiteText [display_monster_casts_frostbite_text = 1]
	},
	modListSP = {
		"复活不死生物", 
		"怪物诅咒施法速度惩罚", 
		"施放冻伤", 
	},
}
minions["Metadata/Monsters/Necromancer/NecromancerElementalWeakness"] = {
	name = "玷污咒师",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerElementalWeakness",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		-- MonsterCastsElementralWeaknessCurseText [monster_casts_elementral_weakness_curse_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
	},
	modListSP = {
		"复活不死生物", 
		"施放元素要害", 
		"怪物诅咒施法速度惩罚", 
	},
}
minions["Metadata/Monsters/Necromancer/NecromancerProjectileWeakness"] = {
	name = "死灵法师",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerEnfeeble",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
		-- MonsterCastsEnfeebleCurseText [monster_casts_enfeeble_curse_text = 1]
	},
	modListSP = {
		"复活不死生物", 
		"怪物诅咒施法速度惩罚", 
		"施放衰弱", 
	},
}
minions["Metadata/Monsters/Necromancer/NecromancerVulnerability"] = {
	name = "死灵法师",
	life = 2.4,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"NecromancerReviveSkeleton",
		"NecromancerVulnerability",
	},
	modList = {
		-- MonsterRaisesUndeadText [monster_raises_undead_text = 1]
		mod("Speed", "INC", -80, ModFlag.Cast, KeywordFlag.Curse), -- MonsterCurseCastSpeedPenalty [curse_cast_speed_+% = -80]
		-- MonsterCastsVulnerabilityCurseText [monster_casts_vulnerability_curse_text = 1]
	},
	modListSP = {
		"复活不死生物", 
		"怪物诅咒施法速度惩罚", 
		"施放脆弱", 
	},
}
-- Undying bomber
minions["Metadata/Monsters/Pyromaniac/PyromaniacFire"] = {
	name = "不朽之炎",
	life = 1,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"PyroFireball",
		"PyroSuicideExplosion",
		"MonsterFireBomb",
	},
	modList = {
		-- MonsterThrowsFireBombsText [monster_throws_fire_bombs_text = 1]
		-- MonsterExplodesOnItsTargetOnLowLifeText [monster_explodes_on_its_target_text = 2]
		-- ImmuneToLavaDamage [immune_to_lava_damage = 1]
	},
	modListSP = {
		"投掷火焰炸弹", 
		"低血时自爆", 
		"免疫熔岩伤害", 
	},
}
minions["Metadata/Monsters/Pyromaniac/PyromaniacPoison"] = {
	name = "不朽之毒",
	life = 1,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterCausticBomb",
		"PyroChaosFireball",
	},
	modList = {
		-- MonsterThrowsPoisonBombsText [monster_throws_caustic_bombs_text = 1]
	},
	modListSP = {
		"投掷腐蚀炸弹", 
	},
}
-- Stygian revenant
minions["Metadata/Monsters/Revenant/Revenant"] = {
	name = "幽灵亡魂",
	life = 1.82,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1.4,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 10,
	accuracy = 1,
	skillList = {
		"RevenantReviveUndead",
		"RevenantSpellProjectile",
		"Melee",
		"RevenantSpellProjectileSpectre",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Sea witch
minions["Metadata/Monsters/Seawitch/SeaWitchFrostBolt"] = {
	name = "莫薇儿的宠儿",
	life = 1.44,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.02,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"SeaWitchWave",
		"Melee",
		"SeawitchFrostbolt",
		"SeawitchWaveGeometrySpell",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
	},
}
minions["Metadata/Monsters/Seawitch/SeaWitchScreech"] = {
	name = "冥曲海妖",
	life = 1.02,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.02,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"SeaWitchWave",
		"Melee",
		"SeaWitchScreech",
		"SeawitchWaveGeometrySpell",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
	},
}
minions["Metadata/Monsters/Seawitch/SeaWitchSpawnExploding"] = {
	name = "莫薇儿的侍女",
	life = 1.02,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.02,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"SeaWitchWave",
		"Melee",
		"SummonExplodingSpawn",
		"SeaWitchScreech",
		"SeawitchWaveGeometrySpell",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		-- MonsterSummonsExplodingSpawnText [monster_summons_exploding_spawn_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"召唤自爆仆从", 
	},
}
minions["Metadata/Monsters/Seawitch/SeaWitchSpawnTemporalChains"] = {
	name = "海妖爱女",
	life = 1.02,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.02,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"SeaWitchWave",
		"Melee",
		"SkeletonTemporalChains",
		"SummonSpawn",
		"SeawitchWaveGeometrySpell",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		-- MonsterSummonsSpawnText [monster_summons_spawn_text = 1]
		-- MonsterCastsTemporalChainsText [monster_casts_temporal_chains_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"召唤仆从", 
		"施放时空锁链", 
	},
}
minions["Metadata/Monsters/Seawitch/SeaWitchVulnerabilityCurse"] = {
	name = "海妖家臣",
	life = 1.02,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.02,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	skillList = {
		"SeaWitchWave",
		"Melee",
		"SkeletonVulnerability",
		"SeawitchWaveGeometrySpell",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		-- MonsterCastsVulnerabilityCurseText [monster_casts_vulnerability_curse_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"施放脆弱", 
	},
}
-- Skeleton
minions["Metadata/Monsters/Skeletons/SkeletonBowPuncture"] = {
	name = "嗜血枯骨",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterPuncture",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"施放放血", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowLightning"] = {
	name = "盗猎者残骨",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterLightningArrow",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterFiresLightningArrowsText [monster_fires_lightning_arrows_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"闪电箭矢", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonMeleeLarge"] = {
	name = "巨型骸骨斗士",
	life = 1.98,
	armour = 0.8,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.8,
	damageSpread = 0.2,
	attackTime = 2.25,
	attackRange = 9,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
	},
	modListSP = {
		"亡灵生物", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowLightning3"] = {
	name = "悲语之弦",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterLightningArrow",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterFiresLightningArrowsText [monster_fires_lightning_arrows_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"闪电箭矢", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonCasterColdMultipleProjectiles"] = {
	name = "冰霜先锋",
	life = 0.84,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.605,
	attackRange = 46,
	accuracy = 1,
	skillList = {
		"SkeletonProjectileCold",
	},
	modList = {
		mod("ProjectileCount", "BASE", 2), -- MonsterMultipleProjectilesImplicit1 [number_of_additional_projectiles = 2]
		-- MonsterNecromancerRaisable [undead_description = 1]
	},
	modListSP = {
		"发射额外投射物", 
		"亡灵生物", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonCasterFireMultipleProjectiles2"] = {
	name = "狂炎术者",
	life = 0.84,
	energyShield = 0.4,
	armour = 0.15,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.605,
	attackRange = 46,
	accuracy = 1,
	skillList = {
		"SkeletonProjectileFire",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		mod("ProjectileCount", "BASE", 2), -- MonsterMultipleProjectilesImplicit1 [number_of_additional_projectiles = 2]
		-- ImmuneToLavaDamage [immune_to_lava_damage = 1]
	},
	modListSP = {
		"亡灵生物", 
		"发射额外投射物", 
		"免疫熔岩伤害", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowPoison"] = {
	name = "瘟疫弓手",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterCausticArrow",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterFiresCausticArrowsText [monster_fires_caustic_arrows_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"使用腐蚀箭矢", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowLightning2"] = {
	name = "不灭之弦",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterLightningArrow",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterFiresLightningArrowsText [monster_fires_lightning_arrows_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"闪电箭矢", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowLightning4"] = {
	name = "罪恶之弓",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterLightningArrow",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterFiresLightningArrowsText [monster_fires_lightning_arrows_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"闪电箭矢", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonCasterLightningSpark"] = {
	name = "雷能枯灵",
	life = 0.84,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.605,
	attackRange = 46,
	accuracy = 1,
	skillList = {
		"SkeletonProjectileLightning",
		"SkeletonSpark",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterCastsSparkText [monster_casts_spark_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"施放电球", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowProjectileWeaknessCurse"] = {
	name = "咒灵射手",
	life = 0.96,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"MonsterProjectileWeakness",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
		-- MonsterCastsProjectileWeaknessCurseText [monster_casts_projectile_vulnerability_curse_text = 1]
	},
	modListSP = {
		"亡灵生物", 
		"施放投射物要害", 
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonMeleeKnightElementalSwordIncursionChampion"] = {
	name = "强大的瓦尔堕灵",
	life = 2.25,
	armour = 1,
	fireResist = 35,
	coldResist = 35,
	lightningResist = 35,
	chaosResist = 20,
	damage = 1.5,
	damageSpread = 0.3,
	attackTime = 1.605,
	attackRange = 9,
	accuracy = 1,
	weaponType1 = "Two Handed Sword",
	skillList = {
		"Melee",
		"ElementalHitSkeletonKnightIncursion",
		"IncursionLeapSlamChampion",
	},
	modList = {
		-- MonsterCastsElementalHitText [monster_casts_elemental_hit_text = 1]
		-- MonsterIncursionDropModifiers__ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 35] [monster_dropped_item_rarity_+% = 2500] [monster_no_map_drops = 1]
	},
	modListSP = {
	},
}
minions["Metadata/Monsters/Skeletons/SkeletonBowKnightElemental"] = {
	name = "瓦尔穿魂之弦",
	life = 0.96,
	fireResist = 37,
	coldResist = 37,
	lightningResist = 37,
	chaosResist = 0,
	damage = 0.6,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"ElementalHitSkeletonKnight",
	},
	modList = {
		-- MonsterCastsElementalHitText [monster_casts_elemental_hit_text = 1]
	},
	modListSP = {
		"击中造成点燃、冰冻、冰缓或感电效果", 
	},
}
minions["Metadata/Monsters/SkeletonCannon/SkeletonCannon1"] = {
	name = "骨壳",
	life = 2.07,
	armour = 0.25,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.8,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"SkeletonCannonMortar",
		"SkeletonCannonBoneMortar",
		"SkeletonCannonBoneNova",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
	},
	modListSP = {
		"亡灵生物", 
	},
}
-- Snake
minions["Metadata/Monsters/Snake/SnakeMeleeSpit"] = {
	name = "丛林眼镜蛇",
	life = 0.8,
	armour = 0.15,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 30,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.65,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"SnakeProjectile",
	},
	modList = {
		mod("PhysicalDamageConvertToChaos", "BASE", 30), -- MonsterSnakeChaos [base_physical_damage_%_to_convert_to_chaos = 30]
	},
	modListSP = {
		"造成混沌伤害", 
	},
}
minions["Metadata/Monsters/Snake/SnakeScorpionMultiShot"] = {
	name = "棘刺巨蛇",
	life = 0.94,
	armour = 0.15,
	fireResist = 30,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 30,
	damage = 0.75,
	damageSpread = 0.2,
	attackTime = 1.65,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"SnakeSpineProjectile",
	},
	modList = {
		mod("PhysicalDamageConvertToChaos", "BASE", 30), -- MonsterSnakeChaos [base_physical_damage_%_to_convert_to_chaos = 30]
		mod("ProjectileCount", "BASE", 2), -- MonsterMultipleProjectilesImplicit1 [number_of_additional_projectiles = 2]
	},
	modListSP = {
		"造成混沌伤害", 
		"发射额外投射物", 
	},
}
-- Spider
minions["Metadata/Monsters/Spiders/SpiderThornFlickerStrike"] = {
	name = "跃影巨蛛",
	life = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.44,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterFlickerStrike",
	},
	modList = {
		-- MonsterUsesFlickerStrikeText [monster_uses_flicker_strike_text = 1]
	},
	modListSP = {
		"使用闪现打击", 
	},
}
-- Statue
minions["Metadata/Monsters/Statue/DaressoStatueLargeMaleSpear"] = {
	name = "巨型创造物",
	life = 5.76,
	armour = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.3,
	damageSpread = 0.2,
	attackTime = 1.875,
	attackRange = 16,
	accuracy = 1,
	damageFixup = 0.33,
	weaponType1 = "One Handed Sword",
	skillList = {
		"Melee",
		"MonsterPuncture",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupComplete [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 33]
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（完全）", 
		"施放放血", 
	},
}
-- Ophidian
minions["Metadata/Monsters/Taster/Taster"] = {
	name = "审阅者",
	life = 1,
	armour = 0.2,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 6,
	accuracy = 1,
	weaponType1 = "Dagger",
	skillList = {
		"Melee",
		"TarMortarTaster",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Templar
minions["Metadata/Monsters/TemplarSlaveDriver/TemplarSlaveDriver"] = {
	name = "驱刑者",
	life = 1,
	armour = 0.25,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.845,
	attackRange = 8,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	weaponType2 = "One Handed Mace",
	skillList = {
		"SlaverTaunt",
		"Melee",
		"SlavedriverFlameWhip",
	},
	modList = {
		-- MonsterImplicitFastRun4 [base_movement_velocity_+% = 20]
	},
	modListSP = {
	"快速移动", 
	},
}
minions["Metadata/Monsters/TemplarSlaveDriver/TemplarSlaveDriverKitava"] = {
	name = "疯狂驱刑者",
	life = 1,
	armour = 0.25,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.845,
	attackRange = 8,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	weaponType2 = "One Handed Mace",
	skillList = {
		"SlaverTaunt",
		"Melee",
		"KitavaSlavedriverFlameWhip",
	},
	modList = {
		-- MonsterImplicitFastRun4 [base_movement_velocity_+% = 20]
	},
	modListSP = {
		"快速移动", 
	},
}
-- Undying
minions["Metadata/Monsters/Undying/CityStalkerMaleCasterArmour"] = {
	name = "不朽福音",
	life = 1.2,
	armour = 0.5,
	fireResist = 37,
	coldResist = 37,
	lightningResist = 37,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.245,
	attackRange = 7,
	accuracy = 1,
	skillList = {
		"Melee",
		"DelayedBlast",
		"MonsterProximityShield",
		"DelayedBlastSpectre",
	},
	modList = {
	},
	modListSP = {
	},
}
minions["Metadata/Monsters/Undying/UndyingOutcastPuncture"] = {
	name = "不朽暗影",
	life = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.65,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"Melee",
		"MonsterPuncture",
	},
	modList = {
		-- MonsterCastsPunctureText [monster_casts_puncture_text = 1]
	},
	modListSP = {
		"施放放血", 
	},
}
minions["Metadata/Monsters/Undying/UndyingOutcastWhirlingBlades"] = {
	name = "不朽放逐者",
	life = 1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.65,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"Melee",
		"UndyingWhirlingBlades",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Wicker Man
minions["Metadata/Monsters/WickerMan/WickerMan"] = {
	name = "诡异行者",
	life = 2.25,
	armour = 1,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 10,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
		"WickerManRighteousFire",
		"WickerManMoltenStrike",
		"MonsterRighteousFireWhileSpectred",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Redemption Sentry
minions["Metadata/Monsters/AtlasExiles/EyrieInfluenceMonsters/EyrieSeraphArcherSpectre"] = {
	name = "救赎哨兵",
	life = 2.7,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 70,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"WalkEmergeAtlasInfluenceMonster",
		"MeleeEyrieArrow",
		"AtlasEyrieArcherMortar",
		"AtlasEyrieArcherSnipe",
		"AtlasEyrieArcherSnipeTrickshot",
		"EmptyActionAttackEyrieArcherTrickshot",
		"AtlasEyrieArcherGeometryProjectiles",
		"AtlasExileEyrieArcherSpawnCrystal",
		"AtlasEyrieArcherCrystalImpact",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Baranite Thaumaturge
minions["Metadata/Monsters/AtlasExiles/CrusaderInfluenceMonsters/CrusaderMageguardCasterSpectre"] = {
	name = "追随巴兰的奇术师",
	life = 4.05,
	energyShield = 0.8,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	skillList = {
		"AtlasExilesCrusaderMageguardProjectile",
		"EmptyActionSpellCrusaderMageguard",
		"AtlasCrusaderMageguardSpawnBombSpectre",
		"AtlasExileCrusaderMageguardBombExplodeSpectre",
		"AtlasCrusaderMageguardBeam",
		"WalkEmergeAtlasInfluenceMonster",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Baranite Sister
minions["Metadata/Monsters/AtlasExiles/CrusaderInfluenceMonsters/CrusaderBlessedSisterSpectre"] = {
	name = "追随巴兰的修女",
	life = 1.2,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.8,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"AtlasCrusaderSisterMortarSpectre",
		"WalkEmergeAtlasInfluenceMonster",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Baranite Preacher
minions["Metadata/Monsters/AtlasExiles/CrusaderInfluenceMonsters/CrusaderTemplarJudgeSpectre"] = {
	name = "追随巴兰的教士",
	life = 1.68,
	energyShield = 0.2,
	armour = 0.5,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"AtlasCrusaderJudgeBallLightning",
		"AtlasCruasderJudgeFadingNova",
		"WalkEmergeAtlasInfluenceMonster",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Scale of Esh
minions["Metadata/Monsters/SandLeaper/SandLeaperBreachSpectre_"] = {
	name = "艾许之鳞",
	life = 3,
	fireResist = 30,
	coldResist = 30,
	lightningResist = 30,
	chaosResist = 20,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"Melee",
		"SandLeaperDodgeLeft",
		"SandLeaperDodgeRight",
		"BreachLightningWhip",
		"BreachArc",
		"BreachTeamWarp",
		"BreachLightningOrbsCommander",
	},
	modList = {
		-- MonsterBreachQuantityCommander [monster_dropped_item_quantity_+% = 700]
		-- MonsterBreachRarityCommander [monster_dropped_item_rarity_+% = 1000]
		-- BreachReducedBeyondPortalChance [monster_beyond_portal_chance_+%_final = -66]
	},
	modListSP = {
	  "怪物掉落调整数量提高 700%", 
		  "怪物掉落调整稀有度提高 1000%", 
		  "怪物召唤超越传送门几率 -66%",
	},
}
-- Scinteel Synthete
minions["Metadata/Monsters/LeagueSynthesis/SynthesisSoulstealer3Spectre"] = {
	name = "菲刃融合体",
	life = 5,
	energyShield = 0.8,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 85,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"SynthesisSoulstealerProjectileLightning",
		"EmptyActionSynthesisSoulstealerArc",
		"SynthesisSoulstealerLaser",
		"SynthesisSoulstealerBolt",
		"GeometryTriggerSynthesisSoulstealer3",
	},
	modList = {
		-- MonsterTagSynthesised
		-- MonsterSynthesisLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 700] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
	},
	modListSP = {
	"忆境怪物",
		"忆境怪物掉落加成（大）",
		"怪物掉落物品数量+700%",
		"怪物掉落物品稀有度+1500%",
	},
}
-- Redemption Knight
minions["Metadata/Monsters/AtlasExiles/EyrieInfluenceMonsters/EyrieSeraphFighterSpectre_"] = {
	name = "救赎骑士",
	life = 2.7,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 14,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	weaponType2 = "Shield",
	skillList = {
		"MeleeCold",
		"WalkEmergeAtlasInfluenceMonster",
		"AtlasEyrieFighterSlash",
		"EmptyActionAttackEyrieFighter",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Primal Crushclaw
minions["Metadata/Monsters/LeagueHarvest/Blue/HarvestNessaCrabT3Spectre"] = {
	name = "原始利爪",
	life = 6,
	armour = 1,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 14,
	accuracy = 1,
	skillList = {
		"MeleeCold",
		"HarvestCrabDashSlam",
		"GAHarvestCrabDashSlam",
		"HarvestNessaCrabScreech",
		"HarvestCrabAbyssSlam",
		"EASHarvestEmerge",
	},
	modList = {
		-- MonsterHarvestT3DropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 720] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
		-- BreachReducedBeyondPortalChance [monster_beyond_portal_chance_+%_final = -66]
		-- MapMonsterReducedCurseEffect [unique_boss_curse_effect_on_self_+%_final = -33]
	},
	modListSP = {
	},
}
-- Templar Tactician
minions["Metadata/Monsters/LegionLeague/LegionTemplarCaster1Spectre"] = {
	name = "圣堂战术家",
	life = 3.45,
	energyShield = 0.4,
	armour = 0.5,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 10,
	accuracy = 1,
	skillList = {
		"Melee",
		"LegionTemplarJudgeStormCall",
		"LegionTemplarJudgeBallLightning",
		"GeometryTriggerLegionTemplarCasterStormCall",
	},
	modList = {
		-- MonsterIgnoresDelveDarkness [monster_ignores_delve_darkness_mechanic = 1]
		-- MonsterLegionDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 125] [monster_dropped_item_rarity_+% = 750] [monster_no_map_drops = 1]
		-- BreachReducedBeyondPortalChance [monster_beyond_portal_chance_+%_final = -66]
	},
	modListSP = {
	},
}
-- Frost Auto-Scout
minions["Metadata/Monsters/LeagueHeist/Robot/RobotClockworkGolemColdSpectre"] = {
	name = "冰霜斥候",
	life = 3.6,
	armour = 1,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 10,
	accuracy = 1,
	skillList = {
		"DoLiterallyNothing",
		"MPSHeistRobotClockworkGolemBasicProjectile",
		"MMSHeistRobotClockworkGolemMortarSpectre",
		"ChangeToStance1Heist",
	},
	modList = {
		-- MonsterNoMapDrops [monster_no_map_drops = 1]
	},
	modListSP = {
	},
}
-- Syndicate Operative
minions["Metadata/Monsters/LeagueBetrayal/BetrayalSecretPolice2Spectre_"] = {
	name = "辛迪加侦探",
	life = 2.1,
	energyShield = 0.08,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.12,
	damageSpread = 0.2,
	attackTime = 0.6,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"Melee",
		"WalkEmergeBetrayal",
		"BetrayalSecretPoliceCurveDagger1",
		"BetrayalSecretPoliceCurveDagger2",
		"BetrayalSecretPoliceCurveDagger3",
		"EmptyActionAttackSecretPoliceDaggers",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Cloud retch
minions["Metadata/Monsters/AtlasExiles/EyrieInfluenceMonsters/EyrieKiwethSpectre"] = {
	name = "毒云",
	life = 2.52,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 40,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.68,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 11,
	accuracy = 1,
	skillList = {
		"MeleeCold",
		"WalkEmergeAtlasInfluenceMonster",
		"AtlasEyrieKiwethMortarSpectre",
		"AtlasEyrieKiwethMortarShards",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Artless Assassin
minions["Metadata/Monsters/LeagueHeist/Thug/ThugRanged1EliteSpectre"] = {
	name = "拙劣刺客",
	life = 5.2,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.56,
	damageSpread = 0.2,
	attackTime = 1,
	attackRange = 60,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"MPWHeistThugRangedBurningArrow",
		"DoLiterallyNothing",
		"GAHeistThugRangedArrowShotgun",
		"EAAHeistThugRangedExplosiveArrowBarrage",
		"HeistThugRangedExplosiveArrow",
		"GAHeistThugRangedShotgun",
		"WalkEmergeHeistThug",
		"EAAHeistThugRangedExplosiveArrowBarrageChokepoint",
		"ChangeToStance1Heist",
		"EASHeistMindControlSuicide",
	},
	modList = {
		-- MonsterNoMapDrops [monster_no_map_drops = 1]
		-- MonsterHarvestT1DropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 100] [monster_dropped_item_rarity_+% = 525] [monster_no_map_drops = 1]
	},
	modListSP = {
	},
}
-- Ashblessed Warden
minions["Metadata/Monsters/LeagueHeist/Robot/RobotPyreKnightEliteSpectre"] = {
	name = "灰祝守卫",
	life = 6,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.58,
	damageSpread = 0.2,
	attackTime = 1.17,
	attackRange = 10,
	accuracy = 1,
	skillList = {
		"DoLiterallyNothing",
		"WalkEmergeHeistRobotElevator",
		"GSHeistRobotPyreBeamBlast",
		"GSHeistRobotPyreNukeBeam",
		"GSHeistRobotPyreNukeBeamChannelled",
		"EASHeistRobotPyreBeamSweep",
		"GSHeistRobotPyreBeamSweepBeam",
		"ChangeToStance1Heist",
	},
	modList = {
		-- MonsterNoMapDrops [monster_no_map_drops = 1]
		-- MonsterHarvestT1DropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 100] [monster_dropped_item_rarity_+% = 525] [monster_no_map_drops = 1]
	},
	modListSP = {
	},
}
-- Snow Rhex
minions["Metadata/Monsters/AtlasExiles/EyrieInfluenceMonsters/EyrieArmouredBirdSpectre__"] = {
	name = "雪凶鸟",
	life = 4.5,
	armour = 0.5,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 14,
	accuracy = 1,
	skillList = {
		"MeleeCold",
		"WalkEmergeAtlasInfluenceMonster",
		"MeleeEyrieBird",
		"AtlasEyrieBirdBreath",
		"AtlasEyrieBirdBreathNoEffects",
	},
	modList = {
	},
	modListSP = {
	},
}
-- Flickershade
minions["Metadata/Monsters/Maligaro/SecretDesecrateMonster"] = {
	name = "摇拽之影",
	life = 3,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.05,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 25,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"SecretDesecrateMonsterTeleport",
		"SecretDesecrateMonsterEarthquakeTriggered",
		"SecretDesecrateMonsterMultiSlash",
	},
	modList = {
		-- MonsterOneThirdDamageTaken [base_damage_taken_+% = -67]
		mod("PhysicalDamageConvertToChaos", "BASE", 50), -- MonsterConvertToChaos1 [base_physical_damage_%_to_convert_to_chaos = 50]
	},
	modListSP = {
		"承受的伤害降低 67%",
		"50% 的物理伤害转换为混沌伤害"
	},
}


--lucifer


minions["Metadata/Monsters/Goatman/GoatmanShamanLightningChampion"] = {
	name = "羊人唤空者",
	life = 1.4,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 75,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 8,
	accuracy = 1,
	damageFixup = 0.11,
	weaponType1 = "Staff",
	skillList = {
		"Melee",
		"MonsterShockNova",
		"MonsterSpark",
		"OrbOfStormsGoatmanShamanChampion",
	},
	modList = {
		-- MonsterSpeedAndDamageFixupSmall [monster_base_type_attack_cast_speed_+%_and_damage_-%_final = 11]
		mod("Speed", "INC", -50, ModFlag.Cast), -- MonsterGoatmanShamanCastSpeed [base_cast_speed_+% = -50]
		-- MonsterCastsShockNovaText [monster_casts_shock_nova_text = 1]
		-- MonsterCastsSparkText [monster_casts_spark_text = 1]
	},
	modListSP = {
		"怪物速度和伤害调整（小）", 
		"羊人怪物施法速度调整", 
		"施放闪电新星", 
		"施放电球", 
	},
}


--Ancient Wraith
minions["Metadata/Monsters/LeagueDelve/GhostEncounter/Wraith"] = {
	name = "远古恶灵",
	life = 1.68,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"WraithEtherealKnives",
		"Melee",
	},
	modList = {
		-- MonsterDelveDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 300] [monster_no_map_drops = 1]
		-- DelveMonsterEnfeebleOnHit [curse_on_hit_level_enfeeble = 8]
		-- AdditionalCurseOnEnemies_ [number_of_additional_curses_allowed = 1]
	},
	modListSP = {
		"怪物掉落调整（矿坑）", 
		"DelveMonsterEnfeebleOnHit", 
		"AdditionalCurseOnEnemies_", 
	},
}


--Ancient Suffering
minions["Metadata/Monsters/LeagueDelve/GhostEncounter/WraithPurple"] = {
	name = "远古冤魂",
	life = 1.68,
	energyShield = 0.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"DelveWraithScreechChaos",
	},
	modList = {
		-- MonsterDelveLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 200] [monster_dropped_item_rarity_+% = 1000] [monster_no_map_drops = 0]
		-- MonsterChanceToTemporalChainsOnHit1 [curse_on_hit_%_temporal_chains = 100]
		-- AdditionalCurseOnEnemies_ [number_of_additional_curses_allowed = 1]
	},
	modListSP = {
		"MonsterDelveLargeDropModifiers_", 
		"击中造成时空锁链", 
		"AdditionalCurseOnEnemies_", 
	},
}


--Farric Tiger
minions["Metadata/Monsters/LeagueBestiary/TigerBestiaryMinion"] = {
	name = "大地之虎",
	life = 6,
	armour = 0.5,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.2,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"WalkEmergeBestiaryHellion",
	},
	modList = {
		-- MonsterBestiaryDropModifiers [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 0] [monster_dropped_item_rarity_+% = 0] [monster_no_map_drops = 1]
	},
	modListSP = {
		"MonsterBestiaryDropModifiers", 
	},
}

--Craicic Chimeral
minions["Metadata/Monsters/LeagueBestiary/GemFrogCrabSpiritBossMinion_"] = {
	name = "深海奇美拉",
	life = 6,
	fireResist = 0,
	coldResist = 30,
	lightningResist = 30,
	chaosResist = 0,
	damage = 0.9,
	damageSpread = 0.2,
	attackTime = 1.005,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"GemFrogLeapSlam",
	},
	modList = {
		-- MonsterLeapsOntoEnemiesText [monster_leaps_onto_enemies_text = 1]
	},
	modListSP = {
		"跃击", 
	},
}

--Undying Operator



minions["Metadata/Monsters/Undying/CityStalkerMaleWorkerLightning2_"] = {
	name = "不朽操作者",
	life = 1,
	armour = 0.3,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 0.75,
	damageSpread = 0.2,
	attackTime = 1.245,
	attackRange = 7,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"Melee",
		"BreachLightningOrbsRefinery",
		"CityStalkerStaticStrike",
	},
	modList = {
	},
	modListSP = {
	},
}


minions["Metadata/Monsters/SlaveCatcher/SlaveCatcherKitava"] = {
	name = "疯狂奴隶",
	life = 1.2,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"SlaveCatcherNetThrow",
		"DeceleratingProjectile",
		"SpellNovaKitava",
	},
	modList = {
	},
	modListSP = {
	},
}

-- Heretical Guardian
minions["Metadata/Monsters/ReligiousTemplar/ReligiousTemplarTwoHandedKitava"] = {
	name = "异教卫士",
	life = 1.88,
	energyShield = 0.16,
	armour = 0.4,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.25,
	damageSpread = 0.2,
	attackTime = 1.95,
	attackRange = 11,
	accuracy = 1,
	weaponType1 = "Two Handed Sword",
	skillList = {
		"Melee",
		"ReligiousTemplarCultistWeaponThrow",
		"MonsterProximityShield",
	},
	modList = {
	},
	modListSP = {
	},
}

-- Temple Guardian

minions["Metadata/Monsters/ReligiousTemplar/ReligiousTemplarTwoHandedPure"] = {
	name = "神寺卫士",
	life = 1.88,
	energyShield = 0.16,
	armour = 0.4,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.25,
	damageSpread = 0.2,
	attackTime = 1.95,
	attackRange = 11,
	accuracy = 1,
	weaponType1 = "Two Handed Sword",
	skillList = {
		"Melee",
		"ReligiousTemplarWeaponThrow",
		"MonsterProximityShield",
	},
	modList = {
	},
	modListSP = {
	},
}

-- Gut Spiker
minions["Metadata/Monsters/HalfSkeleton/HalfSkeletonRanged"] = {
	name = "裂脏锋刃",
	life = 1.21,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.16,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 10,
	accuracy = 1,
	weaponType1 = "One Handed Mace",
	skillList = {
		"Melee",
		"HalfSkeletonProjectile",
	},
	modList = {
	},
	modListSP = {
	},
}

-- Gorgol Alpha

minions["Metadata/Monsters/LeagueDelve/QiongqiChampionSpikedSpawned"] = {
	name = "穷奇首领",
	life = 4.88,
	armour = 1,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.31,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 12,
	accuracy = 1,
	skillList = {
		"DelveMeleeFire",
		"DelveFlamethrowerLeftToRight",
		"DelveFlamethrowerRightToLeft",
		"DelveQiongqiSlash",
		"DelveQiongqiSlam",
		"EmptyActionQiongqiSpiked",
		"DelveQiongqiTornado",
	},
	modList = {
		-- MonsterDelveLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 200] [monster_dropped_item_rarity_+% = 1000] [monster_no_map_drops = 0]
		-- CannotBeUsedAsMinion [cannot_be_used_as_minion = 1]
	},
	modListSP = {
		"MonsterDelveLargeDropModifiers_", 
		"CannotBeUsedAsMinion", 
	},
}
minions["Metadata/Monsters/LeagueDelve/QiongqiChampionSpiked"] = {
	name = "穷奇首领",
	life = 4.88,
	armour = 1,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.31,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 12,
	accuracy = 1,
	skillList = {
		"DelveMeleeFire",
		"DelveFlamethrowerLeftToRight",
		"DelveFlamethrowerRightToLeft",
		"DelveQiongqiSlash",
		"DelveQiongqiSlam",
		"EmptyActionQiongqiSpiked",
		"DelveQiongqiTornado",
	},
	modList = {
		-- MonsterDelveLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 200] [monster_dropped_item_rarity_+% = 1000] [monster_no_map_drops = 0]
	},
	modListSP = {
		"MonsterDelveLargeDropModifiers_", 
	},
}
 
 
--Sun Bleached Vanguard
minions["Metadata/Monsters/SkeletonSoldier/SkeletonSoldierRangedTornadoShotBleached"] = {
	name = "阳洁先锋",
	life = 1.1,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 40,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"Melee",
		"SkeletonSoldierTornadoShot",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
	},
	modListSP = {
		"亡灵生物", 
	},
}

--Turong
minions["Metadata/Monsters/LeagueDelve/TaowuChampionSpectre"] = {
	name = "梼杌",
	life = 5.25,
	energyShield = 0.2,
	armour = 0.5,
	fireResist = 75,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.31,
	damageSpread = 0.2,
	attackTime = 1.335,
	attackRange = 10,
	accuracy = 1,
	skillList = {		
		"FireballTaowuDash",
		"FireballTaowuCombo",
		"DelveMeleeFire",
		"EmptyActionAttackTaowuDash",
		"AddBuffToTargetDelveDarkZone",
		"DelveTaowuSlash",
		"EmptyActionAttackTaowuDashSwipe",
		"DelveTaowuDashAttack",
		"DelveTaowuBackwardsSlash",
		"WalkEmergeDelveWetaUpForward",
	},
	modList = {
		-- MonsterDelveLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 200] [monster_dropped_item_rarity_+% = 1000] [monster_no_map_drops = 0]
	},
	modListSP = {
		"矿坑怪物掉落加成（大）",
		"怪物掉落物品数量+200%",
		"怪物掉落物品稀有度+1000%",
		"怪物不掉落地图"
		
	},
}

--Flayed Lookout
minions["Metadata/Monsters/LeagueBetrayal/BetrayalSkeletonRangedSpectre"] = {
	name = "无皮哨探",
	life = 1.2,
	armour = 0.15,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 80,
	accuracy = 1,
	weaponType1 = "Bow",
	skillList = {
		"BetrayalSkeletonMelee",
		"WalkEmergeBetrayal",
		"BetrayalSkeletonSnipe",
	},
	modList = {
		-- MonsterNecromancerRaisable [undead_description = 1]
	},
	modListSP = {
		"亡灵生物", 
	},
}


-- Baranite Cleric
minions["Metadata/Monsters/AtlasExiles/CrusaderInfluenceMonsters/CrusaderBlackguardClericSpectre"] = {
	name = "追随巴兰的牧师",
	life = 1.2,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 0,
	lightningResist = 40,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.995,
	attackRange = 40,
	accuracy = 1,
	skillList = {
		"AtlasExilesCrusaderClericBlast",
		"WalkEmergeAtlasInfluenceMonster_SP",
	},
	modList = {
  
		-- AtlasCrusaderClericAuraSpectre [physical_damage_%_to_add_as_lightning = 20] [base_chance_to_shock_% = 10]
		--   mod("ExtraAura", "LIST", { mod =  mod("PhysicalDamageGainAsLightning", "BASE", 20) }),
		-- mod("ExtraAura", "LIST", { mod =  mod("EnemyShockChance", "BASE", 10) }),
		 
	},
	modListSP = {
		"巴兰牧师光环（10%感电几率、附加 20% 物理伤害的闪电伤害）", 
	},
}


--Snowcaller
minions["Metadata/Monsters/AtlasExiles/EyrieInfluenceMonsters/EyrieArcticCrystalCasterSpectre_"] = {
	name = "唤雪者",
	life = 4.05,
	energyShield = 0.16,
	fireResist = 0,
	coldResist = 75,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 14,
	accuracy = 1,
	skillList = {
		"WalkEmergeAtlasInfluenceMonster",
		"AtlasExileEyrieCasterProjectile",
		"AtlasEyrieIceSpear",
		"AtlasEyrieArcticCasterBlast",
	},
	modList = {
	},
	modListSP = {
		 
	},
}

--Mindweave Sentinel
minions["Metadata/Monsters/LeagueSynthesis/SynthesisRibbonLargeColdSpectre"] = {
	name = "织心哨兵",
	life = 4.5,
	energyShield = 0.4,
	fireResist = 0,
	coldResist = 85,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 6,
	accuracy = 1,
	skillList = {
		"SynthesisRibbonProjectile",
		"SynthesisRibbonMortar",
		"SynthesisRibbonGeometryTrigger",
		"SynthesisRibbonMassMortar",
	},
	modList = {
		-- MonsterTagSynthesised
		-- MonsterSynthesisLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 700] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
	},
	modListSP = {
		"忆境怪物",
		"忆境怪物掉落加成（大）",
		"怪物掉落物品数量+700%",
		"怪物掉落物品稀有度+1500%",
		"怪物不掉落地图",
		 
	},
}

--Frosal Synthete
minions["Metadata/Monsters/LeagueSynthesis/SynthesisSoulstealer2Spectre"] = {
	name = "冰双融合体",
	life = 5,
	energyShield = 0.8,
	fireResist = 0,
	coldResist = 85,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"SynthesisSoulstealerProjectileCold",
		"EmptyActionSynthesisColdCascade",
		"SynthesisColdCascadeObject",
		"SynthesisColdCascadeGeometry",
		"SynthesisColdRend",
		"SynthesisIceSpear",
	},
	modList = {
		-- MonsterTagSynthesised
		-- MonsterSynthesisLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 700] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
	},
	modListSP = {
		 "忆境怪物",
		"忆境怪物掉落加成（大）",
		"怪物掉落物品数量+700%",
		"怪物掉落物品稀有度+1500%",
		"怪物不掉落地图",
	},
}



--Flaric Synthete
minions["Metadata/Monsters/LeagueSynthesis/SynthesisSoulstealer1Spectre"] = {
	name = "纤威融合体",
	life = 5,
	energyShield = 0.8,
	fireResist = 85,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"SynthesisSoulstealerProjectileFire",
		"SynthesisSelfFlameblast",
		"SynthesisEnergySlice",
		"SynthesisSoulstealerFireStab",
		"DashToTarget",
	},
	modList = {
		-- MonsterTagSynthesised
		-- MonsterSynthesisLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 700] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
	},
	modListSP = {
		  "忆境怪物",
		"忆境怪物掉落加成（大）",
		"怪物掉落物品数量+700%",
		"怪物掉落物品稀有度+1500%",
		"怪物不掉落地图",
	},
}

--Aurid Synthete
minions["Metadata/Monsters/LeagueSynthesis/SynthesisSoulstealer4Spectre"] = {
	name = "酸试融合体",
	life = 5,
	energyShield = 0.8,
	fireResist = 42,
	coldResist = 42,
	lightningResist = 42,
	chaosResist = 0,
	damage = 1.5,
	damageSpread = 0.2,
	attackTime = 1.305,
	attackRange = 8,
	accuracy = 1,
	skillList = {
		"SynthesisSoulstealerProjectilePhysical",
		"SynthesisSoulstealerQuicksand",
		"SynthesisSoulstealerDrones",
		"EmptyActionSynthesisEnrageDrones",
		"SynthesisSoulstealerDroneEnrage",
		"GeometrySpellSynthesisPhysical",
		"SynthesisPhysicalTripleMortar",
		"SynthesisSoulstealerBombDetonate",
		"SynthesisSoulstealerDronesOnSelf",
		"SynthesisPhysicalVolatileSlam",
		"SynthesisQuicksandStartEffect",
	},
	modList = {
		-- MonsterTagSynthesised
		-- MonsterSynthesisLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 700] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
	},
	modListSP = {
		  "忆境怪物",
		"忆境怪物掉落加成（大）",
		"怪物掉落物品数量+700%",
		"怪物掉落物品稀有度+1500%",
		"怪物不掉落地图",
	},
}

--Winged Synthete
minions["Metadata/Monsters/LeagueSynthesis/SynthesisWyvernSpectre"] = {
	name = "展翼的融合体",
	life = 0.9,
	energyShield = 0.1,
	fireResist = 20,
	coldResist = 20,
	lightningResist = 20,
	chaosResist = 0,
	damage = 1.1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 12,
	accuracy = 1,
	skillList = {
		"Melee",
		"SynthesisWyvernProjectile",
		"SynthesisWyvernMortar",
	},
	modList = {
		-- MonsterTagSynthesised
		-- MonsterSynthesisLargeDropModifiers_ [monster_slain_experience_+% = 0] [monster_dropped_item_quantity_+% = 700] [monster_dropped_item_rarity_+% = 1500] [monster_no_map_drops = 0]
	},
	modListSP = {
		"忆境怪物",
		"忆境怪物掉落加成（大）",
		"怪物掉落物品数量+700%",
		"怪物掉落物品稀有度+1500%",
		"怪物不掉落地图",
	},
}


-- They of Tul
minions["Metadata/Monsters/MinerLarge/MinerLargeCommanderBreachSpectre"] = {
	name = "托沃的它",
	life = 3,
	armour = 0.5,
	fireResist = 30,
	coldResist = 30,
	lightningResist = 30,
	chaosResist = 20,
	damage = 1.2,
	damageSpread = 0.2,
	attackTime = 1.755,
	attackRange = 9,
	accuracy = 1,
	skillList = {
		"Melee",
		"BreachBlizzard",
		"SummonBreachIceTotem",
	},
	modList = {
		-- MonsterBreachQuantityCommander [monster_dropped_item_quantity_+% = 700]
		-- MonsterBreachRarityCommander [monster_dropped_item_rarity_+% = 1000]
		-- BreachReducedBeyondPortalChance [monster_beyond_portal_chance_+%_final = -66]
		-- MonsterKillTrapsMinesTotemsOnDeath [kill_traps_mines_and_totems_on_death = 1]
	},
	modListSP = {
		 "怪物掉落调整数量提高 700%", 
		  "怪物掉落调整稀有度提高 1000%", 
		  "怪物召唤超越传送门几率 -66%",
		  
	},
}

-- Xoph's Favoured
minions["Metadata/Monsters/Hellion/HellionBreachHowlSpectre"] = {
	name = "索伏的青睐",
	life = 4.68,
	armour = 0.1,
	fireResist = 40,
	coldResist = 0,
	lightningResist = 0,
	chaosResist = 0,
	damage = 1,
	damageSpread = 0.2,
	attackTime = 1.5,
	attackRange = 7,
	accuracy = 1,
	weaponType1 = "One Handed Sword",
	skillList = {
		"Melee",
		"EmpoweringHowlSpectre",
		"BreachCleave",
	},
	modList = {
		-- MonsterBreachQuantity [monster_dropped_item_quantity_+% = 100]
		-- MonsterBreachRarity [monster_dropped_item_rarity_+% = 300]
		-- BreachReducedBeyondPortalChance [monster_beyond_portal_chance_+%_final = -66]
	},
	modListSP = {
		  "怪物掉落调整数量提高 100%", 
		  "怪物掉落调整稀有度提高 300%", 
		  "怪物召唤超越传送门几率 -66%",
	},
}

--Hyrri's Watch
minions["Metadata/Monsters/LegionLeague/LegionKaruiArcher"] = {
    name = "西里的守望",
    life = 2.25,
    fireResist = 20,
    coldResist = 20,
    lightningResist = 20,
    chaosResist = 0,
    damage = 1.1,
    damageSpread = 0.2,
    attackTime = 1.5,
    attackRange = 50,
    accuracy = 1,
    weaponType1 = "Bow",
    skillList = {
        "MeleeKaruiArcher",
        "LegionKaruiArcherSnipe",
    },
    modList = {
    },modListSP = {
		
	},
}
